In [1]:
from pathlib import Path
from typing import List, Tuple, Dict
import json, random, itertools, statistics as st
import seqeval

import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import KFold, train_test_split
from collections import Counter
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import BallTree
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from sklearn.cluster import KMeans

import torch
from transformers import (
    AutoTokenizer,
        AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)

from seqeval.metrics import f1_score, classification_report
from evaluate import load as load_metric
from tqdm.auto import tqdm

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Configuração e Verificação Inicial

In [2]:
SEED_GLOBAL = 42
random.seed(SEED_GLOBAL)
np.random.seed(SEED_GLOBAL)
torch.manual_seed(SEED_GLOBAL)

CSV_PATH = Path("data/cachacaNER.csv")  # ajuste se necessário
MODEL_NAME = "pierreguillou/bert-base-cased-pt-ner"

df = pd.read_csv(CSV_PATH)

In [3]:
for cand in ["sentence_id", "sentence", "sent_id"]:
    if cand in df.columns:
        SENT_COL = cand
        break
else:
    raise KeyError(f"Coluna de sentença não encontrada em {list(df.columns)}")


def sent_to_record(sent_id, g):
    return {
        "sentence_id": int(sent_id),
        "tokens": g["token"].tolist(),
        "ner_tags": g["tag"].tolist(),
    }

In [4]:
records = [sent_to_record(i, g) for i, g in df.groupby(SENT_COL, sort=False)]
cachaca_full = Dataset.from_list(records)

In [5]:
cachaca_full

Dataset({
    features: ['sentence_id', 'tokens', 'ner_tags'],
    num_rows: 13628
})

In [6]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({lab for sent in cachaca_full["ner_tags"] for lab in sent})
label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [7]:
id2label

{0: 'B-CARACTERISTICA_SENSORIAL_AROMA',
 1: 'B-CARACTERISTICA_SENSORIAL_CONSISTÊNCIA',
 2: 'B-CARACTERISTICA_SENSORIAL_COR',
 3: 'B-CARACTERISTICA_SENSORIAL_SABOR',
 4: 'B-CLASSIFICACAO_BEBIDA',
 5: 'B-EQUIPAMENTO_DESTILACAO',
 6: 'B-GRADUACAO_ALCOOLICA',
 7: 'B-NOME_BEBIDA',
 8: 'B-NOME_LOCAL',
 9: 'B-NOME_ORGANIZACAO',
 10: 'B-NOME_PESSOA',
 11: 'B-PRECO',
 12: 'B-RECIPIENTE_ARMAZENAMENTO',
 13: 'B-TEMPO',
 14: 'B-TEMPO_ARMAZENAMENTO',
 15: 'B-TIPO_MADEIRA',
 16: 'B-VOLUME',
 17: 'I-CARACTERISTICA_SENSORIAL_AROMA',
 18: 'I-CARACTERISTICA_SENSORIAL_CONSISTÊNCIA',
 19: 'I-CARACTERISTICA_SENSORIAL_COR',
 20: 'I-CARACTERISTICA_SENSORIAL_SABOR',
 21: 'I-CLASSIFICACAO_BEBIDA',
 22: 'I-EQUIPAMENTO_DESTILACAO',
 23: 'I-GRADUACAO_ALCOOLICA',
 24: 'I-NOME_BEBIDA',
 25: 'I-NOME_LOCAL',
 26: 'I-NOME_ORGANIZACAO',
 27: 'I-NOME_PESSOA',
 28: 'I-PRECO',
 29: 'I-RECIPIENTE_ARMAZENAMENTO',
 30: 'I-TEMPO',
 31: 'I-TEMPO_ARMAZENAMENTO',
 32: 'I-TIPO_MADEIRA',
 33: 'I-VOLUME',
 34: 'O'}

In [8]:
NUM_LABELS

35

# Splits

In [9]:
def split_standard(ds: Dataset) -> DatasetDict:
    """Usa coluna trainingTest do CSV (80/20 original)."""
    if "trainingTest" not in df.columns:
        raise ValueError("CSV não contém a coluna 'trainingTest'")
    train_ids = df.loc[df["trainingTest"] == "training", SENT_COL].unique()
    test_ids = df.loc[df["trainingTest"] == "test", SENT_COL].unique()
    return DatasetDict(
        train=ds.filter(lambda ex: ex["sentence_id"] in train_ids),
        dev=ds.filter(lambda ex: ex["sentence_id"] in test_ids),
    )

In [10]:
def random_splits(
    ds: Dataset, test_size=0.2, seeds: List[int] = range(30)
) -> List[DatasetDict]:
    triples = []
    for s in seeds:
        train, dev = ds.train_test_split(test_size=test_size, seed=s).values()
        triples.append(DatasetDict(train=train, dev=dev))
    return triples

In [11]:
# def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
#     lengths = np.array([len(t) for t in ds["tokens"]])
#     thr = np.percentile(lengths, 100 * (1 - top_pct))
#     mask = lengths >= thr
#     return DatasetDict(train=ds.filter(~mask), dev=ds.filter(mask))


def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
    """20 % das sentenças mais longas viram conjunto de validação (dev)."""
    lengths = np.array([len(t) for t in ds["tokens"]])
    thr = np.percentile(lengths, 100 * (1 - top_pct))  
    mask = lengths >= thr  

    dev_idx = np.where(mask)[0].tolist()  # índices → list[int]
    train_idx = np.where(~mask)[0].tolist()

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Tamanho da sentenças


# def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
#     freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
#     rare = {w for w, c in freq.items() if c <= freq_thr}

#     def has_rare(example):
#         return any(w.lower() in rare for w in example["tokens"])

#     return DatasetDict(
#         train=ds.filter(lambda ex: not has_rare(ex)), dev=ds.filter(has_rare)
#     )


def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
    freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
    rare = {w for w, c in freq.items() if c <= freq_thr}

    keep_dev = []
    for sent in ds["tokens"]:
        print(sent)
        keep_dev.append(any(w.lower() in rare for w in sent))

    dev_idx = [i for i, x in enumerate(keep_dev) if x]
    train_idx = [i for i, x in enumerate(keep_dev) if not x]

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Raridade dos tokens

In [12]:
def split_adversarial(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    embeds = model.encode([" ".join(t) for t in ds["tokens"]], show_progress_bar=False)
    tree = BallTree(embeds, leaf_size=40)

    idx_train, idx_test = set(range(len(ds))), []
    # semente = ponto mais central
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    idx_train.remove(seed_idx)
    idx_test.append(seed_idx)
    print(k)
    while len(idx_test) < k:
        print(len(idx_test))
        dists, _ = tree.query(embeds[list(idx_train)], k=1, return_distance=True)
        nxt = list(idx_train)[int(np.argmax(dists))]
        idx_train.remove(nxt)
        idx_test.append(nxt)

    return DatasetDict(
        train=ds.select(sorted(idx_train)),
        dev=ds.select(sorted(idx_test)),
    )

    # Maximizando Wassertein Distance


def split_adversarial_fast(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    """
    Farthest-Point Sampling aproximando Wasserstein – versão vetorizada.
    Seleciona pct_test (~20 %) das sentenças como conjunto 'dev'.
    """
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    embeds = model.encode(
        [" ".join(t) for t in ds["tokens"]],
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,  # acelera distância euclidiana ≈ cos
    )

    n = embeds.shape[0]
    idx_all = np.arange(n)

    # 1) ponto mais "central" (norma mais distante da média)
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    selected = [seed_idx]

    # 2) vetor de distâncias mínimas a qualquer ponto já escolhido
    min_dists = np.linalg.norm(embeds - embeds[seed_idx], axis=1)

    while len(selected) < k:
        next_idx = np.argmax(min_dists)
        selected.append(next_idx)

        # atualiza min_dists com a distância ao novo ponto — tudo de uma vez
        d_new = np.linalg.norm(embeds - embeds[next_idx], axis=1)
        min_dists = np.minimum(min_dists, d_new)

    train_idx = np.setdiff1d(idx_all, selected, assume_unique=True)

    return DatasetDict(
        train=ds.select(train_idx.tolist()),
        dev=ds.select(selected),
    )

In [13]:
# def loc_split(
#     dataset: Dataset, pct_test: float = 0.20, ngram: int = 4, seed: int = 42
# ) -> DatasetDict:
#     """
#     Split baseado em baixa sobreposição léxica (4-gram Jaccard).
#     Teste = pct_test das sentenças com menor overlap em relação ao pool.
#     """
#     # 1. Texto plano por sentença
#     docs = [" ".join(toks) for toks in dataset["tokens"]]

#     # 2. Vetorizar 4-grams (binário)
#     vect = CountVectorizer(
#         analyzer="word", ngram_range=(ngram, ngram), binary=True
#     ).fit(docs)
#     X = vect.transform(docs)

#     # 3. Similaridade Jaccard aproximada com matriz binária
#     # Jaccard(A,B) = |A∩B|/|A∪B| = 1 - |AΔB|/|A∪B|
#     # Usamos: overlap = (A·Bᵀ) / (|A|+|B|-A·Bᵀ)
#     bin_counts = X.sum(axis=1).A1

#     # Para cada doc i, escolhemos vizinho + próximo (fast):
#     from sklearn.metrics.pairwise import cosine_similarity

#     # (cosine no binário ∝ |A∩B|)
#     sim = cosine_similarity(X, dense_output=False)
#     # Soma dos top-k overlaps (k=5) como score
#     k = 5
#     topk = np.zeros(len(dataset))
#     for i in range(sim.shape[0]):
#         row = sim.getrow(i).toarray()[0]
#         idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
#         # overlap ≈ |∩|
#         inter = row[idx] * bin_counts[i]
#         uni = bin_counts[i] + bin_counts[idx] - inter
#         topk[i] = (inter / uni).mean()

#     # 4. Ordenar por overlap crescente ⇒ mais “novos” vão p/ teste
#     order = np.argsort(topk)
#     n_test = int(len(dataset) * pct_test)
#     test_idx = order[:n_test]
#     train_idx = order[n_test:]

#     return DatasetDict(
#         {"train": dataset.select(train_idx), "test": dataset.select(test_idx)}
#     )

In [14]:
def loc_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    ngram: int = 4,
    seed: int = 42,
) -> DatasetDict:
    """
    Divide por sobreposição léxica (n-gram Jaccard).
    Frações independentes para teste e validação.
    """
    docs = [" ".join(toks) for toks in dataset["tokens"]]

    vect = CountVectorizer(
        analyzer="word", ngram_range=(ngram, ngram), binary=True
    ).fit(docs)
    X = vect.transform(docs)
    bin_counts = X.sum(axis=1).A1

    sim = cosine_similarity(X, dense_output=False)
    k = 5
    topk = np.zeros(len(dataset))
    for i in range(sim.shape[0]):
        row = sim.getrow(i).toarray()[0]
        idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
        inter = row[idx] * bin_counts[i]
        uni = bin_counts[i] + bin_counts[idx] - inter
        topk[i] = (inter / uni).mean()

    order = np.argsort(topk)  # baixo → alto overlap
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[:n_test]
    val_idx = order[n_test : n_test + n_val]
    train_idx = order[n_test + n_val :]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [15]:
def semantic_cluster_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    k: int | None = None,
    seed: int = 42,
) -> DatasetDict:
    """
    Clusters SBERT → reserva clusters distantes para test/val.
    """
    if k is None:
        k = int(np.sqrt(len(dataset)))

    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    embeddings = sbert.encode(
        [" ".join(t) for t in tqdm(dataset["tokens"])],
        batch_size=64,
        show_progress_bar=False,
    )

    km = KMeans(n_clusters=k, random_state=seed, n_init=10).fit(embeddings)
    labels = km.labels_
    centroids = km.cluster_centers_

    global_center = embeddings.mean(0, keepdims=True)
    dists = pairwise_distances(centroids, global_center).flatten()

    clusters_sorted = np.argsort(-dists)  # mais distantes primeiro
    test_clusters, val_clusters = set(), set()
    total_test = total_val = 0
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    for c in clusters_sorted:
        size = np.sum(labels == c)
        if total_test < n_test:  # preenche primeiro o teste
            test_clusters.add(c)
            total_test += size
        elif total_val < n_val:  # depois a validação
            val_clusters.add(c)
            total_val += size
        if total_test >= n_test and total_val >= n_val:
            break

    test_idx = np.where([lbl in test_clusters for lbl in labels])[0]
    val_idx = np.where([lbl in val_clusters for lbl in labels])[0]
    train_idx = np.where(
        [lbl not in test_clusters and lbl not in val_clusters for lbl in labels]
    )[0]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [16]:
def difficulty_scores(dataset: Dataset) -> np.ndarray:
    length = np.array([len(tok) for tok in dataset["tokens"]], dtype=float)
    length = (length - length.mean()) / length.std()

    dens = []
    for labels in dataset["ner_tags"]:
        non_o = sum(1 for l in labels if l != "O")
        dens.append(non_o / len(labels))
    dens = np.array(dens)
    dens = (dens - dens.mean()) / dens.std()

    ent_types, freq = [], Counter()
    for labels in dataset["ner_tags"]:
        types = [l[2:] for l in labels if l != "O"]
        ent_types.append(types[0] if types else "NONE")
    freq.update(ent_types)
    rarity = np.array([1 / freq[t] for t in ent_types])
    rarity = (rarity - rarity.mean()) / rarity.std()

    return length + dens + rarity


def reverse_curriculum_split(
    dataset: Dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
) -> DatasetDict:
    scores = difficulty_scores(dataset)
    order = np.argsort(scores)  # easy→hard
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[-n_test:]  # hardest
    val_idx = order[-(n_test + n_val) : -n_test]
    train_idx = order[: -(n_test + n_val)]

    rng = np.random.RandomState(seed)
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    rng.shuffle(test_idx)

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [17]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42) -> DatasetDict:
    """Testa só sentenças ≥ máx(len_train)."""
    sent_lens = np.array([len(t) for t in dataset["tokens"]])
    # separação inicial train/dev (randômica estratificando por tamanho grosso)
    idx_all   = np.arange(len(dataset))
    train_idx, temp_idx = train_test_split(idx_all,
                                           test_size=pct_test + pct_val,
                                           stratify=(sent_lens//5),  # bin len
                                           random_state=seed)
    # define longo-threshold como tamanho máx. do treino
    max_train_len = sent_lens[train_idx].max()
    # test = sentenças > threshold.  Caso falte/ sobre exemplos, ajusta.
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]
    # completa ou reduz para atingir pct_test
    need = int(pct_test*len(dataset)) - len(test_idx)
    if need > 0:
        test_idx.extend(resto_idx[:need])
        val_idx = resto_idx[need:]
    else:
        val_keep = int(pct_val*len(dataset))
        val_idx  = resto_idx[:val_keep]
        test_idx = test_idx[: int(pct_test*len(dataset))]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 2) Heuristic Rare-Words ----------------------------------
def heur_rare_split(dataset: Dataset,
                    pct_test: float = 0.20,
                    pct_val : float = 0.10,
                    seed: int = 42) -> DatasetDict:
    """Testa frases que contenham palavras do quintil + raro."""
    # contagem de frequência de token
    freqs = Counter(w for toks in dataset["tokens"] for w in toks)
    # define rareza: 20 % mais raras
    thresh = np.quantile(list(freqs.values()), 0.20)
    rare_set = {w for w,c in freqs.items() if c <= thresh}
    is_rare = np.array([any(w in rare_set for w in toks)
                        for toks in dataset["tokens"]])
    rare_idx   = np.where(is_rare)[0]
    common_idx = np.where(~is_rare)[0]
    # garante proporções desejadas
    n_test = int(pct_test*len(dataset))
    n_val  = int(pct_val *len(dataset))
    rng = np.random.default_rng(seed)
    test_idx = rng.choice(rare_idx, size=min(len(rare_idx), n_test),
                          replace=False)
    resto_idx = [i for i in rare_idx if i not in test_idx] + list(common_idx)
    val_idx  = rng.choice(resto_idx, size=n_val, replace=False)
    train_idx = [i for i in resto_idx if i not in val_idx]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 3) Standard (80-10-10) -----------------------------------
def std_split(dataset: Dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42) -> DatasetDict:
    """Split aleatório estratificado por comprimento (PTB-like)."""
    idx = np.arange(len(dataset))
    strat = (np.array([len(t) for t in dataset["tokens"]]) // 5)
    train_idx, temp_idx = train_test_split(idx, test_size=pct_test+pct_val,
                                          stratify=strat, random_state=seed)
    val_rel = pct_val / (pct_test+pct_val)
    val_idx, test_idx = train_test_split(temp_idx, test_size=1-val_rel,
                                         stratify=strat[temp_idx],
                                         random_state=seed)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 4) Adversarial (approx. Wasserstein) ---------------------
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Seleciona k frases 'mais distantes' recursivamente (BallTree + W₂)
    para compor o teste, lembrando Alg.-1 de Søgaard et al.【turn6file4】.
    """
    # SBERT embed (rápido na GPU / aceitável CPU)
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(toks) for toks in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    # BallTree para vizinhança eficiente
    tree = BallTree(emb, leaf_size=40)
    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)
    print(f"Selecionando {int(pct_test*len(dataset))} sentenças para teste...")
    while len(test_idx) < int(pct_test*len(dataset)):
        print(f"  {len(test_idx)} selecionadas...")
        # amostra candidata: ponto + longe do centro
        center = emb[list(idx_pool)].mean(0, keepdims=True)
        dists, _ = tree.query(center, k=len(idx_pool))
        farthest = list(idx_pool)[int(dists.argmax())]
        # pega-se farest e seus k-NN mais próximos  ⇒ aumenta diversidade
        nn = tree.query([emb[farthest]], k=k, return_distance=False)[0]
        for j in nn:
            if j in idx_pool and len(test_idx) < int(pct_test*len(dataset)):
                test_idx.append(j)
                idx_pool.remove(j)
    # retira val
    val_size = int(pct_val*len(dataset))
    val_idx  = rng.choice(list(idx_pool), size=val_size, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [18]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42,
                   bin_size: int = 10) -> DatasetDict:
    """
    Teste = sentenças mais longas que max(len(train)).
    Robusto a datasets pequenos: se estratificação falhar, usa split aleatório.
    """
    rng = np.random.default_rng(seed)
    idx_all   = np.arange(len(dataset))
    sent_lens = np.array([len(t) for t in dataset["tokens"]])

    # ------ 1) tenta split estratificado por baldes -------------------------
    strat = (sent_lens // bin_size)
    try:
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            stratify=strat,
            random_state=seed,
        )
    except ValueError:                       # classes com 1 amostra
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # ------ 2) escolhe test = len > max(train) ------------------------------
    max_train_len = sent_lens[train_idx].max()
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]

    # garante tamanhos exatos
    n_test_desired = int(pct_test * len(dataset))
    n_val_desired  = int(pct_val  * len(dataset))

    # completa teste se ficou pequeno
    if len(test_idx) < n_test_desired:
        extra = rng.choice(resto_idx,
                           size=n_test_desired - len(test_idx),
                           replace=False)
        test_idx.extend(extra)
        resto_idx = [i for i in resto_idx if i not in extra]

    # define validação
    val_idx  = rng.choice(resto_idx, size=n_val_desired, replace=False)
    train_idx = [i for i in idx_all if i not in test_idx and i not in val_idx]

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [19]:
def std_split(dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42,
              bin_size: int = 5) -> DatasetDict:
    """
    Split 80-10-10 robusto.
      • Tenta estratificar por comprimento // bin_size.
      • Se houver classes com <2 amostras, recua p/ split aleatório.
    """
    idx  = np.arange(len(dataset))
    bins = (np.array([len(t) for t in dataset["tokens"]]) // bin_size)

    try:
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            stratify=bins,
            random_state=seed,
        )
    except ValueError:                       # classes muito pequenas
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # fraciona temp em val / test mantendo proporção desejada
    val_share = pct_val / (pct_test + pct_val)
    try:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            stratify=bins[temp_idx],
            random_state=seed,
        )
    except ValueError:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [20]:
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Versão robusta: nunca “trava” antes de atingir n_test.
    Seleciona blocos de k sentenças mais distantes do centro iterativamente.
    """
    # -------------------------------- embeds -------------------------------
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(t) for t in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    tree = BallTree(emb, leaf_size=40)

    n_test = int(pct_test * len(dataset))
    n_val  = int(pct_val  * len(dataset))

    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)

    print(f"Selecionando {n_test} sentenças para teste…")
    step = 0
    while len(test_idx) < n_test and idx_pool:
        if step % 5 == 0:
            print(f"  {len(test_idx)} selecionadas…")
        step += 1

        pool_list = list(idx_pool)
        center = emb[pool_list].mean(0, keepdims=True)

        # distância euclidiana ao centro global restante
        dists, _ = tree.query(center, k=len(pool_list))
        farthest_local_idx = int(dists.argmax())
        farthest_global_idx = pool_list[farthest_local_idx]

        # número efetivo de vizinhos
        k_eff = min(k, len(idx_pool))
        nn = set(tree.query([emb[farthest_global_idx]],
                            k=k_eff,
                            return_distance=False)[0])

        # adiciona vizinhos ainda não selecionados
        for j in nn:
            if j in idx_pool and len(test_idx) < n_test:
                test_idx.append(j)
                idx_pool.remove(j)

        # Se nada foi adicionado (pode acontecer quando sobram <k únicos)
        if farthest_global_idx not in test_idx:
            test_idx.append(farthest_global_idx)
            idx_pool.remove(farthest_global_idx)

    # ------------------------ validação e treino ---------------------------
    val_idx = rng.choice(list(idx_pool), size=n_val, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [21]:
standard_split = std_split(cachaca_full)
print('std')
# random_splt = random_splits(cachaca_full)
# print('random')
heur_len = heur_len_split(cachaca_full)
print("heur_len")
heur_rare = heur_rare_split(cachaca_full)
print("heur_rare")
advers = adversarial_split(cachaca_full)
print("advs")
loc = loc_split(cachaca_full)
print("loc")
semantic = semantic_cluster_split(cachaca_full)
print("semantic")
reverse = reverse_curriculum_split(cachaca_full)
print("reverse")

std
heur_len
heur_rare
Selecionando 2725 sentenças para teste…
  0 selecionadas…
  26 selecionadas…
  51 selecionadas…
  76 selecionadas…
  101 selecionadas…
  127 selecionadas…
  152 selecionadas…
  177 selecionadas…
  202 selecionadas…
  228 selecionadas…
  254 selecionadas…
  278 selecionadas…
  304 selecionadas…
  327 selecionadas…
  354 selecionadas…
  380 selecionadas…
  406 selecionadas…
  430 selecionadas…
  451 selecionadas…
  469 selecionadas…
  492 selecionadas…
  516 selecionadas…
  541 selecionadas…
  565 selecionadas…
  589 selecionadas…
  606 selecionadas…
  629 selecionadas…
  643 selecionadas…
  664 selecionadas…
  679 selecionadas…
  700 selecionadas…
  718 selecionadas…
  745 selecionadas…
  770 selecionadas…
  788 selecionadas…
  813 selecionadas…
  831 selecionadas…
  848 selecionadas…
  866 selecionadas…
  885 selecionadas…
  901 selecionadas…
  925 selecionadas…
  939 selecionadas…
  944 selecionadas…
  969 selecionadas…
  985 selecionadas…
  998 selecionadas…
  1022 selecionadas…
  1045 selecionadas…
  1060 selecionadas…
  1084 selecionadas…
  1099 selecionadas…
  1122 selecionadas…
  1144 selecionadas…
  1168 selecionadas…
  1192 selecionadas…
  1213 selecionadas…
  1229 selecionadas…
  1255 selecionadas…
  1282 selecionadas…
  1306 selecionadas…
  1326 selecionadas…
  1348 selecionadas…
  1372 selecionadas…
  1392 selecionadas…
  1403 selecionadas…
  1425 selecionadas…
  1451 selecionadas…
  1469 selecionadas…
  1484 selecionadas…
  1504 selecionadas…
  1524 selecionadas…
  1544 selecionadas…
  1569 selecionadas…
  1588 selecionadas…
  1603 selecionadas…
  1628 selecionadas…
  1652 selecionadas…
  1675 selecionadas…
  1693 selecionadas…
  1718 selecionadas…
  1738 selecionadas…
  1757 selecionadas…
  1779 selecionadas…
  1798 selecionadas…
  1822 selecionadas…
  1840 selecionadas…
  1865 selecionadas…
  1886 selecionadas…
  1905 selecionadas…
  1930 selecionadas…
  1946 selecionadas…
  1969 selecionadas…
  1995 selecionadas…
  2011 selecionadas…
  2030 selecionadas…
  2051 selecionadas…
  2073 selecionadas…
  2094 selecionadas…
  2113 selecionadas…
  2138 selecionadas…
  2155 selecionadas…
  2180 selecionadas…
  2204 selecionadas…
  2229 selecionadas…
  2254 selecionadas…
  2275 selecionadas…
  2293 selecionadas…
  2315 selecionadas…
  2333 selecionadas…
  2356 selecionadas…
  2382 selecionadas…
  2405 selecionadas…
  2418 selecionadas…
  2438 selecionadas…
  2458 selecionadas…
  2482 selecionadas…
  2502 selecionadas…
  2527 selecionadas…
  2546 selecionadas…
  2560 selecionadas…
  2586 selecionadas…
  2603 selecionadas…
  2625 selecionadas…
  2648 selecionadas…
  2669 selecionadas…
  2696 selecionadas…
  2719 selecionadas…
advs

C:\Users\user\AppData\Local\Temp\ipykernel_1300\4053031328.py:28: RuntimeWarning: invalid value encountered in divide
  topk[i] = (inter / uni).mean()

loc

100%|██████████| 13628/13628 [00:00<00:00, 1115012.00it/s]

semantic
reverse

# Experimentos

In [22]:



from sklearn.metrics import f1_score as skl_f1

In [23]:
def train_ner_with_split(
    dataset: Dataset,
    split: str,  # "loc" | "semantic" | "reverse" | func
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    model_ckpt: str = "Davlan/distilbert-base-multilingual-cased-ner-hrl",
    training_args_kwargs: dict | None = None,
    split_kwargs: dict | None = None,
    seed: int = 42,
):
    """
    Treina um modelo de NER usando a estratégia de split desejada.
    Retorna (trainer, métricas_test).
    """
    # 1. Escolhe função de split ------------------------------------------------
    if callable(split):
        split_fn = split
    else:
        _map = {
            "loc"      : loc_split,
            "reverse"  : reverse_curriculum_split,
            "semantic" : semantic_cluster_split,
            "heur_len" : heur_len_split,
            "heur_rare": heur_rare_split,
            "std"      : std_split,
            "advs"     : adversarial_split,
        }
        if split not in _map:
            raise ValueError(f"split='{split}' não reconhecido.")
        split_fn = _map[split]

    split_kwargs = split_kwargs or {}
    ds = split_fn(
        dataset, pct_test=pct_test, pct_val=pct_val, seed=seed, **split_kwargs
    )  # train/val/test

    # 2. Tokenizer e modelo -----------------------------------------------------
    label_list = sorted({l for labels in dataset["ner_tags"] for l in labels})
    label2id = {l: i for i, l in enumerate(label_list)}
    id2label = {i: l for l, i in label2id.items()}

    num_labels = len(label_list)
    tok = AutoTokenizer.from_pretrained(model_ckpt)
    model = AutoModelForTokenClassification.from_pretrained(
        model_ckpt,
        num_labels=num_labels,  # ← adapta o tamanho
        ignore_mismatched_sizes=True,  # ← descarta pesos velhos da head
    )
    model.config.id2label = id2label
    model.config.label2id = label2id

    # 3. Mapeamento label↔id ----------------------------------------------------
    # label_list = sorted(
    #     {l for labels in dataset["ner_tags"] for l in labels if l != "O"}
    # )

    # 4. Tokenização + alinhamento ---------------------------------------------
    # def tok_function(ex):
    #     return tok(
    #         ex["tokens"], is_split_into_words=True, truncation=True, padding=False
    #     )

    # def align_labels(ex):
    #     word_ids = ex.word_ids()
    #     labels = []
    #     for w in word_ids:
    #         if w is None:
    #             labels.append(-100)
    #         else:
    #             labels.append(label2id.get(ex["ner_tags"][w], 0))
    #     ex["labels"] = labels
    #     return ex

    # ds_tok = ds.map(tok_function, batched=True)
    # ds_tok = ds_tok.map(align_labels)

    def tokenize_and_align_labels(examples, label_all_tokens=False):
        tokenized = tok(examples["tokens"], is_split_into_words=True, truncation=True)

        labels_batch = []
        for i, word_labels in enumerate(examples["ner_tags"]):
            word_ids = tokenized.word_ids(batch_index=i)  # <- aqui sim
            label_ids = []
            previous_word_idx = None
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)  # máscara
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[word_labels[word_idx]])
                else:
                    # marca sub-tokens; mude para `label2id[...]`
                    # se quiser repetir label em todos os sub-tokens
                    label_ids.append(
                        label2id[word_labels[word_idx]] if label_all_tokens else -100
                    )
                previous_word_idx = word_idx
            labels_batch.append(label_ids)

        tokenized["labels"] = labels_batch
        return tokenized

    ds_tok = ds.map(
        tokenize_and_align_labels, batched=True, remove_columns=ds["train"].column_names
    )
    # 5. Métrica (seqeval) ------------------------------------------------------
    seqeval = load_metric("seqeval")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)

        sent_preds, sent_labels = [], []   # p/ seqeval
        flat_preds, flat_labels = [], []   # p/ sklearn

        for p_row, l_row in zip(preds, labels):
            p_sent, l_sent = [], []
            for pi, li in zip(p_row, l_row):
                if li != -100:
                    lbl_true = id2label[li]
                    lbl_pred = id2label[pi]
                    p_sent.append(lbl_pred)
                    l_sent.append(lbl_true)
                    flat_preds.append(lbl_pred)
                    flat_labels.append(lbl_true)
            sent_preds.append(p_sent)
            sent_labels.append(l_sent)

        # métricas seqeval (micro F1 = overall_f1)
        seqeval_metrics = seqeval.compute(
            predictions=sent_preds,
            references=sent_labels,
        )

        # métricas sklearn
        f1_micro    = skl_f1(flat_labels, flat_preds, average="micro",    zero_division=0)
        f1_macro    = skl_f1(flat_labels, flat_preds, average="macro",    zero_division=0)
        f1_weighted = skl_f1(flat_labels, flat_preds, average="weighted", zero_division=0)

        return {
            **seqeval_metrics,            # overall_precision / recall / f1
            "f1_micro":    f1_micro,
            "f1_macro":    f1_macro,
            "f1_weighted": f1_weighted,
        }



    # 6. Args de treinamento ----------------------------------------------------
    args_defaults = dict(
        output_dir=f"ner-{split}",
        # estratégia de avaliação + salvamento
        eval_strategy="epoch",  # novo nome (4.52+)
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="overall_f1",
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=5,
        seed=seed,
        report_to="none"
    )

    if training_args_kwargs:
        args_defaults.update(training_args_kwargs)
    args = TrainingArguments(**args_defaults)

    data_collator = DataCollatorForTokenClassification(tokenizer=tok, padding=True)

    # 7. Trainer ---------------------------------------------------------------
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tok["train"],
        eval_dataset=ds_tok["val"],
        tokenizer=tok,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    # 8. Avaliação final --------------------------------------------------------
    test_metrics = trainer.evaluate(eval_dataset=ds_tok["test"])
    return trainer, test_metrics

In [ ]:
splits = ["loc", "reverse", "semantic", "heur_len", "heur_rare", "std", "advs"]

In [ ]:
results = {}
trainer_all = {}
for s in splits:
    print(f"Treinando com split: {s}")
    trainer, metrics = train_ner_with_split(cachaca_full, split=s)
    results[s] = metrics
    trainer_all[s] = trainer
    print("F1 Macro:", metrics["eval_f1_macro"])
    print("F1 Micro:", metrics["eval_f1_micro"])
    print("F1 Weighted:", metrics["eval_f1_weighted"])
    print(metrics)
    print('\n')

Treinando com split: loc

C:\Users\user\AppData\Local\Temp\ipykernel_1300\4053031328.py:28: RuntimeWarning: invalid value encountered in divide
  topk[i] = (inter / uni).mean()
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9541/9541 [00:00<00:00, 13768.96 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 10214.53 examples/s]
Map: 100%|██████████| 2725/2725 [00:00<00:00, 12607.71 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.774947839171008
F1 Micro: 0.9581529306299948
F1 Weighted: 0.9564964185799768
{'eval_loss': 0.19240279495716095, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.6501128668171557, 'recall': 0.6206896551724138, 'f1': 0.6350606394707827, 'number': 464}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.8041237113402062, 'recall': 0.7155963302752294, 'f1': 0.7572815533980584, 'number': 109}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.8031914893617021, 'recall': 0.7626262626262627, 'f1': 0.7823834196891192, 'number': 198}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.5718157181571816, 'recall': 0.4668141592920354, 'f1': 0.5140073081607794, 'number': 452}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.8202247191011236, 'recall': 0.8830645161290323, 'f1': 0.850485436893204, 'number': 248}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.7575757575757576, 'recall': 0.7692307692307693, 'f1': 0.7633587786259541, 'number': 65}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.911504424778761, 'recall': 0.9537037037037037, 'f1': 0.9321266968325793, 'number': 108}, 'eval_NOME_BEBIDA': {'precision': 0.7550200803212851, 'recall': 0.7324675324675325, 'f1': 0.7435728411338166, 'number': 770}, 'eval_NOME_LOCAL': {'precision': 0.9278466741826381, 'recall': 0.9278466741826381, 'f1': 0.9278466741826381, 'number': 887}, 'eval_NOME_ORGANIZACAO': {'precision': 0.5060240963855421, 'recall': 0.6436781609195402, 'f1': 0.566610455311973, 'number': 261}, 'eval_NOME_PESSOA': {'precision': 0.8142292490118577, 'recall': 0.8408163265306122, 'f1': 0.8273092369477911, 'number': 245}, 'eval_PRECO': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 4}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.8836363636363637, 'recall': 0.8379310344827586, 'f1': 0.8601769911504424, 'number': 290}, 'eval_TEMPO': {'precision': 0.8311345646437994, 'recall': 0.8677685950413223, 'f1': 0.8490566037735849, 'number': 363}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.9311926605504587, 'recall': 0.9354838709677419, 'f1': 0.9333333333333333, 'number': 217}, 'eval_TIPO_MADEIRA': {'precision': 0.93026941362916, 'recall': 0.9591503267973857, 'f1': 0.9444891391794048, 'number': 612}, 'eval_VOLUME': {'precision': 0.9216589861751152, 'recall': 0.9852216748768473, 'f1': 0.9523809523809523, 'number': 203}, 'eval_overall_precision': 0.8042685151404597, 'eval_overall_recall': 0.8022197962154294, 'eval_overall_f1': 0.8032428493350338, 'eval_overall_accuracy': 0.9581529306299948, 'eval_f1_micro': 0.9581529306299948, 'eval_f1_macro': 0.774947839171008, 'eval_f1_weighted': 0.9564964185799768, 'eval_runtime': 99.3131, 'eval_samples_per_second': 27.438, 'eval_steps_per_second': 1.722, 'epoch': 5.0}


Treinando com split: reverse

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9541/9541 [00:01<00:00, 8398.28 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 11465.97 examples/s]
Map: 100%|██████████| 2725/2725 [00:00<00:00, 7680.43 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.636658318052605
F1 Micro: 0.9054167658022048
F1 Weighted: 0.8910118953601164
{'eval_loss': 0.6190888285636902, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.36065573770491804, 'recall': 0.10401891252955082, 'f1': 0.1614678899082569, 'number': 846}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.9203539823008849, 'recall': 0.42448979591836733, 'f1': 0.5810055865921788, 'number': 245}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.29261363636363635, 'recall': 0.23897911832946636, 'f1': 0.2630906768837803, 'number': 431}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.38746438746438744, 'recall': 0.44958677685950416, 'f1': 0.4162203519510329, 'number': 605}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.9180887372013652, 'recall': 0.5627615062761506, 'f1': 0.6977950713359273, 'number': 478}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.8088235294117647, 'recall': 0.4888888888888889, 'f1': 0.6094182825484764, 'number': 225}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.8875, 'recall': 0.8452380952380952, 'f1': 0.8658536585365854, 'number': 84}, 'eval_NOME_BEBIDA': {'precision': 0.667601683029453, 'recall': 0.805414551607445, 'f1': 0.7300613496932515, 'number': 591}, 'eval_NOME_LOCAL': {'precision': 0.8614035087719298, 'recall': 0.8621597892888498, 'f1': 0.8617814831066258, 'number': 1139}, 'eval_NOME_ORGANIZACAO': {'precision': 0.6417910447761194, 'recall': 0.6093117408906883, 'f1': 0.6251298026998962, 'number': 494}, 'eval_NOME_PESSOA': {'precision': 0.8383458646616542, 'recall': 0.802158273381295, 'f1': 0.8198529411764706, 'number': 556}, 'eval_PRECO': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 323}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.9284332688588007, 'recall': 0.8391608391608392, 'f1': 0.8815426997245179, 'number': 572}, 'eval_TEMPO': {'precision': 0.8547619047619047, 'recall': 0.8886138613861386, 'f1': 0.8713592233009709, 'number': 404}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.8094262295081968, 'recall': 0.8896396396396397, 'f1': 0.8476394849785407, 'number': 444}, 'eval_TIPO_MADEIRA': {'precision': 0.9028629856850716, 'recall': 0.9294736842105263, 'f1': 0.9159751037344399, 'number': 950}, 'eval_VOLUME': {'precision': 0.23842592592592593, 'recall': 0.9856459330143541, 'f1': 0.38397017707362535, 'number': 209}, 'eval_overall_precision': 0.6895908469095884, 'eval_overall_recall': 0.645067473243369, 'eval_overall_f1': 0.6665865240127428, 'eval_overall_accuracy': 0.9054167658022048, 'eval_f1_micro': 0.9054167658022048, 'eval_f1_macro': 0.636658318052605, 'eval_f1_weighted': 0.8910118953601164, 'eval_runtime': 138.0844, 'eval_samples_per_second': 19.734, 'eval_steps_per_second': 1.238, 'epoch': 5.0}


Treinando com split: semantic

100%|██████████| 13628/13628 [00:00<00:00, 1783629.51it/s]
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9448/9448 [00:01<00:00, 6962.17 examples/s]
Map: 100%|██████████| 1400/1400 [00:00<00:00, 11590.07 examples/s]
Map: 100%|██████████| 2780/2780 [00:00<00:00, 15448.78 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6963812336091685
F1 Micro: 0.7734393085886256
F1 Weighted: 0.6859838994546551
{'eval_loss': 1.9648122787475586, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 1.0, 'recall': 0.82, 'f1': 0.9010989010989011, 'number': 50}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.75, 'recall': 0.8709677419354839, 'f1': 0.8059701492537312, 'number': 31}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.9, 'recall': 0.5294117647058824, 'f1': 0.6666666666666667, 'number': 17}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.9746192893401016, 'recall': 0.9922480620155039, 'f1': 0.9833546734955186, 'number': 387}, 'eval_NOME_BEBIDA': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 12}, 'eval_NOME_LOCAL': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 244}, 'eval_PRECO': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 710}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 0}, 'eval_TEMPO': {'precision': 0.9705882352941176, 'recall': 1.0, 'f1': 0.9850746268656716, 'number': 66}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.9796954314720813, 'recall': 0.9747474747474747, 'f1': 0.9772151898734176, 'number': 198}, 'eval_TIPO_MADEIRA': {'precision': 0.9848484848484849, 'recall': 0.9848484848484849, 'f1': 0.9848484848484849, 'number': 66}, 'eval_VOLUME': {'precision': 0.9948078920041536, 'recall': 0.9560878243512974, 'f1': 0.9750636132315521, 'number': 1002}, 'eval_overall_precision': 0.9832759468765372, 'eval_overall_recall': 0.7182896155228171, 'eval_overall_f1': 0.8301495016611297, 'eval_overall_accuracy': 0.7734393085886256, 'eval_f1_micro': 0.7734393085886256, 'eval_f1_macro': 0.6963812336091685, 'eval_f1_weighted': 0.6859838994546551, 'eval_runtime': 39.7219, 'eval_samples_per_second': 69.987, 'eval_steps_per_second': 4.38, 'epoch': 5.0}


Treinando com split: heur_len

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9541/9541 [00:01<00:00, 6163.66 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 5303.96 examples/s]
Map: 100%|██████████| 2725/2725 [00:00<00:00, 7661.75 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

F1 Macro: 0.9288731175797169
F1 Micro: 0.9846575342465753
F1 Weighted: 0.9846079183444877
{'eval_loss': 0.06512857973575592, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.775609756097561, 'recall': 0.8112244897959183, 'f1': 0.7930174563591023, 'number': 196}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.8846153846153846, 'recall': 0.8846153846153846, 'f1': 0.8846153846153846, 'number': 52}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.9016393442622951, 'recall': 0.9243697478991597, 'f1': 0.9128630705394191, 'number': 119}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.7806451612903226, 'recall': 0.6914285714285714, 'f1': 0.7333333333333333, 'number': 175}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.9402985074626866, 'recall': 0.9618320610687023, 'f1': 0.9509433962264152, 'number': 262}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.9242424242424242, 'recall': 0.9384615384615385, 'f1': 0.9312977099236641, 'number': 65}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.981042654028436, 'recall': 0.9951923076923077, 'f1': 0.9880668257756563, 'number': 208}, 'eval_NOME_BEBIDA': {'precision': 0.8961832061068702, 'recall': 0.9258675078864353, 'f1': 0.9107835531419705, 'number': 634}, 'eval_NOME_LOCAL': {'precision': 0.9673659673659674, 'recall': 0.9718969555035128, 'f1': 0.969626168224299, 'number': 854}, 'eval_NOME_ORGANIZACAO': {'precision': 0.8762376237623762, 'recall': 0.8894472361809045, 'f1': 0.8827930174563591, 'number': 199}, 'eval_NOME_PESSOA': {'precision': 0.9590163934426229, 'recall': 0.936, 'f1': 0.9473684210526315, 'number': 125}, 'eval_PRECO': {'precision': 0.9411764705882353, 'recall': 0.9943502824858758, 'f1': 0.9670329670329672, 'number': 177}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.9414893617021277, 'recall': 0.9619565217391305, 'f1': 0.9516129032258065, 'number': 184}, 'eval_TEMPO': {'precision': 0.9840637450199203, 'recall': 0.9762845849802372, 'f1': 0.9801587301587301, 'number': 253}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.9773755656108597, 'recall': 1.0, 'f1': 0.9885583524027459, 'number': 216}, 'eval_TIPO_MADEIRA': {'precision': 0.9800796812749004, 'recall': 0.9800796812749004, 'f1': 0.9800796812749004, 'number': 502}, 'eval_VOLUME': {'precision': 0.9942965779467681, 'recall': 0.9757462686567164, 'f1': 0.984934086629002, 'number': 536}, 'eval_overall_precision': 0.9388436652055938, 'eval_overall_recall': 0.9455539205381543, 'eval_overall_f1': 0.942186845412652, 'eval_overall_accuracy': 0.9846575342465753, 'eval_f1_micro': 0.9846575342465753, 'eval_f1_macro': 0.9288731175797169, 'eval_f1_weighted': 0.9846079183444877, 'eval_runtime': 111.6371, 'eval_samples_per_second': 24.409, 'eval_steps_per_second': 1.532, 'epoch': 5.0}


Treinando com split: heur_rare

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 10537/10537 [00:01<00:00, 7973.85 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 7833.53 examples/s]
Map: 100%|██████████| 1729/1729 [00:00<00:00, 4724.81 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

F1 Macro: 0.8459949848355584
F1 Micro: 0.9664541668808802
F1 Weighted: 0.9664464998267429
{'eval_loss': 0.1467614620923996, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.7603686635944701, 'recall': 0.6962025316455697, 'f1': 0.7268722466960352, 'number': 237}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.7666666666666667, 'recall': 0.71875, 'f1': 0.7419354838709677, 'number': 64}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.8064516129032258, 'recall': 0.8064516129032258, 'f1': 0.8064516129032258, 'number': 93}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.6072874493927125, 'recall': 0.6607929515418502, 'f1': 0.6329113924050632, 'number': 227}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.8641304347826086, 'recall': 0.8983050847457628, 'f1': 0.8808864265927978, 'number': 177}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.7692307692307693, 'recall': 0.8928571428571429, 'f1': 0.8264462809917357, 'number': 56}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.8157894736842105, 'recall': 0.9117647058823529, 'f1': 0.861111111111111, 'number': 68}, 'eval_NOME_BEBIDA': {'precision': 0.7606837606837606, 'recall': 0.8333333333333334, 'f1': 0.7953529937444146, 'number': 534}, 'eval_NOME_LOCAL': {'precision': 0.8803278688524591, 'recall': 0.8994974874371859, 'f1': 0.8898094449047225, 'number': 597}, 'eval_NOME_ORGANIZACAO': {'precision': 0.6234309623430963, 'recall': 0.6898148148148148, 'f1': 0.6549450549450548, 'number': 216}, 'eval_NOME_PESSOA': {'precision': 0.8217821782178217, 'recall': 0.8512820512820513, 'f1': 0.836272040302267, 'number': 195}, 'eval_PRECO': {'precision': 0.96875, 'recall': 0.9587628865979382, 'f1': 0.9637305699481865, 'number': 97}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.9082969432314411, 'recall': 0.9244444444444444, 'f1': 0.9162995594713655, 'number': 225}, 'eval_TEMPO': {'precision': 0.8797653958944281, 'recall': 0.9202453987730062, 'f1': 0.8995502248875561, 'number': 326}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.9161676646706587, 'recall': 0.9216867469879518, 'f1': 0.9189189189189191, 'number': 166}, 'eval_TIPO_MADEIRA': {'precision': 0.9202898550724637, 'recall': 0.9621212121212122, 'f1': 0.9407407407407408, 'number': 396}, 'eval_VOLUME': {'precision': 0.8804347826086957, 'recall': 0.9473684210526315, 'f1': 0.9126760563380281, 'number': 171}, 'eval_overall_precision': 0.8233973559491145, 'eval_overall_recall': 0.85851755526658, 'eval_overall_f1': 0.8405907817672523, 'eval_overall_accuracy': 0.9664541668808802, 'eval_f1_micro': 0.9664541668808802, 'eval_f1_macro': 0.8459949848355584, 'eval_f1_weighted': 0.9664464998267429, 'eval_runtime': 65.6872, 'eval_samples_per_second': 26.322, 'eval_steps_per_second': 1.659, 'epoch': 5.0}


Treinando com split: std

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9539/9539 [00:00<00:00, 11239.11 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 13199.27 examples/s]
Map: 100%|██████████| 2727/2727 [00:00<00:00, 13274.59 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

F1 Macro: 0.9303260747729224
F1 Micro: 0.9855432755965088
F1 Weighted: 0.9856299073740179
{'eval_loss': 0.0611397922039032, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.7903225806451613, 'recall': 0.8546511627906976, 'f1': 0.8212290502793295, 'number': 172}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.926829268292683, 'recall': 0.8444444444444444, 'f1': 0.8837209302325582, 'number': 45}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.8416666666666667, 'recall': 0.8782608695652174, 'f1': 0.8595744680851064, 'number': 115}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.7672955974842768, 'recall': 0.7672955974842768, 'f1': 0.7672955974842768, 'number': 159}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.9383561643835616, 'recall': 0.9785714285714285, 'f1': 0.9580419580419579, 'number': 280}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.9090909090909091, 'recall': 0.9375, 'f1': 0.923076923076923, 'number': 64}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.9823008849557522, 'recall': 1.0, 'f1': 0.9910714285714286, 'number': 222}, 'eval_NOME_BEBIDA': {'precision': 0.9152276295133438, 'recall': 0.9479674796747968, 'f1': 0.9313099041533547, 'number': 615}, 'eval_NOME_LOCAL': {'precision': 0.9654403567447045, 'recall': 0.9632925472747497, 'f1': 0.9643652561247217, 'number': 899}, 'eval_NOME_ORGANIZACAO': {'precision': 0.8513513513513513, 'recall': 0.8915094339622641, 'f1': 0.870967741935484, 'number': 212}, 'eval_NOME_PESSOA': {'precision': 0.9290780141843972, 'recall': 0.8972602739726028, 'f1': 0.9128919860627179, 'number': 146}, 'eval_PRECO': {'precision': 0.953757225433526, 'recall': 0.9939759036144579, 'f1': 0.9734513274336285, 'number': 166}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.968421052631579, 'recall': 0.9533678756476683, 'f1': 0.9608355091383811, 'number': 193}, 'eval_TEMPO': {'precision': 0.9696969696969697, 'recall': 0.9664429530201343, 'f1': 0.9680672268907563, 'number': 298}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.9861111111111112, 'recall': 1.0, 'f1': 0.993006993006993, 'number': 213}, 'eval_TIPO_MADEIRA': {'precision': 0.970703125, 'recall': 0.970703125, 'f1': 0.970703125, 'number': 512}, 'eval_VOLUME': {'precision': 0.9941520467836257, 'recall': 0.9807692307692307, 'f1': 0.9874152952565344, 'number': 520}, 'eval_overall_precision': 0.9390343698854338, 'eval_overall_recall': 0.9501138480645829, 'eval_overall_f1': 0.9445416195081798, 'eval_overall_accuracy': 0.9855432755965088, 'eval_f1_micro': 0.9855432755965088, 'eval_f1_macro': 0.9303260747729224, 'eval_f1_weighted': 0.9856299073740179, 'eval_runtime': 85.0237, 'eval_samples_per_second': 32.073, 'eval_steps_per_second': 2.011, 'epoch': 5.0}


Treinando com split: advs
Selecionando 2725 sentenças para teste…
  0 selecionadas…
  26 selecionadas…
  51 selecionadas…
  76 selecionadas…
  101 selecionadas…
  127 selecionadas…
  152 selecionadas…
  177 selecionadas…
  202 selecionadas…
  228 selecionadas…
  254 selecionadas…
  278 selecionadas…
  304 selecionadas…
  327 selecionadas…
  354 selecionadas…
  380 selecionadas…
  406 selecionadas…
  430 selecionadas…
  451 selecionadas…
  469 selecionadas…
  492 selecionadas…
  516 selecionadas…
  541 selecionadas…
  565 selecionadas…
  589 selecionadas…
  606 selecionadas…
  629 selecionadas…
  643 selecionadas…
  664 selecionadas…
  679 selecionadas…
  700 selecionadas…
  718 selecionadas…
  745 selecionadas…
  770 selecionadas…
  788 selecionadas…
  813 selecionadas…
  831 selecionadas…
  848 selecionadas…
  866 selecionadas…
  885 selecionadas…
  901 selecionadas…
  925 selecionadas…
  939 selecionadas…
  944 selecionadas…
  969 selecionadas…
  985 selecionadas…
  998 selecionadas…
  1022 selecionadas…
  1045 selecionadas…
  1060 selecionadas…
  1084 selecionadas…
  1099 selecionadas…
  1122 selecionadas…
  1144 selecionadas…
  1168 selecionadas…
  1192 selecionadas…
  1213 selecionadas…
  1229 selecionadas…
  1255 selecionadas…
  1282 selecionadas…
  1306 selecionadas…
  1326 selecionadas…
  1348 selecionadas…
  1372 selecionadas…
  1392 selecionadas…
  1403 selecionadas…
  1425 selecionadas…
  1451 selecionadas…
  1469 selecionadas…
  1484 selecionadas…
  1504 selecionadas…
  1524 selecionadas…
  1544 selecionadas…
  1569 selecionadas…
  1588 selecionadas…
  1603 selecionadas…
  1628 selecionadas…
  1652 selecionadas…
  1675 selecionadas…
  1693 selecionadas…
  1718 selecionadas…
  1738 selecionadas…
  1757 selecionadas…
  1779 selecionadas…
  1798 selecionadas…
  1822 selecionadas…
  1840 selecionadas…
  1865 selecionadas…
  1886 selecionadas…
  1905 selecionadas…
  1930 selecionadas…
  1946 selecionadas…
  1969 selecionadas…
  1995 selecionadas…
  2011 selecionadas…
  2030 selecionadas…
  2051 selecionadas…
  2073 selecionadas…
  2094 selecionadas…
  2113 selecionadas…
  2138 selecionadas…
  2155 selecionadas…
  2180 selecionadas…
  2204 selecionadas…
  2229 selecionadas…
  2254 selecionadas…
  2275 selecionadas…
  2293 selecionadas…
  2315 selecionadas…
  2333 selecionadas…
  2356 selecionadas…
  2382 selecionadas…
  2405 selecionadas…
  2418 selecionadas…
  2438 selecionadas…
  2458 selecionadas…
  2482 selecionadas…
  2502 selecionadas…
  2527 selecionadas…
  2546 selecionadas…
  2560 selecionadas…
  2586 selecionadas…
  2603 selecionadas…
  2625 selecionadas…
  2648 selecionadas…
  2669 selecionadas…
  2696 selecionadas…
  2719 selecionadas…

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([35]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([35, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 9540/9540 [00:01<00:00, 9221.45 examples/s]
Map: 100%|██████████| 1362/1362 [00:00<00:00, 9671.15 examples/s]
Map: 100%|██████████| 2726/2726 [00:00<00:00, 10038.42 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_1300\2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

F1 Macro: 0.8729360209592214
F1 Micro: 0.9750559376812795
F1 Weighted: 0.9748498292036873
{'eval_loss': 0.10891634225845337, 'eval_CARACTERISTICA_SENSORIAL_AROMA': {'precision': 0.8208333333333333, 'recall': 0.8277310924369747, 'f1': 0.8242677824267782, 'number': 238}, 'eval_CARACTERISTICA_SENSORIAL_CONSISTÊNCIA': {'precision': 0.8727272727272727, 'recall': 0.8275862068965517, 'f1': 0.8495575221238938, 'number': 58}, 'eval_CARACTERISTICA_SENSORIAL_COR': {'precision': 0.8548387096774194, 'recall': 0.8346456692913385, 'f1': 0.844621513944223, 'number': 127}, 'eval_CARACTERISTICA_SENSORIAL_SABOR': {'precision': 0.7528735632183908, 'recall': 0.7401129943502824, 'f1': 0.7464387464387464, 'number': 177}, 'eval_CLASSIFICACAO_BEBIDA': {'precision': 0.8602150537634409, 'recall': 0.975609756097561, 'f1': 0.9142857142857143, 'number': 246}, 'eval_EQUIPAMENTO_DESTILACAO': {'precision': 0.8611111111111112, 'recall': 0.96875, 'f1': 0.911764705882353, 'number': 64}, 'eval_GRADUACAO_ALCOOLICA': {'precision': 0.963963963963964, 'recall': 0.9907407407407407, 'f1': 0.9771689497716894, 'number': 216}, 'eval_NOME_BEBIDA': {'precision': 0.7762237762237763, 'recall': 0.8525345622119815, 'f1': 0.8125915080527086, 'number': 651}, 'eval_NOME_LOCAL': {'precision': 0.9616685456595265, 'recall': 0.9638418079096045, 'f1': 0.9627539503386005, 'number': 885}, 'eval_NOME_ORGANIZACAO': {'precision': 0.7907949790794979, 'recall': 0.7907949790794979, 'f1': 0.7907949790794979, 'number': 239}, 'eval_NOME_PESSOA': {'precision': 0.8258064516129032, 'recall': 0.8590604026845637, 'f1': 0.8421052631578947, 'number': 149}, 'eval_PRECO': {'precision': 0.9052631578947369, 'recall': 0.9942196531791907, 'f1': 0.9476584022038568, 'number': 173}, 'eval_RECIPIENTE_ARMAZENAMENTO': {'precision': 0.933649289099526, 'recall': 0.9609756097560975, 'f1': 0.9471153846153846, 'number': 205}, 'eval_TEMPO': {'precision': 0.9594594594594594, 'recall': 0.9627118644067797, 'f1': 0.961082910321489, 'number': 295}, 'eval_TEMPO_ARMAZENAMENTO': {'precision': 0.920863309352518, 'recall': 0.9808429118773946, 'f1': 0.9499072356215214, 'number': 261}, 'eval_TIPO_MADEIRA': {'precision': 0.9508506616257089, 'recall': 0.9562737642585551, 'f1': 0.9535545023696683, 'number': 526}, 'eval_VOLUME': {'precision': 0.9798206278026906, 'recall': 0.9520697167755992, 'f1': 0.9657458563535912, 'number': 459}, 'eval_overall_precision': 0.8943661971830986, 'eval_overall_recall': 0.9201046488227007, 'eval_overall_f1': 0.9070528717389148, 'eval_overall_accuracy': 0.9750559376812795, 'eval_f1_micro': 0.9750559376812795, 'eval_f1_macro': 0.8729360209592214, 'eval_f1_weighted': 0.9748498292036873, 'eval_runtime': 39.8816, 'eval_samples_per_second': 68.352, 'eval_steps_per_second': 4.288, 'epoch': 5.0}