In [1]:
from pathlib import Path
from typing import List, Tuple, Dict
import json, random, itertools, os, gc, statistics as st
import seqeval

import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import KFold, train_test_split
from collections import Counter
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import BallTree
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from sklearn.cluster import KMeans

import torch
from transformers import (
    AutoTokenizer,
        AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)

from seqeval.metrics import f1_score, classification_report
from evaluate import load as load_metric
from tqdm.auto import tqdm

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Configuração e Verificação Inicial

In [2]:
SEED_GLOBAL = 42
random.seed(SEED_GLOBAL)
np.random.seed(SEED_GLOBAL)
torch.manual_seed(SEED_GLOBAL)

JSON_PATH = "data/geocorpus-v2.json"  
MODEL_NAME = "modelicaai/albertina-base"

with open(JSON_PATH, encoding="utf-8") as f:
    raw = json.load(f)

In [3]:
records_geo = [
    {
        "sentence_id": i,
        "tokens"     : item["tokens"],
        "ner_tags"   : item["ner_tokens"],
    }
    for i, item in enumerate(raw)
]

geocorpus_full = Dataset.from_list(records_geo)

In [4]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({l for sent in geocorpus_full["ner_tags"] for l in sent})
label2id   = {l: i for i, l in enumerate(label_list)}
id2label   = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [5]:
id2label

{0: 'B-ambienteSedimentacao',
 1: 'B-baciaSedimentar',
 2: 'B-bentonico',
 3: 'B-campoPetrolifero',
 4: 'B-constituinteRochaSedimentar',
 5: 'B-contextoGeologicoDeBacia',
 6: 'B-elementoQuimico',
 7: 'B-eon',
 8: 'B-epoca',
 9: 'B-era',
 10: 'B-estratigrafia',
 11: 'B-estruturaGeologica',
 12: 'B-estruturaSedimentar',
 13: 'B-fosseis',
 14: 'B-geomorfologia',
 15: 'B-granulometria',
 16: 'B-idade',
 17: 'B-magmaticas',
 18: 'B-metamorficas',
 19: 'B-mineral',
 20: 'B-periodo',
 21: 'B-planctonico',
 22: 'B-procedimentoMetodologico',
 23: 'B-sedimentaresCarbonaticas',
 24: 'B-sedimentaresOrganicas',
 25: 'B-sedimentaresQuimicas',
 26: 'B-sedimentaresSiliciclasticas',
 27: 'B-sistemaPetrolifero',
 28: 'B-unidadeEstratigrafica',
 29: 'B-unidadeGeotectonica',
 30: 'I-ambienteSedimentacao',
 31: 'I-baciaSedimentar',
 32: 'I-bentonico',
 33: 'I-campoPetrolifero',
 34: 'I-constituinteRochaSedimentar',
 35: 'I-contextoGeologicoDeBacia',
 36: 'I-epoca',
 37: 'I-era',
 38: 'I-estratigrafia',
 39: 'I-estruturaGeologica',
 40: 'I-estruturaSedimentar',
 41: 'I-fosseis',
 42: 'I-granulometria',
 43: 'I-idade',
 44: 'I-magmaticas',
 45: 'I-metamorficas',
 46: 'I-mineral',
 47: 'I-periodo',
 48: 'I-planctonico',
 49: 'I-procedimentoMetodologico',
 50: 'I-sedimentaresCarbonaticas',
 51: 'I-sedimentaresQuimicas',
 52: 'I-sedimentaresSiliciclasticas',
 53: 'I-sistemaPetrolifero',
 54: 'I-unidadeEstratigrafica',
 55: 'I-unidadeGeotectonica',
 56: 'O'}

In [6]:
NUM_LABELS

57

# Splits

In [7]:
def split_standard(ds: Dataset) -> DatasetDict:
    """Usa coluna trainingTest do CSV (80/20 original)."""
    if "trainingTest" not in df.columns:
        raise ValueError("CSV não contém a coluna 'trainingTest'")
    train_ids = df.loc[df["trainingTest"] == "training", SENT_COL].unique()
    test_ids = df.loc[df["trainingTest"] == "test", SENT_COL].unique()
    return DatasetDict(
        train=ds.filter(lambda ex: ex["sentence_id"] in train_ids),
        dev=ds.filter(lambda ex: ex["sentence_id"] in test_ids),
    )

In [8]:
def random_splits(
    ds: Dataset, test_size=0.2, seeds: List[int] = range(30)
) -> List[DatasetDict]:
    triples = []
    for s in seeds:
        train, dev = ds.train_test_split(test_size=test_size, seed=s).values()
        triples.append(DatasetDict(train=train, dev=dev))
    return triples

In [9]:
# def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
#     lengths = np.array([len(t) for t in ds["tokens"]])
#     thr = np.percentile(lengths, 100 * (1 - top_pct))
#     mask = lengths >= thr
#     return DatasetDict(train=ds.filter(~mask), dev=ds.filter(mask))


def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
    """20 % das sentenças mais longas viram conjunto de validação (dev)."""
    lengths = np.array([len(t) for t in ds["tokens"]])
    thr = np.percentile(lengths, 100 * (1 - top_pct))  
    mask = lengths >= thr  

    dev_idx = np.where(mask)[0].tolist()  # índices → list[int]
    train_idx = np.where(~mask)[0].tolist()

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Tamanho da sentenças


# def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
#     freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
#     rare = {w for w, c in freq.items() if c <= freq_thr}

#     def has_rare(example):
#         return any(w.lower() in rare for w in example["tokens"])

#     return DatasetDict(
#         train=ds.filter(lambda ex: not has_rare(ex)), dev=ds.filter(has_rare)
#     )


def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
    freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
    rare = {w for w, c in freq.items() if c <= freq_thr}

    keep_dev = []
    for sent in ds["tokens"]:
        print(sent)
        keep_dev.append(any(w.lower() in rare for w in sent))

    dev_idx = [i for i, x in enumerate(keep_dev) if x]
    train_idx = [i for i, x in enumerate(keep_dev) if not x]

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Raridade dos tokens

In [10]:
def split_adversarial(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    embeds = model.encode([" ".join(t) for t in ds["tokens"]], show_progress_bar=False)
    tree = BallTree(embeds, leaf_size=40)

    idx_train, idx_test = set(range(len(ds))), []
    # semente = ponto mais central
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    idx_train.remove(seed_idx)
    idx_test.append(seed_idx)
    print(k)
    while len(idx_test) < k:
        print(len(idx_test))
        dists, _ = tree.query(embeds[list(idx_train)], k=1, return_distance=True)
        nxt = list(idx_train)[int(np.argmax(dists))]
        idx_train.remove(nxt)
        idx_test.append(nxt)

    return DatasetDict(
        train=ds.select(sorted(idx_train)),
        dev=ds.select(sorted(idx_test)),
    )

    # Maximizando Wassertein Distance


def split_adversarial_fast(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    """
    Farthest-Point Sampling aproximando Wasserstein – versão vetorizada.
    Seleciona pct_test (~20 %) das sentenças como conjunto 'dev'.
    """
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    embeds = model.encode(
        [" ".join(t) for t in ds["tokens"]],
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,  # acelera distância euclidiana ≈ cos
    )

    n = embeds.shape[0]
    idx_all = np.arange(n)

    # 1) ponto mais "central" (norma mais distante da média)
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    selected = [seed_idx]

    # 2) vetor de distâncias mínimas a qualquer ponto já escolhido
    min_dists = np.linalg.norm(embeds - embeds[seed_idx], axis=1)

    while len(selected) < k:
        next_idx = np.argmax(min_dists)
        selected.append(next_idx)

        # atualiza min_dists com a distância ao novo ponto — tudo de uma vez
        d_new = np.linalg.norm(embeds - embeds[next_idx], axis=1)
        min_dists = np.minimum(min_dists, d_new)

    train_idx = np.setdiff1d(idx_all, selected, assume_unique=True)

    return DatasetDict(
        train=ds.select(train_idx.tolist()),
        dev=ds.select(selected),
    )

In [11]:
# def loc_split(
#     dataset: Dataset, pct_test: float = 0.20, ngram: int = 4, seed: int = 42
# ) -> DatasetDict:
#     """
#     Split baseado em baixa sobreposição léxica (4-gram Jaccard).
#     Teste = pct_test das sentenças com menor overlap em relação ao pool.
#     """
#     # 1. Texto plano por sentença
#     docs = [" ".join(toks) for toks in dataset["tokens"]]

#     # 2. Vetorizar 4-grams (binário)
#     vect = CountVectorizer(
#         analyzer="word", ngram_range=(ngram, ngram), binary=True
#     ).fit(docs)
#     X = vect.transform(docs)

#     # 3. Similaridade Jaccard aproximada com matriz binária
#     # Jaccard(A,B) = |A∩B|/|A∪B| = 1 - |AΔB|/|A∪B|
#     # Usamos: overlap = (A·Bᵀ) / (|A|+|B|-A·Bᵀ)
#     bin_counts = X.sum(axis=1).A1

#     # Para cada doc i, escolhemos vizinho + próximo (fast):
#     from sklearn.metrics.pairwise import cosine_similarity

#     # (cosine no binário ∝ |A∩B|)
#     sim = cosine_similarity(X, dense_output=False)
#     # Soma dos top-k overlaps (k=5) como score
#     k = 5
#     topk = np.zeros(len(dataset))
#     for i in range(sim.shape[0]):
#         row = sim.getrow(i).toarray()[0]
#         idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
#         # overlap ≈ |∩|
#         inter = row[idx] * bin_counts[i]
#         uni = bin_counts[i] + bin_counts[idx] - inter
#         topk[i] = (inter / uni).mean()

#     # 4. Ordenar por overlap crescente ⇒ mais “novos” vão p/ teste
#     order = np.argsort(topk)
#     n_test = int(len(dataset) * pct_test)
#     test_idx = order[:n_test]
#     train_idx = order[n_test:]

#     return DatasetDict(
#         {"train": dataset.select(train_idx), "test": dataset.select(test_idx)}
#     )

In [12]:
def loc_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    ngram: int = 4,
    seed: int = 42,
) -> DatasetDict:
    """
    Divide por sobreposição léxica (n-gram Jaccard).
    Frações independentes para teste e validação.
    """
    docs = [" ".join(toks) for toks in dataset["tokens"]]

    vect = CountVectorizer(
        analyzer="word", ngram_range=(ngram, ngram), binary=True
    ).fit(docs)
    X = vect.transform(docs)
    bin_counts = X.sum(axis=1).A1

    sim = cosine_similarity(X, dense_output=False)
    k = 5
    topk = np.zeros(len(dataset))
    for i in range(sim.shape[0]):
        row = sim.getrow(i).toarray()[0]
        idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
        inter = row[idx] * bin_counts[i]
        uni = bin_counts[i] + bin_counts[idx] - inter
        topk[i] = (inter / uni).mean()

    order = np.argsort(topk)  # baixo → alto overlap
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[:n_test]
    val_idx = order[n_test : n_test + n_val]
    train_idx = order[n_test + n_val :]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [13]:
def semantic_cluster_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    k: int | None = None,
    seed: int = 42,
) -> DatasetDict:
    """
    Clusters SBERT → reserva clusters distantes para test/val.
    """
    if k is None:
        k = int(np.sqrt(len(dataset)))

    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    embeddings = sbert.encode(
        [" ".join(t) for t in tqdm(dataset["tokens"])],
        batch_size=64,
        show_progress_bar=False,
    )

    km = KMeans(n_clusters=k, random_state=seed, n_init=10).fit(embeddings)
    labels = km.labels_
    centroids = km.cluster_centers_

    global_center = embeddings.mean(0, keepdims=True)
    dists = pairwise_distances(centroids, global_center).flatten()

    clusters_sorted = np.argsort(-dists)  # mais distantes primeiro
    test_clusters, val_clusters = set(), set()
    total_test = total_val = 0
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    for c in clusters_sorted:
        size = np.sum(labels == c)
        if total_test < n_test:  # preenche primeiro o teste
            test_clusters.add(c)
            total_test += size
        elif total_val < n_val:  # depois a validação
            val_clusters.add(c)
            total_val += size
        if total_test >= n_test and total_val >= n_val:
            break

    test_idx = np.where([lbl in test_clusters for lbl in labels])[0]
    val_idx = np.where([lbl in val_clusters for lbl in labels])[0]
    train_idx = np.where(
        [lbl not in test_clusters and lbl not in val_clusters for lbl in labels]
    )[0]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [14]:
def difficulty_scores(dataset: Dataset) -> np.ndarray:
    length = np.array([len(tok) for tok in dataset["tokens"]], dtype=float)
    length = (length - length.mean()) / length.std()

    dens = []
    for labels in dataset["ner_tags"]:
        non_o = sum(1 for l in labels if l != "O")
        dens.append(non_o / len(labels))
    dens = np.array(dens)
    dens = (dens - dens.mean()) / dens.std()

    ent_types, freq = [], Counter()
    for labels in dataset["ner_tags"]:
        types = [l[2:] for l in labels if l != "O"]
        ent_types.append(types[0] if types else "NONE")
    freq.update(ent_types)
    rarity = np.array([1 / freq[t] for t in ent_types])
    rarity = (rarity - rarity.mean()) / rarity.std()

    return length + dens + rarity


def reverse_curriculum_split(
    dataset: Dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
) -> DatasetDict:
    scores = difficulty_scores(dataset)
    order = np.argsort(scores)  # easy→hard
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[-n_test:]  # hardest
    val_idx = order[-(n_test + n_val) : -n_test]
    train_idx = order[: -(n_test + n_val)]

    rng = np.random.RandomState(seed)
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    rng.shuffle(test_idx)

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [15]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42) -> DatasetDict:
    """Testa só sentenças ≥ máx(len_train)."""
    sent_lens = np.array([len(t) for t in dataset["tokens"]])
    # separação inicial train/dev (randômica estratificando por tamanho grosso)
    idx_all   = np.arange(len(dataset))
    train_idx, temp_idx = train_test_split(idx_all,
                                           test_size=pct_test + pct_val,
                                           stratify=(sent_lens//5),  # bin len
                                           random_state=seed)
    # define longo-threshold como tamanho máx. do treino
    max_train_len = sent_lens[train_idx].max()
    # test = sentenças > threshold.  Caso falte/ sobre exemplos, ajusta.
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]
    # completa ou reduz para atingir pct_test
    need = int(pct_test*len(dataset)) - len(test_idx)
    if need > 0:
        test_idx.extend(resto_idx[:need])
        val_idx = resto_idx[need:]
    else:
        val_keep = int(pct_val*len(dataset))
        val_idx  = resto_idx[:val_keep]
        test_idx = test_idx[: int(pct_test*len(dataset))]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 2) Heuristic Rare-Words ----------------------------------
def heur_rare_split(dataset: Dataset,
                    pct_test: float = 0.20,
                    pct_val : float = 0.10,
                    seed: int = 42) -> DatasetDict:
    """Testa frases que contenham palavras do quintil + raro."""
    # contagem de frequência de token
    freqs = Counter(w for toks in dataset["tokens"] for w in toks)
    # define rareza: 20 % mais raras
    thresh = np.quantile(list(freqs.values()), 0.20)
    rare_set = {w for w,c in freqs.items() if c <= thresh}
    is_rare = np.array([any(w in rare_set for w in toks)
                        for toks in dataset["tokens"]])
    rare_idx   = np.where(is_rare)[0]
    common_idx = np.where(~is_rare)[0]
    # garante proporções desejadas
    n_test = int(pct_test*len(dataset))
    n_val  = int(pct_val *len(dataset))
    rng = np.random.default_rng(seed)
    test_idx = rng.choice(rare_idx, size=min(len(rare_idx), n_test),
                          replace=False)
    resto_idx = [i for i in rare_idx if i not in test_idx] + list(common_idx)
    val_idx  = rng.choice(resto_idx, size=n_val, replace=False)
    train_idx = [i for i in resto_idx if i not in val_idx]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 3) Standard (80-10-10) -----------------------------------
def std_split(dataset: Dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42) -> DatasetDict:
    """Split aleatório estratificado por comprimento (PTB-like)."""
    idx = np.arange(len(dataset))
    strat = (np.array([len(t) for t in dataset["tokens"]]) // 5)
    train_idx, temp_idx = train_test_split(idx, test_size=pct_test+pct_val,
                                          stratify=strat, random_state=seed)
    val_rel = pct_val / (pct_test+pct_val)
    val_idx, test_idx = train_test_split(temp_idx, test_size=1-val_rel,
                                         stratify=strat[temp_idx],
                                         random_state=seed)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 4) Adversarial (approx. Wasserstein) ---------------------
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Seleciona k frases 'mais distantes' recursivamente (BallTree + W₂)
    para compor o teste, lembrando Alg.-1 de Søgaard et al.【turn6file4】.
    """
    # SBERT embed (rápido na GPU / aceitável CPU)
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(toks) for toks in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    # BallTree para vizinhança eficiente
    tree = BallTree(emb, leaf_size=40)
    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)
    print(f"Selecionando {int(pct_test*len(dataset))} sentenças para teste...")
    while len(test_idx) < int(pct_test*len(dataset)):
        print(f"  {len(test_idx)} selecionadas...")
        # amostra candidata: ponto + longe do centro
        center = emb[list(idx_pool)].mean(0, keepdims=True)
        dists, _ = tree.query(center, k=len(idx_pool))
        farthest = list(idx_pool)[int(dists.argmax())]
        # pega-se farest e seus k-NN mais próximos  ⇒ aumenta diversidade
        nn = tree.query([emb[farthest]], k=k, return_distance=False)[0]
        for j in nn:
            if j in idx_pool and len(test_idx) < int(pct_test*len(dataset)):
                test_idx.append(j)
                idx_pool.remove(j)
    # retira val
    val_size = int(pct_val*len(dataset))
    val_idx  = rng.choice(list(idx_pool), size=val_size, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [16]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42,
                   bin_size: int = 10) -> DatasetDict:
    """
    Teste = sentenças mais longas que max(len(train)).
    Robusto a datasets pequenos: se estratificação falhar, usa split aleatório.
    """
    rng = np.random.default_rng(seed)
    idx_all   = np.arange(len(dataset))
    sent_lens = np.array([len(t) for t in dataset["tokens"]])

    # ------ 1) tenta split estratificado por baldes -------------------------
    strat = (sent_lens // bin_size)
    try:
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            stratify=strat,
            random_state=seed,
        )
    except ValueError:                       # classes com 1 amostra
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # ------ 2) escolhe test = len > max(train) ------------------------------
    max_train_len = sent_lens[train_idx].max()
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]

    # garante tamanhos exatos
    n_test_desired = int(pct_test * len(dataset))
    n_val_desired  = int(pct_val  * len(dataset))

    # completa teste se ficou pequeno
    if len(test_idx) < n_test_desired:
        extra = rng.choice(resto_idx,
                           size=n_test_desired - len(test_idx),
                           replace=False)
        test_idx.extend(extra)
        resto_idx = [i for i in resto_idx if i not in extra]

    # define validação
    val_idx  = rng.choice(resto_idx, size=n_val_desired, replace=False)
    train_idx = [i for i in idx_all if i not in test_idx and i not in val_idx]

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [17]:
def std_split(dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42,
              bin_size: int = 5) -> DatasetDict:
    """
    Split 80-10-10 robusto.
      • Tenta estratificar por comprimento // bin_size.
      • Se houver classes com <2 amostras, recua p/ split aleatório.
    """
    idx  = np.arange(len(dataset))
    bins = (np.array([len(t) for t in dataset["tokens"]]) // bin_size)

    try:
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            stratify=bins,
            random_state=seed,
        )
    except ValueError:                       # classes muito pequenas
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # fraciona temp em val / test mantendo proporção desejada
    val_share = pct_val / (pct_test + pct_val)
    try:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            stratify=bins[temp_idx],
            random_state=seed,
        )
    except ValueError:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [18]:
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Versão robusta: nunca “trava” antes de atingir n_test.
    Seleciona blocos de k sentenças mais distantes do centro iterativamente.
    """
    # -------------------------------- embeds -------------------------------
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(t) for t in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    tree = BallTree(emb, leaf_size=40)

    n_test = int(pct_test * len(dataset))
    n_val  = int(pct_val  * len(dataset))

    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)

    print(f"Selecionando {n_test} sentenças para teste…")
    step = 0
    while len(test_idx) < n_test and idx_pool:
        if step % 5 == 0:
            print(f"  {len(test_idx)} selecionadas…")
        step += 1

        pool_list = list(idx_pool)
        center = emb[pool_list].mean(0, keepdims=True)

        # distância euclidiana ao centro global restante
        dists, _ = tree.query(center, k=len(pool_list))
        farthest_local_idx = int(dists.argmax())
        farthest_global_idx = pool_list[farthest_local_idx]

        # número efetivo de vizinhos
        k_eff = min(k, len(idx_pool))
        nn = set(tree.query([emb[farthest_global_idx]],
                            k=k_eff,
                            return_distance=False)[0])

        # adiciona vizinhos ainda não selecionados
        for j in nn:
            if j in idx_pool and len(test_idx) < n_test:
                test_idx.append(j)
                idx_pool.remove(j)

        # Se nada foi adicionado (pode acontecer quando sobram <k únicos)
        if farthest_global_idx not in test_idx:
            test_idx.append(farthest_global_idx)
            idx_pool.remove(farthest_global_idx)

    # ------------------------ validação e treino ---------------------------
    val_idx = rng.choice(list(idx_pool), size=n_val, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [19]:
# standard_split = std_split(geocorpus_full)
print('std')
# random_splt = random_splits(geocorpus_full)
# print('random')
heur_len = heur_len_split(geocorpus_full)
print("heur_len")
heur_rare = heur_rare_split(geocorpus_full)
print("heur_rare")
advers = adversarial_split(geocorpus_full)
print("advs")
# loc = loc_split(geocorpus_full)
# print("loc")
semantic = semantic_cluster_split(geocorpus_full)
print("semantic")
reverse = reverse_curriculum_split(geocorpus_full)
print("reverse")

std
heur_len
heur_rare
Selecionando 1054 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  47 selecionadas…
  71 selecionadas…
  96 selecionadas…
  121 selecionadas…
  144 selecionadas…
  165 selecionadas…
  187 selecionadas…
  211 selecionadas…
  232 selecionadas…
  251 selecionadas…
  271 selecionadas…
  288 selecionadas…
  305 selecionadas…
  329 selecionadas…
  349 selecionadas…
  364 selecionadas…
  383 selecionadas…
  399 selecionadas…
  417 selecionadas…
  433 selecionadas…
  452 selecionadas…
  470 selecionadas…
  488 selecionadas…
  501 selecionadas…
  515 selecionadas…
  529 selecionadas…
  542 selecionadas…
  554 selecionadas…
  565 selecionadas…
  577 selecionadas…
  590 selecionadas…
  597 selecionadas…
  610 selecionadas…
  628 selecionadas…
  642 selecionadas…
  658 selecionadas…
  671 selecionadas…
  685 selecionadas…
  698 selecionadas…
  713 selecionadas…
  724 selecionadas…
  738 selecionadas…
  754 selecionadas…
  771 selecionadas…
  785 selecionadas…
  798 selecionadas…
  817 selecionadas…
  830 selecionadas…
  844 selecionadas…
  856 selecionadas…
  868 selecionadas…
  884 selecionadas…
  894 selecionadas…
  901 selecionadas…
  916 selecionadas…
  936 selecionadas…
  951 selecionadas…
  963 selecionadas…
  976 selecionadas…
  986 selecionadas…
  998 selecionadas…
  1015 selecionadas…
  1032 selecionadas…
  1047 selecionadas…
advs

100%|██████████| 5272/5272 [00:00<00:00, 1360510.10it/s]

semantic
reverse

# Experimentos

In [20]:
from sklearn.metrics import f1_score as skl_f1

In [21]:
def train_ner_with_split(
    dataset: Dataset,
    split: str,  # "loc" | "semantic" | "reverse" | func
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    model_ckpt: str = "Davlan/distilbert-base-multilingual-cased-ner-hrl",
    training_args_kwargs: dict | None = None,
    split_kwargs: dict | None = None,
    seed: int = 42,
):
    """
    Treina um modelo de NER usando a estratégia de split desejada.
    Retorna (trainer, métricas_test).
    """
    # 1. Escolhe função de split ------------------------------------------------
    if callable(split):
        split_fn = split
    else:
        _map = {
            "loc"      : loc_split,
            "reverse"  : reverse_curriculum_split,
            "semantic" : semantic_cluster_split,
            "heur_len" : heur_len_split,
            "heur_rare": heur_rare_split,
            "std"      : std_split,
            "advs"     : adversarial_split,
        }
        if split not in _map:
            raise ValueError(f"split='{split}' não reconhecido.")
        split_fn = _map[split]

    split_kwargs = split_kwargs or {}
    ds = split_fn(
        dataset, pct_test=pct_test, pct_val=pct_val, seed=seed, **split_kwargs
    )  # train/val/test

    # 2. Tokenizer e modelo -----------------------------------------------------
    label_list = sorted({l for labels in dataset["ner_tags"] for l in labels})
    label2id = {l: i for i, l in enumerate(label_list)}
    id2label = {i: l for l, i in label2id.items()}

    num_labels = len(label_list)
    tok = AutoTokenizer.from_pretrained(model_ckpt)
    model = AutoModelForTokenClassification.from_pretrained(
        model_ckpt,
        num_labels=num_labels,  # ← adapta o tamanho
        ignore_mismatched_sizes=True,  # ← descarta pesos velhos da head
    )
    model.config.id2label = id2label
    model.config.label2id = label2id

    # 3. Mapeamento label↔id ----------------------------------------------------
    # label_list = sorted(
    #     {l for labels in dataset["ner_tags"] for l in labels if l != "O"}
    # )

    # 4. Tokenização + alinhamento ---------------------------------------------
    # def tok_function(ex):
    #     return tok(
    #         ex["tokens"], is_split_into_words=True, truncation=True, padding=False
    #     )

    # def align_labels(ex):
    #     word_ids = ex.word_ids()
    #     labels = []
    #     for w in word_ids:
    #         if w is None:
    #             labels.append(-100)
    #         else:
    #             labels.append(label2id.get(ex["ner_tags"][w], 0))
    #     ex["labels"] = labels
    #     return ex

    # ds_tok = ds.map(tok_function, batched=True)
    # ds_tok = ds_tok.map(align_labels)

    def tokenize_and_align_labels(examples, label_all_tokens=False):
        tokenized = tok(examples["tokens"], is_split_into_words=True, truncation=True)

        labels_batch = []
        for i, word_labels in enumerate(examples["ner_tags"]):
            word_ids = tokenized.word_ids(batch_index=i)  # <- aqui sim
            label_ids = []
            previous_word_idx = None
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)  # máscara
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[word_labels[word_idx]])
                else:
                    # marca sub-tokens; mude para `label2id[...]`
                    # se quiser repetir label em todos os sub-tokens
                    label_ids.append(
                        label2id[word_labels[word_idx]] if label_all_tokens else -100
                    )
                previous_word_idx = word_idx
            labels_batch.append(label_ids)

        tokenized["labels"] = labels_batch
        return tokenized

    ds_tok = ds.map(
        tokenize_and_align_labels, batched=True, remove_columns=ds["train"].column_names
    )
    # 5. Métrica (seqeval) ------------------------------------------------------
    seqeval = load_metric("seqeval")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)

        sent_preds, sent_labels = [], []   # p/ seqeval
        flat_preds, flat_labels = [], []   # p/ sklearn

        for p_row, l_row in zip(preds, labels):
            p_sent, l_sent = [], []
            for pi, li in zip(p_row, l_row):
                if li != -100:
                    lbl_true = id2label[li]
                    lbl_pred = id2label[pi]
                    p_sent.append(lbl_pred)
                    l_sent.append(lbl_true)
                    flat_preds.append(lbl_pred)
                    flat_labels.append(lbl_true)
            sent_preds.append(p_sent)
            sent_labels.append(l_sent)

        # métricas seqeval (micro F1 = overall_f1)
        seqeval_metrics = seqeval.compute(
            predictions=sent_preds,
            references=sent_labels,
        )

        # métricas sklearn
        f1_micro    = skl_f1(flat_labels, flat_preds, average="micro",    zero_division=0)
        f1_macro    = skl_f1(flat_labels, flat_preds, average="macro",    zero_division=0)
        f1_weighted = skl_f1(flat_labels, flat_preds, average="weighted", zero_division=0)

        return {
            **seqeval_metrics,            # overall_precision / recall / f1
            "f1_micro":    f1_micro,
            "f1_macro":    f1_macro,
            "f1_weighted": f1_weighted,
        }



    # 6. Args de treinamento ----------------------------------------------------
    args_defaults = dict(
        output_dir=f"ner-{split}",
        # estratégia de avaliação + salvamento
        eval_strategy="epoch",  # novo nome (4.52+)
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="overall_f1",
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=5,
        seed=seed,
        report_to="none"
    )

    if training_args_kwargs:
        args_defaults.update(training_args_kwargs)
    args = TrainingArguments(**args_defaults)

    data_collator = DataCollatorForTokenClassification(tokenizer=tok, padding=True)

    # 7. Trainer ---------------------------------------------------------------
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tok["train"],
        eval_dataset=ds_tok["val"],
        tokenizer=tok,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    # 8. Avaliação final --------------------------------------------------------
    test_metrics = trainer.evaluate(eval_dataset=ds_tok["test"])
    return trainer, test_metrics

In [22]:
splits = ["loc", "reverse", "semantic", "heur_len", "heur_rare", "advs"]

In [23]:
results = {}
trainer_all = {}
s = splits[0]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: loc

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3691/3691 [00:00<00:00, 9049.25 examples/s]
Map: 100%|██████████| 527/527 [00:00<00:00, 10931.58 examples/s]
Map: 100%|██████████| 1054/1054 [00:00<00:00, 11407.18 examples/s]
/tmp/ipykernel_144877/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6587085052451003
F1 Micro: 0.9887927208166889
F1 Weighted: 0.9884786309189074
{'eval_loss': 0.05377170071005821, 'eval_ambienteSedimentacao': {'precision': 0.6, 'recall': 0.5, 'f1': 0.5454545454545454, 'number': 6}, 'eval_baciaSedimentar': {'precision': 0.7543859649122807, 'recall': 0.8269230769230769, 'f1': 0.7889908256880734, 'number': 52}, 'eval_bentonico': {'precision': 0.6666666666666666, 'recall': 0.36363636363636365, 'f1': 0.4705882352941177, 'number': 11}, 'eval_campoPetrolifero': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 3}, 'eval_constituinteRochaSedimentar': {'precision': 0.75, 'recall': 1.0, 'f1': 0.8571428571428571, 'number': 3}, 'eval_contextoGeologicoDeBacia': {'precision': 0.8131868131868132, 'recall': 0.74, 'f1': 0.774869109947644, 'number': 100}, 'eval_elementoQuimico': {'precision': 1.0, 'recall': 0.7142857142857143, 'f1': 0.8333333333333333, 'number': 7}, 'eval_eon': {'precision': 0.9032258064516129, 'recall': 0.9655172413793104, 'f1': 0.9333333333333333, 'number': 29}, 'eval_epoca': {'precision': 0.967741935483871, 'recall': 0.975609756097561, 'f1': 0.97165991902834, 'number': 123}, 'eval_era': {'precision': 0.9104477611940298, 'recall': 0.9682539682539683, 'f1': 0.9384615384615386, 'number': 63}, 'eval_estratigrafia': {'precision': 0.95, 'recall': 0.95, 'f1': 0.9500000000000001, 'number': 20}, 'eval_estruturaGeologica': {'precision': 0.3333333333333333, 'recall': 0.3333333333333333, 'f1': 0.3333333333333333, 'number': 3}, 'eval_estruturaSedimentar': {'precision': 0.6666666666666666, 'recall': 1.0, 'f1': 0.8, 'number': 2}, 'eval_fosseis': {'precision': 0.375, 'recall': 0.75, 'f1': 0.5, 'number': 4}, 'eval_geomorfologia': {'precision': 1.0, 'recall': 0.7272727272727273, 'f1': 0.8421052631578948, 'number': 11}, 'eval_granulometria': {'precision': 0.84, 'recall': 0.84, 'f1': 0.8399999999999999, 'number': 25}, 'eval_idade': {'precision': 0.8830409356725146, 'recall': 0.9741935483870968, 'f1': 0.9263803680981595, 'number': 155}, 'eval_magmaticas': {'precision': 0.8571428571428571, 'recall': 0.9523809523809523, 'f1': 0.9022556390977443, 'number': 126}, 'eval_metamorficas': {'precision': 0.8351648351648352, 'recall': 0.8636363636363636, 'f1': 0.8491620111731844, 'number': 88}, 'eval_mineral': {'precision': 0.9642857142857143, 'recall': 1.0, 'f1': 0.9818181818181818, 'number': 27}, 'eval_periodo': {'precision': 0.9285714285714286, 'recall': 0.883495145631068, 'f1': 0.9054726368159205, 'number': 103}, 'eval_planctonico': {'precision': 0.65625, 'recall': 0.9130434782608695, 'f1': 0.7636363636363634, 'number': 23}, 'eval_procedimentoMetodologico': {'precision': 0.9375, 'recall': 0.967741935483871, 'f1': 0.9523809523809523, 'number': 31}, 'eval_sedimentaresCarbonaticas': {'precision': 0.7692307692307693, 'recall': 0.8333333333333334, 'f1': 0.8, 'number': 36}, 'eval_sedimentaresOrganicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1}, 'eval_sedimentaresQuimicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.8362068965517241, 'recall': 0.8660714285714286, 'f1': 0.8508771929824562, 'number': 112}, 'eval_sistemaPetrolifero': {'precision': 0.7333333333333333, 'recall': 0.88, 'f1': 0.8, 'number': 25}, 'eval_unidadeEstratigrafica': {'precision': 0.6724137931034483, 'recall': 0.7222222222222222, 'f1': 0.6964285714285714, 'number': 54}, 'eval_unidadeGeotectonica': {'precision': 0.6666666666666666, 'recall': 0.6666666666666666, 'f1': 0.6666666666666666, 'number': 3}, 'eval_overall_precision': 0.8501930501930502, 'eval_overall_recall': 0.8822115384615384, 'eval_overall_f1': 0.8659064097522612, 'eval_overall_accuracy': 0.9887927208166889, 'eval_f1_micro': 0.9887927208166889, 'eval_f1_macro': 0.6587085052451003, 'eval_f1_weighted': 0.9884786309189074, 'eval_runtime': 6.4028, 'eval_samples_per_second': 164.615, 'eval_steps_per_second': 10.308, 'epoch': 5.0}

340

In [24]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [25]:
results = {}
trainer_all = {}
s = splits[1]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: reverse

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3691/3691 [00:00<00:00, 11732.55 examples/s]
Map: 100%|██████████| 527/527 [00:00<00:00, 7833.18 examples/s]
Map: 100%|██████████| 1054/1054 [00:00<00:00, 6728.66 examples/s]
/tmp/ipykernel_144877/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.3899700393069398
F1 Micro: 0.9428287050860954
F1 Weighted: 0.9292042647934189
{'eval_loss': 0.4567084014415741, 'eval_ambienteSedimentacao': {'precision': 1.0, 'recall': 0.008928571428571428, 'f1': 0.017699115044247787, 'number': 112}, 'eval_baciaSedimentar': {'precision': 0.7262357414448669, 'recall': 0.6221498371335505, 'f1': 0.6701754385964912, 'number': 307}, 'eval_bentonico': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 27}, 'eval_campoPetrolifero': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 5}, 'eval_constituinteRochaSedimentar': {'precision': 0.96, 'recall': 0.42857142857142855, 'f1': 0.5925925925925924, 'number': 56}, 'eval_contextoGeologicoDeBacia': {'precision': 0.5542521994134897, 'recall': 0.5869565217391305, 'f1': 0.5701357466063349, 'number': 322}, 'eval_elementoQuimico': {'precision': 1.0, 'recall': 0.058823529411764705, 'f1': 0.1111111111111111, 'number': 17}, 'eval_eon': {'precision': 0.881578947368421, 'recall': 0.8589743589743589, 'f1': 0.8701298701298701, 'number': 78}, 'eval_epoca': {'precision': 0.9069767441860465, 'recall': 0.8705357142857143, 'f1': 0.8883826879271071, 'number': 224}, 'eval_era': {'precision': 0.8467153284671532, 'recall': 0.943089430894309, 'f1': 0.8923076923076922, 'number': 123}, 'eval_estratigrafia': {'precision': 0.7244897959183674, 'recall': 0.6283185840707964, 'f1': 0.6729857819905214, 'number': 113}, 'eval_estruturaGeologica': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 70}, 'eval_estruturaSedimentar': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 74}, 'eval_fosseis': {'precision': 0.8125, 'recall': 0.2708333333333333, 'f1': 0.40625, 'number': 96}, 'eval_geomorfologia': {'precision': 1.0, 'recall': 0.8076923076923077, 'f1': 0.8936170212765957, 'number': 26}, 'eval_granulometria': {'precision': 0.8305084745762712, 'recall': 0.5697674418604651, 'f1': 0.6758620689655173, 'number': 86}, 'eval_idade': {'precision': 0.8805970149253731, 'recall': 0.9247648902821317, 'f1': 0.9021406727828746, 'number': 319}, 'eval_magmaticas': {'precision': 0.9175824175824175, 'recall': 0.6761133603238867, 'f1': 0.7785547785547787, 'number': 247}, 'eval_metamorficas': {'precision': 0.8091603053435115, 'recall': 0.6022727272727273, 'f1': 0.6905537459283387, 'number': 176}, 'eval_mineral': {'precision': 0.8928571428571429, 'recall': 0.75, 'f1': 0.8152173913043479, 'number': 100}, 'eval_periodo': {'precision': 0.8762376237623762, 'recall': 0.855072463768116, 'f1': 0.8655256723716381, 'number': 207}, 'eval_planctonico': {'precision': 0.7659574468085106, 'recall': 0.7346938775510204, 'f1': 0.7499999999999999, 'number': 49}, 'eval_procedimentoMetodologico': {'precision': 0.9821428571428571, 'recall': 0.9016393442622951, 'f1': 0.9401709401709402, 'number': 61}, 'eval_sedimentaresCarbonaticas': {'precision': 0.5351351351351351, 'recall': 0.5469613259668509, 'f1': 0.5409836065573771, 'number': 181}, 'eval_sedimentaresOrganicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 18}, 'eval_sedimentaresQuimicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 11}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.7198697068403909, 'recall': 0.7607573149741824, 'f1': 0.7397489539748954, 'number': 581}, 'eval_sistemaPetrolifero': {'precision': 0.8055555555555556, 'recall': 0.8285714285714286, 'f1': 0.8169014084507044, 'number': 35}, 'eval_unidadeEstratigrafica': {'precision': 0.8323863636363636, 'recall': 0.5446096654275093, 'f1': 0.6584269662921349, 'number': 538}, 'eval_unidadeGeotectonica': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 25}, 'eval_overall_precision': 0.7801316919553393, 'eval_overall_recall': 0.6360877684407096, 'eval_overall_f1': 0.7007843641507008, 'eval_overall_accuracy': 0.9428287050860954, 'eval_f1_micro': 0.9428287050860954, 'eval_f1_macro': 0.3899700393069398, 'eval_f1_weighted': 0.9292042647934189, 'eval_runtime': 12.9563, 'eval_samples_per_second': 81.35, 'eval_steps_per_second': 5.094, 'epoch': 5.0}

0

In [26]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [27]:
results = {}
trainer_all = {}
s = splits[2]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: semantic

100%|██████████| 5272/5272 [00:00<00:00, 1341525.86it/s]
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3614/3614 [00:00<00:00, 9585.91 examples/s]
Map: 100%|██████████| 577/577 [00:00<00:00, 10467.26 examples/s]
Map: 100%|██████████| 1081/1081 [00:00<00:00, 11132.52 examples/s]
/tmp/ipykernel_144877/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6668808184213878
F1 Micro: 0.9898943349023996
F1 Weighted: 0.9897224714981325
{'eval_loss': 0.04663388803601265, 'eval_ambienteSedimentacao': {'precision': 0.6666666666666666, 'recall': 0.5, 'f1': 0.5714285714285715, 'number': 4}, 'eval_baciaSedimentar': {'precision': 0.926829268292683, 'recall': 1.0, 'f1': 0.9620253164556963, 'number': 38}, 'eval_bentonico': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_campoPetrolifero': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 1}, 'eval_constituinteRochaSedimentar': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1}, 'eval_contextoGeologicoDeBacia': {'precision': 0.5135135135135135, 'recall': 0.9047619047619048, 'f1': 0.6551724137931034, 'number': 21}, 'eval_elementoQuimico': {'precision': 0.6666666666666666, 'recall': 1.0, 'f1': 0.8, 'number': 2}, 'eval_eon': {'precision': 0.9562043795620438, 'recall': 0.9776119402985075, 'f1': 0.966789667896679, 'number': 134}, 'eval_epoca': {'precision': 0.8679245283018868, 'recall': 0.92, 'f1': 0.8932038834951457, 'number': 100}, 'eval_era': {'precision': 0.91875, 'recall': 0.8497109826589595, 'f1': 0.8828828828828829, 'number': 173}, 'eval_estratigrafia': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 10}, 'eval_estruturaGeologica': {'precision': 0.7692307692307693, 'recall': 0.6666666666666666, 'f1': 0.7142857142857142, 'number': 15}, 'eval_estruturaSedimentar': {'precision': 0.75, 'recall': 1.0, 'f1': 0.8571428571428571, 'number': 3}, 'eval_fosseis': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_geomorfologia': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 9}, 'eval_granulometria': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 2}, 'eval_idade': {'precision': 0.780952380952381, 'recall': 0.9647058823529412, 'f1': 0.8631578947368421, 'number': 85}, 'eval_magmaticas': {'precision': 0.7913669064748201, 'recall': 0.8870967741935484, 'f1': 0.8365019011406843, 'number': 124}, 'eval_metamorficas': {'precision': 0.7424242424242424, 'recall': 0.7538461538461538, 'f1': 0.7480916030534351, 'number': 65}, 'eval_mineral': {'precision': 0.6022727272727273, 'recall': 1.0, 'f1': 0.75177304964539, 'number': 53}, 'eval_periodo': {'precision': 0.926923076923077, 'recall': 0.9678714859437751, 'f1': 0.9469548133595286, 'number': 249}, 'eval_planctonico': {'precision': 0.6666666666666666, 'recall': 1.0, 'f1': 0.8, 'number': 4}, 'eval_procedimentoMetodologico': {'precision': 0.926829268292683, 'recall': 1.0, 'f1': 0.9620253164556963, 'number': 38}, 'eval_sedimentaresCarbonaticas': {'precision': 0.8888888888888888, 'recall': 1.0, 'f1': 0.9411764705882353, 'number': 16}, 'eval_sedimentaresOrganicas': {'precision': 0.8, 'recall': 1.0, 'f1': 0.888888888888889, 'number': 4}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.6909090909090909, 'recall': 0.8636363636363636, 'f1': 0.7676767676767676, 'number': 44}, 'eval_sistemaPetrolifero': {'precision': 0.8787878787878788, 'recall': 0.9354838709677419, 'f1': 0.90625, 'number': 62}, 'eval_unidadeEstratigrafica': {'precision': 0.8076923076923077, 'recall': 0.6, 'f1': 0.6885245901639345, 'number': 35}, 'eval_unidadeGeotectonica': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1}, 'eval_overall_precision': 0.8404558404558404, 'eval_overall_recall': 0.9097918272937549, 'eval_overall_f1': 0.8737504627915587, 'eval_overall_accuracy': 0.9898943349023996, 'eval_f1_micro': 0.9898943349023996, 'eval_f1_macro': 0.6668808184213878, 'eval_f1_weighted': 0.9897224714981325, 'eval_runtime': 6.8187, 'eval_samples_per_second': 158.533, 'eval_steps_per_second': 9.973, 'epoch': 5.0}

0

In [28]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [29]:
results = {}
trainer_all = {}
s = splits[3]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_len

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3691/3691 [00:00<00:00, 10139.86 examples/s]
Map: 100%|██████████| 527/527 [00:00<00:00, 9810.61 examples/s]
Map: 100%|██████████| 1054/1054 [00:00<00:00, 9412.04 examples/s]
/tmp/ipykernel_144877/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6796626114892569
F1 Micro: 0.985896976216087
F1 Weighted: 0.9856486616592398
{'eval_loss': 0.0655684620141983, 'eval_ambienteSedimentacao': {'precision': 0.7368421052631579, 'recall': 0.717948717948718, 'f1': 0.7272727272727273, 'number': 39}, 'eval_baciaSedimentar': {'precision': 0.8380952380952381, 'recall': 0.8380952380952381, 'f1': 0.8380952380952381, 'number': 105}, 'eval_bentonico': {'precision': 1.0, 'recall': 0.6666666666666666, 'f1': 0.8, 'number': 3}, 'eval_campoPetrolifero': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_constituinteRochaSedimentar': {'precision': 0.8636363636363636, 'recall': 0.8636363636363636, 'f1': 0.8636363636363636, 'number': 22}, 'eval_contextoGeologicoDeBacia': {'precision': 0.7549668874172185, 'recall': 0.8444444444444444, 'f1': 0.7972027972027972, 'number': 135}, 'eval_elementoQuimico': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 1}, 'eval_eon': {'precision': 0.9818181818181818, 'recall': 0.9642857142857143, 'f1': 0.972972972972973, 'number': 56}, 'eval_epoca': {'precision': 0.9030303030303031, 'recall': 0.9802631578947368, 'f1': 0.9400630914826498, 'number': 152}, 'eval_era': {'precision': 0.9397590361445783, 'recall': 0.9873417721518988, 'f1': 0.962962962962963, 'number': 79}, 'eval_estratigrafia': {'precision': 0.8723404255319149, 'recall': 0.9111111111111111, 'f1': 0.891304347826087, 'number': 45}, 'eval_estruturaGeologica': {'precision': 0.8, 'recall': 0.5714285714285714, 'f1': 0.6666666666666666, 'number': 14}, 'eval_estruturaSedimentar': {'precision': 0.631578947368421, 'recall': 0.75, 'f1': 0.6857142857142857, 'number': 16}, 'eval_fosseis': {'precision': 0.5806451612903226, 'recall': 0.6428571428571429, 'f1': 0.6101694915254238, 'number': 28}, 'eval_geomorfologia': {'precision': 0.75, 'recall': 1.0, 'f1': 0.8571428571428571, 'number': 6}, 'eval_granulometria': {'precision': 0.7419354838709677, 'recall': 0.7666666666666667, 'f1': 0.7540983606557377, 'number': 30}, 'eval_idade': {'precision': 0.8858695652173914, 'recall': 0.9878787878787879, 'f1': 0.9340974212034384, 'number': 165}, 'eval_magmaticas': {'precision': 0.8620689655172413, 'recall': 0.9259259259259259, 'f1': 0.8928571428571429, 'number': 108}, 'eval_metamorficas': {'precision': 0.8, 'recall': 0.8095238095238095, 'f1': 0.8047337278106509, 'number': 84}, 'eval_mineral': {'precision': 0.8979591836734694, 'recall': 0.9565217391304348, 'f1': 0.9263157894736843, 'number': 46}, 'eval_periodo': {'precision': 0.8646616541353384, 'recall': 0.9504132231404959, 'f1': 0.9055118110236221, 'number': 121}, 'eval_planctonico': {'precision': 0.8571428571428571, 'recall': 0.972972972972973, 'f1': 0.9113924050632912, 'number': 37}, 'eval_procedimentoMetodologico': {'precision': 0.9393939393939394, 'recall': 0.96875, 'f1': 0.9538461538461539, 'number': 32}, 'eval_sedimentaresCarbonaticas': {'precision': 0.8115942028985508, 'recall': 0.8235294117647058, 'f1': 0.8175182481751825, 'number': 68}, 'eval_sedimentaresOrganicas': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 3}, 'eval_sedimentaresQuimicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.8378378378378378, 'recall': 0.8815165876777251, 'f1': 0.859122401847575, 'number': 211}, 'eval_sistemaPetrolifero': {'precision': 0.8918918918918919, 'recall': 0.9428571428571428, 'f1': 0.9166666666666667, 'number': 35}, 'eval_unidadeEstratigrafica': {'precision': 0.81875, 'recall': 0.8733333333333333, 'f1': 0.8451612903225806, 'number': 150}, 'eval_unidadeGeotectonica': {'precision': 0.25, 'recall': 0.16666666666666666, 'f1': 0.2, 'number': 6}, 'eval_overall_precision': 0.8440944881889764, 'eval_overall_recall': 0.8933333333333333, 'eval_overall_f1': 0.8680161943319838, 'eval_overall_accuracy': 0.985896976216087, 'eval_f1_micro': 0.985896976216087, 'eval_f1_macro': 0.6796626114892569, 'eval_f1_weighted': 0.9856486616592398, 'eval_runtime': 8.5271, 'eval_samples_per_second': 123.605, 'eval_steps_per_second': 7.74, 'epoch': 5.0}

320

In [30]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [31]:
results = {}
trainer_all = {}
s = splits[4]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_rare

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3691/3691 [00:00<00:00, 10058.79 examples/s]
Map: 100%|██████████| 527/527 [00:00<00:00, 9235.20 examples/s]
Map: 100%|██████████| 1054/1054 [00:00<00:00, 9022.68 examples/s]
/tmp/ipykernel_144877/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6523659634606951
F1 Micro: 0.9844875196274839
F1 Weighted: 0.9843165729452448
{'eval_loss': 0.07353035360574722, 'eval_ambienteSedimentacao': {'precision': 0.6451612903225806, 'recall': 0.6451612903225806, 'f1': 0.6451612903225806, 'number': 31}, 'eval_baciaSedimentar': {'precision': 0.828125, 'recall': 0.8983050847457628, 'f1': 0.8617886178861789, 'number': 118}, 'eval_bentonico': {'precision': 0.5, 'recall': 0.5, 'f1': 0.5, 'number': 2}, 'eval_campoPetrolifero': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1}, 'eval_constituinteRochaSedimentar': {'precision': 0.8125, 'recall': 0.7222222222222222, 'f1': 0.7647058823529411, 'number': 36}, 'eval_contextoGeologicoDeBacia': {'precision': 0.6492146596858639, 'recall': 0.8104575163398693, 'f1': 0.7209302325581396, 'number': 153}, 'eval_elementoQuimico': {'precision': 0.8888888888888888, 'recall': 0.8888888888888888, 'f1': 0.8888888888888888, 'number': 9}, 'eval_eon': {'precision': 0.8809523809523809, 'recall': 0.8809523809523809, 'f1': 0.8809523809523809, 'number': 42}, 'eval_epoca': {'precision': 0.9078947368421053, 'recall': 0.9787234042553191, 'f1': 0.9419795221843004, 'number': 141}, 'eval_era': {'precision': 0.9135802469135802, 'recall': 0.9866666666666667, 'f1': 0.9487179487179487, 'number': 75}, 'eval_estratigrafia': {'precision': 0.7307692307692307, 'recall': 0.8085106382978723, 'f1': 0.7676767676767676, 'number': 47}, 'eval_estruturaGeologica': {'precision': 0.38095238095238093, 'recall': 0.5714285714285714, 'f1': 0.4571428571428571, 'number': 14}, 'eval_estruturaSedimentar': {'precision': 0.75, 'recall': 0.6923076923076923, 'f1': 0.7199999999999999, 'number': 26}, 'eval_fosseis': {'precision': 0.7894736842105263, 'recall': 0.6, 'f1': 0.6818181818181819, 'number': 25}, 'eval_geomorfologia': {'precision': 1.0, 'recall': 0.6666666666666666, 'f1': 0.8, 'number': 12}, 'eval_granulometria': {'precision': 0.8518518518518519, 'recall': 0.92, 'f1': 0.8846153846153846, 'number': 25}, 'eval_idade': {'precision': 0.92, 'recall': 0.9757575757575757, 'f1': 0.9470588235294117, 'number': 165}, 'eval_magmaticas': {'precision': 0.8947368421052632, 'recall': 0.9379310344827586, 'f1': 0.9158249158249158, 'number': 145}, 'eval_metamorficas': {'precision': 0.7323943661971831, 'recall': 0.9454545454545454, 'f1': 0.8253968253968254, 'number': 55}, 'eval_mineral': {'precision': 0.8163265306122449, 'recall': 0.975609756097561, 'f1': 0.888888888888889, 'number': 41}, 'eval_periodo': {'precision': 0.8620689655172413, 'recall': 0.946969696969697, 'f1': 0.9025270758122743, 'number': 132}, 'eval_planctonico': {'precision': 0.7666666666666667, 'recall': 1.0, 'f1': 0.8679245283018869, 'number': 23}, 'eval_procedimentoMetodologico': {'precision': 0.9736842105263158, 'recall': 0.8809523809523809, 'f1': 0.925, 'number': 42}, 'eval_sedimentaresCarbonaticas': {'precision': 0.7333333333333333, 'recall': 0.7971014492753623, 'f1': 0.7638888888888887, 'number': 69}, 'eval_sedimentaresOrganicas': {'precision': 0.75, 'recall': 1.0, 'f1': 0.8571428571428571, 'number': 3}, 'eval_sedimentaresQuimicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.7991803278688525, 'recall': 0.8783783783783784, 'f1': 0.8369098712446353, 'number': 222}, 'eval_sistemaPetrolifero': {'precision': 0.9285714285714286, 'recall': 0.9629629629629629, 'f1': 0.9454545454545454, 'number': 27}, 'eval_unidadeEstratigrafica': {'precision': 0.7976190476190477, 'recall': 0.9241379310344827, 'f1': 0.8562300319488818, 'number': 145}, 'eval_unidadeGeotectonica': {'precision': 0.3333333333333333, 'recall': 0.14285714285714285, 'f1': 0.2, 'number': 7}, 'eval_overall_precision': 0.815592203898051, 'eval_overall_recall': 0.8893732970027248, 'eval_overall_f1': 0.8508863399374348, 'eval_overall_accuracy': 0.9844875196274839, 'eval_f1_micro': 0.9844875196274839, 'eval_f1_macro': 0.6523659634606951, 'eval_f1_weighted': 0.9843165729452448, 'eval_runtime': 9.6178, 'eval_samples_per_second': 109.588, 'eval_steps_per_second': 6.862, 'epoch': 5.0}

320

In [25]:
del results, trainer_all#, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

NameError: name 'results' is not defined

In [23]:
results = {}
trainer_all = {}
s = splits[5]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(geocorpus_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: advs
Selecionando 1054 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  47 selecionadas…
  71 selecionadas…
  96 selecionadas…
  121 selecionadas…
  144 selecionadas…
  165 selecionadas…
  187 selecionadas…
  211 selecionadas…
  232 selecionadas…
  251 selecionadas…
  271 selecionadas…
  288 selecionadas…
  305 selecionadas…
  329 selecionadas…
  349 selecionadas…
  364 selecionadas…
  383 selecionadas…
  399 selecionadas…
  417 selecionadas…
  433 selecionadas…
  452 selecionadas…
  470 selecionadas…
  488 selecionadas…
  501 selecionadas…
  515 selecionadas…
  529 selecionadas…
  542 selecionadas…
  554 selecionadas…
  565 selecionadas…
  577 selecionadas…
  590 selecionadas…
  597 selecionadas…
  610 selecionadas…
  628 selecionadas…
  642 selecionadas…
  658 selecionadas…
  671 selecionadas…
  685 selecionadas…
  698 selecionadas…
  713 selecionadas…
  724 selecionadas…
  738 selecionadas…
  754 selecionadas…
  771 selecionadas…
  785 selecionadas…
  798 selecionadas…
  817 selecionadas…
  830 selecionadas…
  844 selecionadas…
  856 selecionadas…
  868 selecionadas…
  884 selecionadas…
  894 selecionadas…
  901 selecionadas…
  916 selecionadas…
  936 selecionadas…
  951 selecionadas…
  963 selecionadas…
  976 selecionadas…
  986 selecionadas…
  998 selecionadas…
  1015 selecionadas…
  1032 selecionadas…
  1047 selecionadas…

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([57]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([57, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 3691/3691 [00:00<00:00, 9018.85 examples/s]
Map: 100%|██████████| 527/527 [00:00<00:00, 9575.12 examples/s]
Map: 100%|██████████| 1054/1054 [00:00<00:00, 8299.64 examples/s]
/tmp/ipykernel_163479/2810120630.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.6020732383933304
F1 Micro: 0.9723849372384937
F1 Weighted: 0.9686079379785297
{'eval_loss': 0.15635041892528534, 'eval_ambienteSedimentacao': {'precision': 0.30120481927710846, 'recall': 0.27472527472527475, 'f1': 0.28735632183908044, 'number': 91}, 'eval_baciaSedimentar': {'precision': 0.8033707865168539, 'recall': 0.8218390804597702, 'f1': 0.8125, 'number': 174}, 'eval_bentonico': {'precision': 0.4, 'recall': 0.3333333333333333, 'f1': 0.3636363636363636, 'number': 6}, 'eval_constituinteRochaSedimentar': {'precision': 0.9047619047619048, 'recall': 0.4470588235294118, 'f1': 0.5984251968503936, 'number': 85}, 'eval_contextoGeologicoDeBacia': {'precision': 0.7272727272727273, 'recall': 0.7619047619047619, 'f1': 0.7441860465116279, 'number': 210}, 'eval_elementoQuimico': {'precision': 0.8, 'recall': 1.0, 'f1': 0.888888888888889, 'number': 4}, 'eval_eon': {'precision': 0.8695652173913043, 'recall': 0.9090909090909091, 'f1': 0.888888888888889, 'number': 22}, 'eval_epoca': {'precision': 0.9130434782608695, 'recall': 0.9767441860465116, 'f1': 0.9438202247191011, 'number': 86}, 'eval_era': {'precision': 0.8913043478260869, 'recall': 0.9534883720930233, 'f1': 0.9213483146067417, 'number': 43}, 'eval_estratigrafia': {'precision': 0.8592592592592593, 'recall': 0.8345323741007195, 'f1': 0.8467153284671532, 'number': 139}, 'eval_estruturaGeologica': {'precision': 0.2916666666666667, 'recall': 0.4375, 'f1': 0.35000000000000003, 'number': 16}, 'eval_estruturaSedimentar': {'precision': 0.1111111111111111, 'recall': 0.034482758620689655, 'f1': 0.05263157894736842, 'number': 58}, 'eval_fosseis': {'precision': 0.6461538461538462, 'recall': 0.711864406779661, 'f1': 0.6774193548387097, 'number': 59}, 'eval_geomorfologia': {'precision': 1.0, 'recall': 0.7692307692307693, 'f1': 0.8695652173913044, 'number': 13}, 'eval_granulometria': {'precision': 0.7792207792207793, 'recall': 0.7317073170731707, 'f1': 0.7547169811320754, 'number': 82}, 'eval_idade': {'precision': 0.8181818181818182, 'recall': 0.9278350515463918, 'f1': 0.8695652173913045, 'number': 97}, 'eval_magmaticas': {'precision': 0.7424242424242424, 'recall': 0.875, 'f1': 0.8032786885245902, 'number': 56}, 'eval_metamorficas': {'precision': 0.6511627906976745, 'recall': 0.9032258064516129, 'f1': 0.7567567567567568, 'number': 62}, 'eval_mineral': {'precision': 0.9545454545454546, 'recall': 0.9333333333333333, 'f1': 0.9438202247191012, 'number': 45}, 'eval_periodo': {'precision': 0.927710843373494, 'recall': 0.875, 'f1': 0.9005847953216374, 'number': 88}, 'eval_planctonico': {'precision': 0.5833333333333334, 'recall': 1.0, 'f1': 0.7368421052631579, 'number': 14}, 'eval_procedimentoMetodologico': {'precision': 0.9411764705882353, 'recall': 0.8648648648648649, 'f1': 0.9014084507042254, 'number': 37}, 'eval_sedimentaresCarbonaticas': {'precision': 0.823943661971831, 'recall': 0.8068965517241379, 'f1': 0.8153310104529616, 'number': 145}, 'eval_sedimentaresOrganicas': {'precision': 0.7, 'recall': 1.0, 'f1': 0.8235294117647058, 'number': 7}, 'eval_sedimentaresQuimicas': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 7}, 'eval_sedimentaresSiliciclasticas': {'precision': 0.7887323943661971, 'recall': 0.8452830188679246, 'f1': 0.8160291438979963, 'number': 530}, 'eval_sistemaPetrolifero': {'precision': 0.9285714285714286, 'recall': 1.0, 'f1': 0.962962962962963, 'number': 13}, 'eval_unidadeEstratigrafica': {'precision': 0.8512110726643599, 'recall': 0.8978102189781022, 'f1': 0.8738898756660747, 'number': 274}, 'eval_unidadeGeotectonica': {'precision': 0.2857142857142857, 'recall': 0.25, 'f1': 0.26666666666666666, 'number': 8}, 'eval_overall_precision': 0.7788, 'eval_overall_recall': 0.7879401052205585, 'eval_overall_f1': 0.7833433916716959, 'eval_overall_accuracy': 0.9723849372384937, 'eval_f1_micro': 0.9723849372384937, 'eval_f1_macro': 0.6020732383933304, 'eval_f1_weighted': 0.9686079379785297, 'eval_runtime': 10.8099, 'eval_samples_per_second': 97.503, 'eval_steps_per_second': 6.106, 'epoch': 5.0}

20

In [24]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()