In [1]:
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional
import json, random, itertools, os, gc, statistics as st
import seqeval

import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict, concatenate_datasets
from sklearn.model_selection import KFold, train_test_split
from collections import Counter
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import BallTree
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from sklearn.cluster import KMeans
from dataclasses import dataclass, field

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
)

from seqeval.metrics import f1_score, classification_report
from evaluate import load as load_metric
from tqdm.auto import tqdm

/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def _get(d: Dict[str, Any], k: str, default=None):
    return d.get(k, default)


@dataclass
class NERMetricsCollector:
    overall_rows: List[Dict[str, Any]] = field(default_factory=list)
    label_rows: List[Dict[str, Any]] = field(default_factory=list)
    meta: Dict[str, Any] = field(
        default_factory=dict
    )  # ex.: nome do modelo, dataset, etc.

    def record(
        self,
        split_name: Any,
        metrics: Dict[str, Any],
        extras: Optional[Dict[str, Any]] = None,
    ):
        """
        Registra os resultados de um split.
        - split_name: pode ser string, int, tupla... será convertido para string
        - metrics: dict retornado pelo seu train/eval
        - extras: (opcional) dict com metadados (seed, versão, etc.)
        """
        split_str = str(split_name)

        # ------------------------------
        # Tabela 1: métricas gerais
        # ------------------------------
        overall = {
            "split": split_str,
            "eval_loss": _get(metrics, "eval_loss"),
            "overall_precision": _get(metrics, "eval_overall_precision"),
            "overall_recall": _get(metrics, "eval_overall_recall"),
            "overall_f1": _get(metrics, "eval_overall_f1"),
            "overall_accuracy": _get(metrics, "eval_overall_accuracy"),
            "f1_micro": _get(metrics, "eval_f1_micro"),
            "f1_macro": _get(metrics, "eval_f1_macro"),
            "f1_weighted": _get(metrics, "eval_f1_weighted"),
            "runtime_s": _get(metrics, "eval_runtime"),
            "samples_per_sec": _get(metrics, "eval_samples_per_second"),
            "steps_per_sec": _get(metrics, "eval_steps_per_second"),
            "epoch": _get(metrics, "epoch"),
        }

        self.overall_rows.append(overall)

        # ------------------------------
        # Tabela 2: métricas por rótulo
        # ------------------------------
        # Regra: qualquer entrada do dict que seja outro dict contendo
        # precision/recall/f1/number é tratada como rótulo.
        for k, v in metrics.items():
            if isinstance(v, dict) and {"precision", "recall", "f1", "number"} <= set(
                v.keys()
            ):
                self.label_rows.append(
                    {
                        "split": split_str,
                        "label": k.replace(
                            "eval_", ""
                        ),  # remove prefixo "eval_" para ficar limpo
                        "precision": v["precision"],
                        "recall": v["recall"],
                        "f1": v["f1"],
                        "support": v["number"],
                    }
                )

    # Comentário: retorna DataFrames prontos para inspeção ou export
    def to_dataframes(self):
        df_overall = pd.DataFrame(self.overall_rows)
        df_labels = pd.DataFrame(self.label_rows)
        return df_overall, df_labels

    # Comentário: exporta dois CSVs (UTF-8 com BOM para abrir liso no Excel)
    def to_csv(self, base_name: str = "ner"):
        df_overall, df_labels = self.to_dataframes()
        df_overall.to_csv(
            f"{base_name}_overall_metrics.csv", index=False, encoding="utf-8-sig"
        )
        df_labels.to_csv(
            f"{base_name}_label_metrics.csv", index=False, encoding="utf-8-sig"
        )
        return f"{base_name}_overall_metrics.csv", f"{base_name}_label_metrics.csv"


# --- Cria (ou reaproveita) um coletor global ---
if "ner_collector" not in globals():
    ner_collector = NERMetricsCollector()

# Configuração e Verificação Inicial

In [3]:
SEED_GLOBAL = 42
random.seed(SEED_GLOBAL)
np.random.seed(SEED_GLOBAL)
torch.manual_seed(SEED_GLOBAL)

MODEL_NAME = "albert/albert-base-v2"

In [4]:
def read_conll(path):
    tokens, tags = [], []
    sent_tokens, sent_tags = [], []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()
            if not line:
                if tokens:
                    sent_tokens.append(tokens)
                    sent_tags.append(tags)
                    tokens, tags = [], []
            else:
                tok, _, _, ner = line.split()
                tokens.append(tok)
                tags.append(ner)
    # último sentença
    if tokens:
        sent_tokens.append(tokens)
        sent_tags.append(tags)
    return sent_tokens, sent_tags

In [5]:
def read_conll(path: Path, start_sentence_id: int = 0):
    """
    Lê arquivos CoNLL/ CleanCoNLL:
      • usa parts[0] como token
      • usa parts[-1] como rótulo NER (corrigido)
      • ignora linhas '-DOCSTART- …'
    """
    tokens, tags, sent_ids = [], [], []
    cur_toks, cur_tags = [], []
    sid = start_sentence_id

    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.rstrip()

            if not line:  # fim da sentença
                if cur_toks:
                    tokens.append(cur_toks)
                    tags.append(cur_tags)
                    sent_ids.append(sid)
                    sid += 1
                    cur_toks, cur_tags = [], []
                continue

            parts = line.split()
            if parts[0] == "-DOCSTART-":  # pula marcador de doc
                continue

            tok, ner = parts[0], parts[-1]  # 1ª e última coluna
            cur_toks.append(tok)
            cur_tags.append(ner)

    if cur_toks:  # última sentença
        tokens.append(cur_toks)
        tags.append(cur_tags)
        sent_ids.append(sid)

    return tokens, tags, sent_ids, sid  # devolve sid para continuar contagem

In [6]:
def load_cleanconll(base_dir=None, keep_sentence_id=True):
    # 1. Resolva o diretório da forma mais robusta possível
    if base_dir is None:
        # base_dir = Path.home() / "Documents" / "mestrado" / "ner_splits" / "data" -> Windows
        base_dir = Path.home() / "Estudos" / "mestrado" / "data"  # -> Linux
    else:
        base_dir = Path(base_dir).expanduser()

    FILES = {
        "train": "cleanconll.train",
        "dev"  : "cleanconll.dev",
        "test" : "cleanconll.test",
    }

    # 2. Verifique se todos os arquivos existem antes de começar
    missing = [fname for fname in FILES.values() if not (base_dir / fname).exists()]
    if missing:
        raise FileNotFoundError(f"Arquivos não encontrados em {base_dir}: {', '.join(missing)}")

    splits, sid = {}, 0
    for split, fname in FILES.items():
        toks, labs, sids, sid = read_conll(base_dir / fname, sid)
        data = {"tokens": toks, "ner_tags": labs}
        if keep_sentence_id:
            data["sentence_id"] = sids
        splits[split] = Dataset.from_dict(data)

    return DatasetDict(splits)

In [7]:
cleanconll_ds = load_cleanconll()  # pronto!
print(cleanconll_ds)

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags', 'sentence_id'],
        num_rows: 13957
    })
    dev: Dataset({
        features: ['tokens', 'ner_tags', 'sentence_id'],
        num_rows: 3233
    })
    test: Dataset({
        features: ['tokens', 'ner_tags', 'sentence_id'],
        num_rows: 3427
    })
})

In [8]:
cleanconll_ds["train"] = cleanconll_ds["train"].add_column(
    "split", ["train"] * len(cleanconll_ds["train"])
)
cleanconll_ds["dev"] = cleanconll_ds["dev"].add_column(
    "split", ["dev"] * len(cleanconll_ds["dev"])
)
cleanconll_ds["test"] = cleanconll_ds["test"].add_column(
    "split", ["test"] * len(cleanconll_ds["test"])
)

cleanconll_full = concatenate_datasets(
    [
        cleanconll_ds["train"],
        cleanconll_ds["dev"],
        cleanconll_ds["test"],
    ]
)

In [9]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({l for sent in cleanconll_full["ner_tags"] for l in sent})
label2id   = {l: i for i, l in enumerate(label_list)}
id2label   = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [10]:
id2label

{0: 'B-LOC',
 1: 'B-MISC',
 2: 'B-ORG',
 3: 'B-PER',
 4: 'I-LOC',
 5: 'I-MISC',
 6: 'I-ORG',
 7: 'I-PER',
 8: 'O'}

In [11]:
NUM_LABELS

9

# Splits

In [12]:
def loc_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    ngram: int = 4,
    seed: int = 42,
) -> DatasetDict:
    """
    Divide por sobreposição léxica (n-gram Jaccard).
    Frações independentes para teste e validação.
    """
    docs = [" ".join(toks) for toks in dataset["tokens"]]

    vect = CountVectorizer(
        analyzer="word", ngram_range=(ngram, ngram), binary=True
    ).fit(docs)
    X = vect.transform(docs)
    bin_counts = X.sum(axis=1).A1

    sim = cosine_similarity(X, dense_output=False)
    k = 5
    topk = np.zeros(len(dataset))
    for i in range(sim.shape[0]):
        row = sim.getrow(i).toarray()[0]
        idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
        inter = row[idx] * bin_counts[i]
        uni = bin_counts[i] + bin_counts[idx] - inter
        topk[i] = (inter / uni).mean()

    order = np.argsort(topk)  # baixo → alto overlap
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[:n_test]
    val_idx = order[n_test : n_test + n_val]
    train_idx = order[n_test + n_val :]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [13]:
def semantic_cluster_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    k: int | None = None,
    seed: int = 42,
) -> DatasetDict:
    """
    Clusters SBERT → reserva clusters distantes para test/val.
    """
    if k is None:
        k = int(np.sqrt(len(dataset)))

    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    embeddings = sbert.encode(
        [" ".join(t) for t in tqdm(dataset["tokens"])],
        batch_size=64,
        show_progress_bar=False,
    )

    km = KMeans(n_clusters=k, random_state=seed, n_init=10).fit(embeddings)
    labels = km.labels_
    centroids = km.cluster_centers_

    global_center = embeddings.mean(0, keepdims=True)
    dists = pairwise_distances(centroids, global_center).flatten()

    clusters_sorted = np.argsort(-dists)  # mais distantes primeiro
    test_clusters, val_clusters = set(), set()
    total_test = total_val = 0
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    for c in clusters_sorted:
        size = np.sum(labels == c)
        if total_test < n_test:  # preenche primeiro o teste
            test_clusters.add(c)
            total_test += size
        elif total_val < n_val:  # depois a validação
            val_clusters.add(c)
            total_val += size
        if total_test >= n_test and total_val >= n_val:
            break

    test_idx = np.where([lbl in test_clusters for lbl in labels])[0]
    val_idx = np.where([lbl in val_clusters for lbl in labels])[0]
    train_idx = np.where(
        [lbl not in test_clusters and lbl not in val_clusters for lbl in labels]
    )[0]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [14]:
def difficulty_scores(dataset: Dataset) -> np.ndarray:
    length = np.array([len(tok) for tok in dataset["tokens"]], dtype=float)
    length = (length - length.mean()) / length.std()

    dens = []
    for labels in dataset["ner_tags"]:
        non_o = sum(1 for l in labels if l != "O")
        dens.append(non_o / len(labels))
    dens = np.array(dens)
    dens = (dens - dens.mean()) / dens.std()

    ent_types, freq = [], Counter()
    for labels in dataset["ner_tags"]:
        types = [l[2:] for l in labels if l != "O"]
        ent_types.append(types[0] if types else "NONE")
    freq.update(ent_types)
    rarity = np.array([1 / freq[t] for t in ent_types])
    rarity = (rarity - rarity.mean()) / rarity.std()

    return length + dens + rarity


def reverse_curriculum_split(
    dataset: Dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
) -> DatasetDict:
    scores = difficulty_scores(dataset)
    order = np.argsort(scores)  # easy→hard
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[-n_test:]  # hardest
    val_idx = order[-(n_test + n_val) : -n_test]
    train_idx = order[: -(n_test + n_val)]

    rng = np.random.RandomState(seed)
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    rng.shuffle(test_idx)

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [15]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42) -> DatasetDict:
    """Testa só sentenças ≥ máx(len_train)."""
    sent_lens = np.array([len(t) for t in dataset["tokens"]])
    # separação inicial train/dev (randômica estratificando por tamanho grosso)
    idx_all   = np.arange(len(dataset))
    train_idx, temp_idx = train_test_split(idx_all,
                                           test_size=pct_test + pct_val,
                                           stratify=(sent_lens//5),  # bin len
                                           random_state=seed)
    # define longo-threshold como tamanho máx. do treino
    max_train_len = sent_lens[train_idx].max()
    # test = sentenças > threshold.  Caso falte/ sobre exemplos, ajusta.
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]
    # completa ou reduz para atingir pct_test
    need = int(pct_test*len(dataset)) - len(test_idx)
    if need > 0:
        test_idx.extend(resto_idx[:need])
        val_idx = resto_idx[need:]
    else:
        val_keep = int(pct_val*len(dataset))
        val_idx  = resto_idx[:val_keep]
        test_idx = test_idx[: int(pct_test*len(dataset))]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 2) Heuristic Rare-Words ----------------------------------
def heur_rare_split(dataset: Dataset,
                    pct_test: float = 0.20,
                    pct_val : float = 0.10,
                    seed: int = 42) -> DatasetDict:
    """Testa frases que contenham palavras do quintil + raro."""
    # contagem de frequência de token
    freqs = Counter(w for toks in dataset["tokens"] for w in toks)
    # define rareza: 20 % mais raras
    thresh = np.quantile(list(freqs.values()), 0.20)
    rare_set = {w for w,c in freqs.items() if c <= thresh}
    is_rare = np.array([any(w in rare_set for w in toks)
                        for toks in dataset["tokens"]])
    rare_idx   = np.where(is_rare)[0]
    common_idx = np.where(~is_rare)[0]
    # garante proporções desejadas
    n_test = int(pct_test*len(dataset))
    n_val  = int(pct_val *len(dataset))
    rng = np.random.default_rng(seed)
    test_idx = rng.choice(rare_idx, size=min(len(rare_idx), n_test),
                          replace=False)
    resto_idx = [i for i in rare_idx if i not in test_idx] + list(common_idx)
    val_idx  = rng.choice(resto_idx, size=n_val, replace=False)
    train_idx = [i for i in resto_idx if i not in val_idx]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 3) Standard (80-10-10) -----------------------------------
def std_split(dataset: Dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42) -> DatasetDict:
    """Split aleatório estratificado por comprimento (PTB-like)."""
    idx = np.arange(len(dataset))
    strat = (np.array([len(t) for t in dataset["tokens"]]) // 5)
    train_idx, temp_idx = train_test_split(idx, test_size=pct_test+pct_val,
                                          stratify=strat, random_state=seed)
    val_rel = pct_val / (pct_test+pct_val)
    val_idx, test_idx = train_test_split(temp_idx, test_size=1-val_rel,
                                         stratify=strat[temp_idx],
                                         random_state=seed)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 4) Adversarial (approx. Wasserstein) ---------------------
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Seleciona k frases 'mais distantes' recursivamente (BallTree + W₂)
    para compor o teste, lembrando Alg.-1 de Søgaard et al.【turn6file4】.
    """
    # SBERT embed (rápido na GPU / aceitável CPU)
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(toks) for toks in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    # BallTree para vizinhança eficiente
    tree = BallTree(emb, leaf_size=40)
    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)
    print(f"Selecionando {int(pct_test*len(dataset))} sentenças para teste...")
    while len(test_idx) < int(pct_test*len(dataset)):
        print(f"  {len(test_idx)} selecionadas...")
        # amostra candidata: ponto + longe do centro
        center = emb[list(idx_pool)].mean(0, keepdims=True)
        dists, _ = tree.query(center, k=len(idx_pool))
        farthest = list(idx_pool)[int(dists.argmax())]
        # pega-se farest e seus k-NN mais próximos  ⇒ aumenta diversidade
        nn = tree.query([emb[farthest]], k=k, return_distance=False)[0]
        for j in nn:
            if j in idx_pool and len(test_idx) < int(pct_test*len(dataset)):
                test_idx.append(j)
                idx_pool.remove(j)
    # retira val
    val_size = int(pct_val*len(dataset))
    val_idx  = rng.choice(list(idx_pool), size=val_size, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [16]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42,
                   bin_size: int = 10) -> DatasetDict:
    """
    Teste = sentenças mais longas que max(len(train)).
    Robusto a datasets pequenos: se estratificação falhar, usa split aleatório.
    """
    rng = np.random.default_rng(seed)
    idx_all   = np.arange(len(dataset))
    sent_lens = np.array([len(t) for t in dataset["tokens"]])

    # ------ 1) tenta split estratificado por baldes -------------------------
    strat = (sent_lens // bin_size)
    try:
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            stratify=strat,
            random_state=seed,
        )
    except ValueError:                       # classes com 1 amostra
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # ------ 2) escolhe test = len > max(train) ------------------------------
    max_train_len = sent_lens[train_idx].max()
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]

    # garante tamanhos exatos
    n_test_desired = int(pct_test * len(dataset))
    n_val_desired  = int(pct_val  * len(dataset))

    # completa teste se ficou pequeno
    if len(test_idx) < n_test_desired:
        extra = rng.choice(resto_idx,
                           size=n_test_desired - len(test_idx),
                           replace=False)
        test_idx.extend(extra)
        resto_idx = [i for i in resto_idx if i not in extra]

    # define validação
    val_idx  = rng.choice(resto_idx, size=n_val_desired, replace=False)
    train_idx = [i for i in idx_all if i not in test_idx and i not in val_idx]

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [17]:
def std_split(dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42,
              bin_size: int = 5) -> DatasetDict:
    """
    Split 80-10-10 robusto.
      • Tenta estratificar por comprimento // bin_size.
      • Se houver classes com <2 amostras, recua p/ split aleatório.
    """
    idx  = np.arange(len(dataset))
    bins = (np.array([len(t) for t in dataset["tokens"]]) // bin_size)

    try:
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            stratify=bins,
            random_state=seed,
        )
    except ValueError:                       # classes muito pequenas
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # fraciona temp em val / test mantendo proporção desejada
    val_share = pct_val / (pct_test + pct_val)
    try:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            stratify=bins[temp_idx],
            random_state=seed,
        )
    except ValueError:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [18]:
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Versão robusta: nunca “trava” antes de atingir n_test.
    Seleciona blocos de k sentenças mais distantes do centro iterativamente.
    """
    # -------------------------------- embeds -------------------------------
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(t) for t in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    tree = BallTree(emb, leaf_size=40)

    n_test = int(pct_test * len(dataset))
    n_val  = int(pct_val  * len(dataset))

    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)

    print(f"Selecionando {n_test} sentenças para teste…")
    step = 0
    while len(test_idx) < n_test and idx_pool:
        if step % 5 == 0:
            print(f"  {len(test_idx)} selecionadas…")
        step += 1

        pool_list = list(idx_pool)
        center = emb[pool_list].mean(0, keepdims=True)

        # distância euclidiana ao centro global restante
        dists, _ = tree.query(center, k=len(pool_list))
        farthest_local_idx = int(dists.argmax())
        farthest_global_idx = pool_list[farthest_local_idx]

        # número efetivo de vizinhos
        k_eff = min(k, len(idx_pool))
        nn = set(tree.query([emb[farthest_global_idx]],
                            k=k_eff,
                            return_distance=False)[0])

        # adiciona vizinhos ainda não selecionados
        for j in nn:
            if j in idx_pool and len(test_idx) < n_test:
                test_idx.append(j)
                idx_pool.remove(j)

        # Se nada foi adicionado (pode acontecer quando sobram <k únicos)
        if farthest_global_idx not in test_idx:
            test_idx.append(farthest_global_idx)
            idx_pool.remove(farthest_global_idx)

    # ------------------------ validação e treino ---------------------------
    val_idx = rng.choice(list(idx_pool), size=n_val, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [19]:
def standard_split_conll(
    dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
):

    ds = DatasetDict(
        {("val" if k == "dev" else k): v for k, v in cleanconll_ds.items()}
    )
    return ds

In [20]:
# standard_split = standard_split_conll(cleanconll_full)
# print('std')
# # random_splt = random_splits(cleanconll_full)
# # print('random')
# heur_len = heur_len_split(cleanconll_full)
# print("heur_len")
# heur_rare = heur_rare_split(cleanconll_full)
# print("heur_rare")
# advers = adversarial_split(cleanconll_full)
# print("advs")
# loc = loc_split(cleanconll_full)
# print("loc")
# semantic = semantic_cluster_split(cleanconll_full)
# print("semantic")
# reverse = reverse_curriculum_split(cleanconll_full)
# print("reverse")

# Experimentos

In [21]:
from sklearn.metrics import f1_score as skl_f1

In [22]:
def train_ner_with_split(
    dataset: Dataset,
    split: str,  # "loc" | "semantic" | "reverse" | func
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    model_ckpt: str = "Davlan/distilbert-base-multilingual-cased-ner-hrl",
    training_args_kwargs: dict | None = None,
    split_kwargs: dict | None = None,
    seed: int = 42,
):
    """
    Treina um modelo de NER usando a estratégia de split desejada.
    Retorna (trainer, métricas_test).
    """
    # 1. Escolhe função de split ------------------------------------------------
    if callable(split):
        split_fn = split
    else:
        _map = {
            "loc": loc_split,
            "reverse": reverse_curriculum_split,
            "semantic": semantic_cluster_split,
            "heur_len": heur_len_split,
            "heur_rare": heur_rare_split,
            "std": standard_split_conll,
            "advs": adversarial_split,
        }
        if split not in _map:
            raise ValueError(f"split='{split}' não reconhecido.")
        split_fn = _map[split]

    split_kwargs = split_kwargs or {}
    ds = split_fn(
        dataset, pct_test=pct_test, pct_val=pct_val, seed=seed, **split_kwargs
    )  # train/val/test

    # 2. Tokenizer e modelo -----------------------------------------------------
    label_list = sorted({l for labels in dataset["ner_tags"] for l in labels})
    label2id = {l: i for i, l in enumerate(label_list)}
    id2label = {i: l for l, i in label2id.items()}

    num_labels = len(label_list)
    tok = AutoTokenizer.from_pretrained(model_ckpt)
    model = AutoModelForTokenClassification.from_pretrained(
        model_ckpt,
        num_labels=num_labels,  # ← adapta o tamanho
        ignore_mismatched_sizes=True,  # ← descarta pesos velhos da head
    )
    model.config.id2label = id2label
    model.config.label2id = label2id

    # 3. Mapeamento label↔id ----------------------------------------------------
    # label_list = sorted(
    #     {l for labels in dataset["ner_tags"] for l in labels if l != "O"}
    # )

    # 4. Tokenização + alinhamento ---------------------------------------------
    # def tok_function(ex):
    #     return tok(
    #         ex["tokens"], is_split_into_words=True, truncation=True, padding=False
    #     )

    # def align_labels(ex):
    #     word_ids = ex.word_ids()
    #     labels = []
    #     for w in word_ids:
    #         if w is None:
    #             labels.append(-100)
    #         else:
    #             labels.append(label2id.get(ex["ner_tags"][w], 0))
    #     ex["labels"] = labels
    #     return ex

    # ds_tok = ds.map(tok_function, batched=True)
    # ds_tok = ds_tok.map(align_labels)

    def tokenize_and_align_labels(examples, label_all_tokens=False):
        tokenized = tok(examples["tokens"], is_split_into_words=True, truncation=True)

        labels_batch = []
        for i, word_labels in enumerate(examples["ner_tags"]):
            word_ids = tokenized.word_ids(batch_index=i)  # <- aqui sim
            label_ids = []
            previous_word_idx = None
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)  # máscara
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[word_labels[word_idx]])
                else:
                    # marca sub-tokens; mude para `label2id[...]`
                    # se quiser repetir label em todos os sub-tokens
                    label_ids.append(
                        label2id[word_labels[word_idx]] if label_all_tokens else -100
                    )
                previous_word_idx = word_idx
            labels_batch.append(label_ids)

        tokenized["labels"] = labels_batch
        return tokenized

    ds_tok = ds.map(
        tokenize_and_align_labels, batched=True, remove_columns=ds["train"].column_names
    )
    # 5. Métrica (seqeval) ------------------------------------------------------
    seqeval = load_metric("seqeval")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)

        sent_preds, sent_labels = [], []  # p/ seqeval
        flat_preds, flat_labels = [], []  # p/ sklearn

        for p_row, l_row in zip(preds, labels):
            p_sent, l_sent = [], []
            for pi, li in zip(p_row, l_row):
                if li != -100:
                    lbl_true = id2label[li]
                    lbl_pred = id2label[pi]
                    p_sent.append(lbl_pred)
                    l_sent.append(lbl_true)
                    flat_preds.append(lbl_pred)
                    flat_labels.append(lbl_true)
            sent_preds.append(p_sent)
            sent_labels.append(l_sent)

        # métricas seqeval (micro F1 = overall_f1)
        seqeval_metrics = seqeval.compute(
            predictions=sent_preds,
            references=sent_labels,
        )

        # métricas sklearn
        f1_micro = skl_f1(flat_labels, flat_preds, average="micro", zero_division=0)
        f1_macro = skl_f1(flat_labels, flat_preds, average="macro", zero_division=0)
        f1_weighted = skl_f1(
            flat_labels, flat_preds, average="weighted", zero_division=0
        )

        return {
            **seqeval_metrics,  # overall_precision / recall / f1
            "f1_micro": f1_micro,
            "f1_macro": f1_macro,
            "f1_weighted": f1_weighted,
        }

    # 6. Args de treinamento ----------------------------------------------------
    args_defaults = dict(
        # output_dir=f"ner-{split}",
        # estratégia de avaliação + salvamento
        eval_strategy="epoch",  # novo nome (4.52+)
        save_strategy="no",
        # load_best_model_at_end=True,
        metric_for_best_model="overall_f1",
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=5,
        seed=seed,
        report_to="none",
    )

    if training_args_kwargs:
        args_defaults.update(training_args_kwargs)
    args = TrainingArguments(**args_defaults)

    data_collator = DataCollatorForTokenClassification(tokenizer=tok, padding=True)

    # 7. Trainer ---------------------------------------------------------------
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tok["train"],
        eval_dataset=ds_tok["val"],
        tokenizer=tok,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    # 8. Avaliação final --------------------------------------------------------
    test_metrics = trainer.evaluate(eval_dataset=ds_tok["test"])
    return trainer, test_metrics

In [23]:
splits = ["loc", "reverse", "semantic", "heur_len", "heur_rare", "std", "advs"]

In [24]:
results = {}
trainer_all = {}
s = splits[0]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: loc

/tmp/ipykernel_442257/4053031328.py:28: RuntimeWarning: invalid value encountered in divide
  topk[i] = (inter / uni).mean()
Map: 100%|██████████| 14433/14433 [00:00<00:00, 16767.26 examples/s]
Map: 100%|██████████| 2061/2061 [00:00<00:00, 19035.97 examples/s]
Map: 100%|██████████| 4123/4123 [00:00<00:00, 17906.93 examples/s]
/home/hartb/Estudos/mestrado/ner_splits/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
/tmp/ipykernel_442257/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.9330494000180107
F1 Micro: 0.9907281604132762
F1 Weighted: 0.9907164560738976
{'eval_loss': 0.054959286004304886, 'eval_LOC': {'precision': 0.9679054054054054, 'recall': 0.9491993373826615, 'f1': 0.9584611095623083, 'number': 1811}, 'eval_MISC': {'precision': 0.8671655753040225, 'recall': 0.8720602069614299, 'f1': 0.8696060037523452, 'number': 1063}, 'eval_ORG': {'precision': 0.8910569105691057, 'recall': 0.9298642533936652, 'f1': 0.9100470523110988, 'number': 1768}, 'eval_PER': {'precision': 0.9810473815461347, 'recall': 0.9732805541810985, 'f1': 0.9771485345255837, 'number': 2021}, 'eval_overall_precision': 0.9345780433159074, 'eval_overall_recall': 0.9390664865676122, 'eval_overall_f1': 0.9368168887558017, 'eval_overall_accuracy': 0.9907281604132762, 'eval_f1_micro': 0.9907281604132762, 'eval_f1_macro': 0.9330494000180107, 'eval_f1_weighted': 0.9907164560738976, 'eval_runtime': 48.3899, 'eval_samples_per_second': 85.204, 'eval_steps_per_second': 5.332, 'epoch': 5.0}

0

In [25]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [26]:
!find . -name "*.ipynb_checkpoints" -exec rm -rf {} +

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [27]:
import time

In [28]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch

In [ ]:
results = {}
trainer_all = {}
s = splits[1]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: reverse

Map: 100%|██████████| 14433/14433 [00:00<00:00, 19427.70 examples/s]
Map: 100%|██████████| 2061/2061 [00:00<00:00, 18324.43 examples/s]
Map: 100%|██████████| 4123/4123 [00:00<00:00, 14994.75 examples/s]
/tmp/ipykernel_442257/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch
   # limpa buffers de IP

In [ ]:
results = {}
trainer_all = {}
s = splits[2]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: semantic

100%|██████████| 20617/20617 [00:00<00:00, 3053674.89it/s]
Map: 100%|██████████| 14362/14362 [00:01<00:00, 13153.77 examples/s]
Map: 100%|██████████| 2075/2075 [00:00<00:00, 22588.18 examples/s]
Map: 100%|██████████| 4180/4180 [00:00<00:00, 31432.88 examples/s]
/tmp/ipykernel_7866/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.9540100531973619
F1 Micro: 0.9868720594930945
F1 Weighted: 0.9865837850195649
{'eval_loss': 0.08238779753446579, 'eval_LOC': {'precision': 0.9675028506271379, 'recall': 0.9866279069767442, 'f1': 0.9769717904432931, 'number': 1720}, 'eval_MISC': {'precision': 0.8459343794579173, 'recall': 0.8201936376210235, 'f1': 0.8328651685393258, 'number': 723}, 'eval_ORG': {'precision': 0.979539641943734, 'recall': 0.9730691056910569, 'f1': 0.9762936528167219, 'number': 1968}, 'eval_PER': {'precision': 0.9283582089552239, 'recall': 0.9688473520249221, 'f1': 0.9481707317073171, 'number': 321}, 'eval_overall_precision': 0.9517386722866175, 'eval_overall_recall': 0.9543533389687235, 'eval_overall_f1': 0.9530442123034716, 'eval_overall_accuracy': 0.9868720594930945, 'eval_f1_micro': 0.9868720594930945, 'eval_f1_macro': 0.9540100531973619, 'eval_f1_weighted': 0.9865837850195649, 'eval_runtime': 29.4755, 'eval_samples_per_second': 141.813, 'eval_steps_per_second': 8.889, 'epoch': 5.0}

0

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch
   # limpa buffers de IPC

In [ ]:
results = {}
trainer_all = {}
s = splits[3]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_len

Map: 100%|██████████| 14433/14433 [00:00<00:00, 19429.64 examples/s]
Map: 100%|██████████| 2061/2061 [00:00<00:00, 18825.04 examples/s]
Map: 100%|██████████| 4123/4123 [00:00<00:00, 11957.78 examples/s]
/tmp/ipykernel_7866/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.962138507306871
F1 Micro: 0.9929633431570581
F1 Weighted: 0.9929258121728596
{'eval_loss': 0.03630712628364563, 'eval_LOC': {'precision': 0.967979002624672, 'recall': 0.9761778718898888, 'f1': 0.9720611491829204, 'number': 1889}, 'eval_MISC': {'precision': 0.9012567324955116, 'recall': 0.9061371841155235, 'f1': 0.9036903690369037, 'number': 1108}, 'eval_ORG': {'precision': 0.9612612612612612, 'recall': 0.9560931899641577, 'f1': 0.9586702605570531, 'number': 2232}, 'eval_PER': {'precision': 0.9855289421157685, 'recall': 0.9894789579158316, 'f1': 0.9875, 'number': 1996}, 'eval_overall_precision': 0.9605135993372912, 'eval_overall_recall': 0.9629065743944637, 'eval_overall_f1': 0.9617085982858723, 'eval_overall_accuracy': 0.9929633431570581, 'eval_f1_micro': 0.9929633431570581, 'eval_f1_macro': 0.962138507306871, 'eval_f1_weighted': 0.9929258121728596, 'eval_runtime': 62.6548, 'eval_samples_per_second': 65.805, 'eval_steps_per_second': 4.118, 'epoch': 5.0}

0

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch
   # limpa buffers de IPC

In [ ]:
results = {}
trainer_all = {}
s = splits[4]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_rare

Map: 100%|██████████| 14433/14433 [00:00<00:00, 14452.25 examples/s]
Map: 100%|██████████| 2061/2061 [00:00<00:00, 17148.34 examples/s]
Map: 100%|██████████| 4123/4123 [00:00<00:00, 14054.56 examples/s]
/tmp/ipykernel_7866/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.9478290385962403
F1 Micro: 0.9910221927465213
F1 Weighted: 0.9909641735366185
{'eval_loss': 0.05344154313206673, 'eval_LOC': {'precision': 0.9645580978017048, 'recall': 0.9623992837958818, 'f1': 0.9634774815146762, 'number': 2234}, 'eval_MISC': {'precision': 0.8969072164948454, 'recall': 0.8907849829351536, 'f1': 0.8938356164383562, 'number': 1465}, 'eval_ORG': {'precision': 0.909692671394799, 'recall': 0.9267822736030829, 'f1': 0.9181579575280362, 'number': 2076}, 'eval_PER': {'precision': 0.9795493934142114, 'recall': 0.983983286908078, 'f1': 0.9817613340281397, 'number': 2872}, 'eval_overall_precision': 0.9448410870566559, 'eval_overall_recall': 0.9488840060136463, 'eval_overall_f1': 0.9468582309157002, 'eval_overall_accuracy': 0.9910221927465213, 'eval_f1_micro': 0.9910221927465213, 'eval_f1_macro': 0.9478290385962403, 'eval_f1_weighted': 0.9909641735366185, 'eval_runtime': 63.549, 'eval_samples_per_second': 64.879, 'eval_steps_per_second': 4.06, 'epoch': 5.0}

0

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch
   # limpa buffers de IPC

In [ ]:
results = {}
trainer_all = {}
s = splits[5]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: std

Map: 100%|██████████| 13957/13957 [00:00<00:00, 19425.65 examples/s]
Map: 100%|██████████| 3233/3233 [00:00<00:00, 10255.47 examples/s]
Map: 100%|██████████| 3427/3427 [00:00<00:00, 21843.61 examples/s]
/tmp/ipykernel_7866/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.9245260390942156
F1 Micro: 0.9849905384483055
F1 Weighted: 0.9849809342389966
{'eval_loss': 0.1006765142083168, 'eval_LOC': {'precision': 0.9301187980433263, 'recall': 0.9419674451521586, 'f1': 0.9360056258790436, 'number': 1413}, 'eval_MISC': {'precision': 0.8383594692400482, 'recall': 0.8559113300492611, 'f1': 0.8470444850700792, 'number': 812}, 'eval_ORG': {'precision': 0.894681960375391, 'recall': 0.8988999476165531, 'f1': 0.8967859942513717, 'number': 1909}, 'eval_PER': {'precision': 0.9667519181585678, 'recall': 0.950345694531741, 'f1': 0.9584786053882726, 'number': 1591}, 'eval_overall_precision': 0.9150121908742599, 'eval_overall_recall': 0.9177292576419214, 'eval_overall_f1': 0.9163687102119125, 'eval_overall_accuracy': 0.9849905384483055, 'eval_f1_micro': 0.9849905384483055, 'eval_f1_macro': 0.9245260390942156, 'eval_f1_weighted': 0.9849809342389966, 'eval_runtime': 39.2894, 'eval_samples_per_second': 87.225, 'eval_steps_per_second': 5.472, 'epoch': 5.0}

0

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()  # solta o cache ocioso do PyTorch
   # limpa buffers de IPC

In [ ]:
results = {}
trainer_all = {}
s = splits[6]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(cleanconll_full, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: std

Map: 100%|██████████| 13957/13957 [00:00<00:00, 21045.17 examples/s]
Map: 100%|██████████| 3233/3233 [00:00<00:00, 20305.67 examples/s]
Map: 100%|██████████| 3427/3427 [00:00<00:00, 21164.11 examples/s]
/tmp/ipykernel_7866/1801789067.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.9245260390942156
F1 Micro: 0.9849905384483055
F1 Weighted: 0.9849809342389966
{'eval_loss': 0.1006765142083168, 'eval_LOC': {'precision': 0.9301187980433263, 'recall': 0.9419674451521586, 'f1': 0.9360056258790436, 'number': 1413}, 'eval_MISC': {'precision': 0.8383594692400482, 'recall': 0.8559113300492611, 'f1': 0.8470444850700792, 'number': 812}, 'eval_ORG': {'precision': 0.894681960375391, 'recall': 0.8988999476165531, 'f1': 0.8967859942513717, 'number': 1909}, 'eval_PER': {'precision': 0.9667519181585678, 'recall': 0.950345694531741, 'f1': 0.9584786053882726, 'number': 1591}, 'eval_overall_precision': 0.9150121908742599, 'eval_overall_recall': 0.9177292576419214, 'eval_overall_f1': 0.9163687102119125, 'eval_overall_accuracy': 0.9849905384483055, 'eval_f1_micro': 0.9849905384483055, 'eval_f1_macro': 0.9245260390942156, 'eval_f1_weighted': 0.9849809342389966, 'eval_runtime': 36.2663, 'eval_samples_per_second': 94.495, 'eval_steps_per_second': 5.928, 'epoch': 5.0}

0

In [ ]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu": "0"})

In [ ]:
df = ner_collector.to_dataframes()

In [ ]:
df

(       split  eval_loss  overall_precision  overall_recall  overall_f1  \
 0        loc   0.054959           0.934578        0.939066    0.936817
 1    reverse   0.193439           0.880701        0.864156    0.872350
 2   semantic   0.082388           0.951739        0.954353    0.953044
 3   heur_len   0.036307           0.960514        0.962907    0.961709
 4  heur_rare   0.053442           0.944841        0.948884    0.946858
 5        std   0.100677           0.915012        0.917729    0.916369
 6        std   0.100677           0.915012        0.917729    0.916369

    overall_accuracy  f1_micro  f1_macro  f1_weighted  runtime_s  \
 0          0.990728  0.990728  0.933049     0.990716    51.1556
 1          0.974013  0.974013  0.891480     0.972969    66.7348
 2          0.986872  0.986872  0.954010     0.986584    29.4755
 3          0.992963  0.992963  0.962139     0.992926    62.6548
 4          0.991022  0.991022  0.947829     0.990964    63.5490
 5          0.984991  0.984991  0.924526     0.984981    39.2894
 6          0.984991  0.984991  0.924526     0.984981    36.2663

    samples_per_sec  steps_per_sec  epoch
 0           80.597          5.043    5.0
 1           61.782          3.866    5.0
 2          141.813          8.889    5.0
 3           65.805          4.118    5.0
 4           64.879          4.060    5.0
 5           87.225          5.472    5.0
 6           94.495          5.928    5.0  ,
         split label  precision    recall        f1  support
 0         loc   LOC   0.967905  0.949199  0.958461     1811
 1         loc  MISC   0.867166  0.872060  0.869606     1063
 2         loc   ORG   0.891057  0.929864  0.910047     1768
 3         loc   PER   0.981047  0.973281  0.977149     2021
 4     reverse   LOC   0.879987  0.911277  0.895359     2953
 5     reverse  MISC   0.924174  0.729598  0.815440     3909
 6     reverse   ORG   0.723279  0.898706  0.801506     1777
 7     reverse   PER   0.959941  0.987150  0.973356     2646
 8    semantic   LOC   0.967503  0.986628  0.976972     1720
 9    semantic  MISC   0.845934  0.820194  0.832865      723
 10   semantic   ORG   0.979540  0.973069  0.976294     1968
 11   semantic   PER   0.928358  0.968847  0.948171      321
 12   heur_len   LOC   0.967979  0.976178  0.972061     1889
 13   heur_len  MISC   0.901257  0.906137  0.903690     1108
 14   heur_len   ORG   0.961261  0.956093  0.958670     2232
 15   heur_len   PER   0.985529  0.989479  0.987500     1996
 16  heur_rare   LOC   0.964558  0.962399  0.963477     2234
 17  heur_rare  MISC   0.896907  0.890785  0.893836     1465
 18  heur_rare   ORG   0.909693  0.926782  0.918158     2076
 19  heur_rare   PER   0.979549  0.983983  0.981761     2872
 20        std   LOC   0.930119  0.941967  0.936006     1413
 21        std  MISC   0.838359  0.855911  0.847044      812
 22        std   ORG   0.894682  0.898900  0.896786     1909
 23        std   PER   0.966752  0.950346  0.958479     1591
 24        std   LOC   0.930119  0.941967  0.936006     1413
 25        std  MISC   0.838359  0.855911  0.847044      812
 26        std   ORG   0.894682  0.898900  0.896786     1909
 27        std   PER   0.966752  0.950346  0.958479     1591)

In [ ]:
nome_modelo = MODEL_NAME.split("/")[1]

In [ ]:
ner_collector.to_csv(base_name=nome_modelo)

('albert-base-v2_overall_metrics.csv', 'albert-base-v2_label_metrics.csv')