In [1]:
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional
import json, random, itertools, os, gc, statistics as st
import seqeval
import re

import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict, concatenate_datasets
from sklearn.model_selection import KFold, train_test_split
from collections import Counter
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import BallTree
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from sklearn.cluster import KMeans
from dataclasses import dataclass, field

import torch
from transformers import (
    AutoTokenizer,
        AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)

from seqeval.metrics import f1_score, classification_report
from evaluate import load as load_metric
from tqdm.auto import tqdm

c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def _get(d: Dict[str, Any], k: str, default=None):
    return d.get(k, default)

@dataclass
class NERMetricsCollector:
    overall_rows: List[Dict[str, Any]] = field(default_factory=list)
    label_rows:   List[Dict[str, Any]] = field(default_factory=list)
    meta:         Dict[str, Any] = field(default_factory=dict)  # ex.: nome do modelo, dataset, etc.

    def record(self, split_name: Any, metrics: Dict[str, Any], extras: Optional[Dict[str, Any]] = None):
        """
        Registra os resultados de um split.
        - split_name: pode ser string, int, tupla... será convertido para string
        - metrics: dict retornado pelo seu train/eval
        - extras: (opcional) dict com metadados (seed, versão, etc.)
        """
        split_str = str(split_name)

        # ------------------------------
        # Tabela 1: métricas gerais
        # ------------------------------
        overall = {
            "split": split_str,
            "eval_loss":                _get(metrics, "eval_loss"),
            "overall_precision":        _get(metrics, "eval_overall_precision"),
            "overall_recall":           _get(metrics, "eval_overall_recall"),
            "overall_f1":               _get(metrics, "eval_overall_f1"),
            "overall_accuracy":         _get(metrics, "eval_overall_accuracy"),
            "f1_micro":                 _get(metrics, "eval_f1_micro"),
            "f1_macro":                 _get(metrics, "eval_f1_macro"),
            "f1_weighted":              _get(metrics, "eval_f1_weighted"),
            "runtime_s":                _get(metrics, "eval_runtime"),
            "samples_per_sec":          _get(metrics, "eval_samples_per_second"),
            "steps_per_sec":            _get(metrics, "eval_steps_per_second"),
            "epoch":                    _get(metrics, "epoch"),
        }
        
        self.overall_rows.append(overall)

        # ------------------------------
        # Tabela 2: métricas por rótulo
        # ------------------------------
        # Regra: qualquer entrada do dict que seja outro dict contendo
        # precision/recall/f1/number é tratada como rótulo.
        for k, v in metrics.items():
            if isinstance(v, dict) and {"precision", "recall", "f1", "number"} <= set(v.keys()):
                self.label_rows.append({
                    "split": split_str,
                    "label": k.replace("eval_", ""),  # remove prefixo "eval_" para ficar limpo
                    "precision": v["precision"],
                    "recall":    v["recall"],
                    "f1":        v["f1"],
                    "support":   v["number"],
                })

    # Comentário: retorna DataFrames prontos para inspeção ou export
    def to_dataframes(self):
        df_overall = pd.DataFrame(self.overall_rows)
        df_labels  = pd.DataFrame(self.label_rows)
        return df_overall, df_labels

    # Comentário: exporta dois CSVs (UTF-8 com BOM para abrir liso no Excel)
    def to_csv(self, base_name: str = "ner"):
        df_overall, df_labels = self.to_dataframes()
        df_overall.to_csv(f"{base_name}_overall_metrics.csv", index=False, encoding="utf-8-sig")
        df_labels.to_csv(f"{base_name}_label_metrics.csv", index=False, encoding="utf-8-sig")
        return f"{base_name}_overall_metrics.csv", f"{base_name}_label_metrics.csv"


# --- Cria (ou reaproveita) um coletor global ---
if "ner_collector" not in globals():
    ner_collector = NERMetricsCollector()

# Configuração e Verificação Inicial

In [ ]:
SEED_GLOBAL = 42
random.seed(SEED_GLOBAL)
np.random.seed(SEED_GLOBAL)
torch.manual_seed(SEED_GLOBAL)

CSV_PATH = Path("../data/all_ener.csv")  # ajuste se necessário
MODEL_NAME = "albert/albert-base-v2"

df = pd.read_csv(CSV_PATH)

In [4]:
df

         -DOCSTART-  O
0               NaN  O
1             Check  O
2               the  O
3       appropriate  O
4               box  O
...             ... ..
415363         this  O
415364      Summary  O
415365   Prospectus  O
415366            .  O
415367          NaN  O

[415368 rows x 2 columns]

In [5]:
NER_MARK = "<BIO-COMMA>"

In [6]:
from datasets import Dataset, DatasetDict, Features, Sequence, Value

In [7]:
def _read_conllish_csv(df: pd.DataFrame):
    """Lê DataFrame com colunas ['-DOCSTART-', 'O'] e fecha sentenças por linha vazia ou pontuação terminal."""
    sents, tags = [], []
    cur_toks, cur_tags = [], []

    SENT_END = {".", "!", "?"}

    for _, row in df.iterrows():
        tok, lab = row["-DOCSTART-"], row["O"]

        # linha vazia / NaN => fecha sentença
        if pd.isna(tok) or str(tok).strip() == "":
            if cur_toks:
                sents.append(cur_toks); tags.append(cur_tags)
                cur_toks, cur_tags = [], []
            continue

        tok = str(tok)
        lab = str(lab)

        cur_toks.append(tok)
        cur_tags.append(lab)

        # fecha sentença se encontrar pontuação terminal
        if tok in SENT_END:
            sents.append(cur_toks); tags.append(cur_tags)
            cur_toks, cur_tags = [], []

    # flush final (última sentença sem ponto)
    if cur_toks:
        sents.append(cur_toks); tags.append(cur_tags)

    return {"tokens": sents, "ner_tags": tags}


def build_ener_dataset(
    df: pd.DataFrame,
    val_size: float = 0.15,
    test_size: float = 0.15,
    seed: int = 42,
    add_columns: bool = True,
    corpus_name: str = "ener",
):
    data = _read_conllish_csv(df)

    features = Features({
        "tokens": Sequence(Value("string")),
        "ner_tags": Sequence(Value("string")),
    })
    ds_full = Dataset.from_dict(data, features=features)

    # mapeia labels->ids
    labels = sorted({lab for seq in data["ner_tags"] for lab in seq})
    label2id = {l: i for i, l in enumerate(labels)}
    id2label = {i: l for l, i in label2id.items()}

    return ds_full, labels, label2id, id2label

In [8]:
data = _read_conllish_csv(df)

In [9]:
len(data["tokens"])

11737

In [10]:
data

{'tokens': [['Check', 'the', 'appropriate', 'box', ':'],
  ['Payment',
   'of',
   'Filing',
   'Fee',
   '(',
   'check',
   'the',
   'appropriate',
   'box',
   ')',
   ':'],
  ['Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NAN',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '2',
   '(',
   'NXK',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Investment',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen', 'New', 'York', 'Municipal', 'Value', 'Fund', ',', 'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   '2',
   '(',
   'NYV',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Performance',
   'Plus',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Quality',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Select',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NKO',
   ')'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Premium',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NRK',
   ')'],
  ['Nuveen', 'Core', 'Equity', 'Alpha', 'Fund', '(', 'JCE', ')'],
  ['Nuveen', 'Real', 'Estate', 'Income', 'Fund', '(', 'JRS', ')'],
  ['Nuveen',
   'Diversified',
   'Dividend',
   'and',
   'Income',
   'Fund',
   '(',
   'JDD',
   ')'],
  ['Nuveen', 'Equity', 'Premium', 'and', 'Growth', 'Fund', '(', 'JPG', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Advantage', 'Fund', '(', 'JLA', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Income', 'Fund', '(', 'JPZ', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Opportunity', 'Fund', '(', 'JSN', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '(', 'JTP', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '2', '(', 'JPS', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '3', '(', 'JHP', ')'],
  ['Nuveen',
   'Tax-Advantaged',
   'Total',
   'Return',
   'Strategy',
   'Fund',
   '(',
   'JTA',
   ')'],
  ['Nuveen', 'Tax-Advantaged', 'Dividend', 'Growth', 'Fund', '(', 'JTD', ')'],
  ['Nuveen',
   'Global',
   'Government',
   'Enhanced',
   'Income',
   'Fund',
   '(',
   'JGG',
   ')'],
  ['Nuveen', 'Global', 'Value', 'Opportunities', 'Fund', '(', 'JGV', ')'],
  ['Nuveen',
   'Multi-Currency',
   'Short-Term',
   'Government',
   'Income',
   'Fund',
   '(',
   'JGT',
   ')'],
  ['Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '(',
   'JPC',
   ')'],
  ['Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '2',
   '(',
   'JQC',
   ')'],
  ['To', 'the', 'Shareholders', 'of', 'the', 'Above', 'Funds', ':'],
  ['Notice',
   'is',
   'hereby',
   'given',
   'that',
   'the',
   'Annual',
   'Meeting',
   'of',
   'Shareholders',
   'of',
   'each',
   'of',
   'Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'New',
   'York',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '2',
   '(',
   'New',
   'York',
   'Dividend',
   '2',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   '2',
   '(',
   'New',
   'York',
   'Value',
   '2',
   ')',
   ',',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'Insured',
   'New',
   'York',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   ')',
   ',',
   'Nuveen',
   'Core',
   'Equity',
   'Alpha',
   'Fund',
   '(',
   'Core',
   'Equity',
   ')',
   ',',
   'Nuveen',
   'Real',
   'Estate',
   'Income',
   'Fund',
   '(',
   'Real',
   'Estate',
   ')',
   ',',
   'Nuveen',
   'Diversified',
   'Dividend',
   'and',
   'Income',
   'Fund',
   '(',
   'Diversified',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'and',
   'Growth',
   'Fund',
   '(',
   'Equity',
   'Premium',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Advantage',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Advantage',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Income',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Income',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Opportunity',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Opportunity',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '(',
   'Quality',
   'Preferred',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '2',
   '(',
   'Quality',
   'Preferred',
   '2',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '3',
   '(',
   'Quality',
   'Preferred',
   '3',
   ')',
   ',',
   'Nuveen',
   'Tax-Advantaged',
   'Total',
   'Return',
   'Strategy',
   'Fund',
   '(',
   'Tax-Advantaged',
   ')',
   ',',
   'Nuveen',
   'Tax-Advantaged',
   'Dividend',
   'Growth',
   'Fund',
   '(',
   'Tax-Advantaged',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Global',
   'Government',
   'Enhanced',
   'Income',
   'Fund',
   '(',
   'Global',
   'Government',
   ')',
   ',',
   'Nuveen',
   'Global',
   'Value',
   'Opportunities',
   'Fund',
   '(',
   'Global',
   'Value',
   ')',
   ',',
   'Nuveen',
   'Multi-Currency',
   'Short-Term',
   'Government',
   'Income',
   'Fund',
   '(',
   'Multi-Currency',
   ')',
   ',',
   'Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '(',
   'Multi-Strategy',
   ')',
   'and',
   'Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '2',
   '(',
   'Multi-Strategy',
   '2',
   ')',
   ',',
   'each',
   'a',
   'Massachusetts',
   'Business',
   'Trust',
   ',',
   'and',
   'Nuveen',
   'New',
   'York',
   'Investment',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Investment',
   'Quality',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Value',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Performance',
   'Plus',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Performance',
   'Plus',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Quality',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Quality',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Select',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Select',
   ')',
   'and',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Premium',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'Insured',
   'New',
   'York',
   'Premium',
   ')',
   ',',
   'each',
   'a',
   'Minnesota',
   'Corporation',
   '(',
   'individually',
   ',',
   'a',
   'Fund',
   'and',
   'collectively',
   ',',
   'the',
   'Funds',
   ')',
   ',',
   'will',
   'be',
   'held',
   'in',
   'the',
   '31st',
   'Floor',
   'Conference',
   'Room',
   'of',
   'Nuveen',
   'Investments',
   ',',
   '333',
   'West',
   'Wacker',
   'Drive',
   ',',
   'Chicago',
   ',',
   'Illinois',
   ',',
   'on',
   'Tuesday',
   ',',
   'April',
   '6',
   ',',
   '2010',
   ',',
   'at',
   '10:00',
   'a.m.',
   ',',
   'Central',
   'time',
   '(',
   'for',
   'each',
   'Fund',
   ',',
   'an',
   'Annual',
   'Meeting',
   ')',
   ',',
   'for',
   'the',
   'following',
   'purposes',
   'and',
   'to',
   'transact',
   'such',
   'other',
   'business',
   ',',
   'if',
   'any',
   ',',
   'as',
   'may',
   'properly',
   'come',
   'before',
   'the',
   'Annual',
   'Meeting',
   '.'],
  ['Matters', 'to', 'Be', 'Voted', 'on', 'by', 'Shareholders', ':'],
  ['Shareholders',
   'of',
   'record',
   'at',
   'the',
   'close',
   'of',
   'business',
   'on',
   'February',
   '8',
   ',',
   '2010',
   'are',
   'entitled',
   'to',
   'notice',
   'of',
   'and',
   'to',
   'vote',
   'at',
   'the',
   'Annual',
   'Meeting',
   '.'],
  ['All',
   'shareholders',
   'are',
   'cordially',
   'invited',
   'to',
   'attend',
   'the',
   'Annual',
   'Meeting',
   '.'],
  ['In',
   'order',
   'to',
   'avoid',
   'delay',
   'and',
   'additional',
   'expense',
   'and',
   'to',
   'assure',
   'that',
   'your',
   'shares',
   'are',
   'represented',
   ',',
   'please',
   'vote',
   'as',
   'promptly',
   'as',
   'possible',
   ',',
   'regardless',
   'of',
   'whether',
   'or',
   'not',
   'you',
   'plan',
   'to',
   'attend',
   'the',
   'Annual',
   'Meeting',
   '.'],
  ['You',
   'may',
   'vote',
   'by',
   'mail',
   ',',
   'telephone',
   'or',
   'over',
   'the',
   'Internet',
   '.'],
  ['To',
   'vote',
   'by',
   'mail',
   ',',
   'please',
   'mark',
   ',',
   'sign',
   ',',
   'date',
   'and',
   'mail',
   'the',
   'enclosed',
   'proxy',
   'card',
   '.'],
  ['No',
   'postage',
   'is',
   'required',
   'if',
   'mailed',
   'in',
   'the',
   'United',
   'States',
   '.'],
  ['To',
   'vote',
   'by',
   'telephone',
   ',',
   'please',
   'call',
   'the',
   'toll-free',
   'number',
   'located',
   'on',
   'your',
   'proxy',
   'card',
   'and',
   'follow',
   'the',
   'recorded',
   'instructions',
   ',',
   'using',
   'your',
   'proxy',
   'card',
   'as',
   'a',
   'guide',
   '.'],
  ['To',
   'vote',
   'over',
   'the',
   'Internet',
   ',',
   'go',
   'to',
   'the',
   'Internet',
   'address',
   'provided',
   'on',
   'your',
   'proxy',
   'card',
   'and',
   'follow',
   'the',
   'instructions',
   ',',
   'using',
   'your',
   'proxy',
   'card',
   'as',
   'a',
   'guide',
   '.'],
  ['about', 'March', '1', ',', '2010', '.'],
  ['Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NAN',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '2',
   '(',
   'NXK',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Investment',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen', 'New', 'York', 'Municipal', 'Value', 'Fund', ',', 'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   '2',
   '(',
   'NYV',
   ')'],
  ['Nuveen',
   'New',
   'York',
   'Performance',
   'Plus',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Quality',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'New',
   'York',
   'Select',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NKO',
   ')'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Premium',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.'],
  ['Nuveen',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'NRK',
   ')'],
  ['Nuveen', 'Core', 'Equity', 'Alpha', 'Fund', '(', 'JCE', ')'],
  ['Nuveen', 'Real', 'Estate', 'Income', 'Fund', '(', 'JRS', ')'],
  ['Nuveen',
   'Diversified',
   'Dividend',
   'and',
   'Income',
   'Fund',
   '(',
   'JDD',
   ')'],
  ['Nuveen', 'Equity', 'Premium', 'and', 'Growth', 'Fund', '(', 'JPG', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Advantage', 'Fund', '(', 'JLA', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Income', 'Fund', '(', 'JPZ', ')'],
  ['Nuveen', 'Equity', 'Premium', 'Opportunity', 'Fund', '(', 'JSN', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '(', 'JTP', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '2', '(', 'JPS', ')'],
  ['Nuveen', 'Quality', 'Preferred', 'Income', 'Fund', '3', '(', 'JHP', ')'],
  ['Nuveen',
   'Tax-Advantaged',
   'Total',
   'Return',
   'Strategy',
   'Fund',
   '(',
   'JTA',
   ')'],
  ['Nuveen', 'Tax-Advantaged', 'Dividend', 'Growth', 'Fund', '(', 'JTD', ')'],
  ['Nuveen',
   'Global',
   'Government',
   'Enhanced',
   'Income',
   'Fund',
   '(',
   'JGG',
   ')'],
  ['Nuveen', 'Global', 'Value', 'Opportunities', 'Fund', '(', 'JGV', ')'],
  ['Nuveen',
   'Multi-Currency',
   'Short-Term',
   'Government',
   'Income',
   'Fund',
   '(',
   'JGT',
   ')'],
  ['Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '(',
   'JPC',
   ')'],
  ['Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '2',
   '(',
   'JQC',
   ')'],
  ['This',
   'Joint',
   'Proxy',
   'Statement',
   'is',
   'furnished',
   'in',
   'connection',
   'with',
   'the',
   'solicitation',
   'by',
   'the',
   'Board',
   'of',
   'Directors',
   'or',
   'Trustees',
   '(',
   'each',
   'a',
   'Board',
   'and',
   'collectively',
   ',',
   'the',
   'Boards',
   ',',
   'and',
   'each',
   'Director',
   'or',
   'Trustee',
   'a',
   'Board',
   'Member',
   'and',
   'collectively',
   ',',
   'the',
   'Board',
   'Members',
   ')',
   'of',
   'each',
   'of',
   'Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'New',
   'York',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '2',
   '(',
   'New',
   'York',
   'Dividend',
   '2',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   '2',
   '(',
   'New',
   'York',
   'Value',
   '2',
   ')',
   ',',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Dividend',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'Insured',
   'New',
   'York',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   'Advantage',
   'Municipal',
   'Fund',
   '(',
   'Insured',
   'New',
   'York',
   'Tax-Free',
   ')',
   ',',
   'Nuveen',
   'Core',
   'Equity',
   'Alpha',
   'Fund',
   '(',
   'Core',
   'Equity',
   ')',
   ',',
   'Nuveen',
   'Real',
   'Estate',
   'Income',
   'Fund',
   '(',
   'Real',
   'Estate',
   ')',
   ',',
   'Nuveen',
   'Diversified',
   'Dividend',
   'and',
   'Income',
   'Fund',
   '(',
   'Diversified',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'and',
   'Growth',
   'Fund',
   '(',
   'Equity',
   'Premium',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Advantage',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Advantage',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Income',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Income',
   ')',
   ',',
   'Nuveen',
   'Equity',
   'Premium',
   'Opportunity',
   'Fund',
   '(',
   'Equity',
   'Premium',
   'Opportunity',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '(',
   'Quality',
   'Preferred',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '2',
   '(',
   'Quality',
   'Preferred',
   '2',
   ')',
   ',',
   'Nuveen',
   'Quality',
   'Preferred',
   'Income',
   'Fund',
   '3',
   '(',
   'Quality',
   'Preferred',
   '3',
   ')',
   ',',
   'Nuveen',
   'Tax-Advantaged',
   'Total',
   'Return',
   'Strategy',
   'Fund',
   '(',
   'Tax-Advantaged',
   ')',
   ',',
   'Nuveen',
   'Tax-Advantaged',
   'Dividend',
   'Growth',
   'Fund',
   '(',
   'Tax-Advantaged',
   'Dividend',
   ')',
   ',',
   'Nuveen',
   'Global',
   'Government',
   'Enhanced',
   'Income',
   'Fund',
   '(',
   'Global',
   'Government',
   ')',
   ',',
   'Nuveen',
   'Global',
   'Value',
   'Opportunities',
   'Fund',
   '(',
   'Global',
   'Value',
   ')',
   ',',
   'Nuveen',
   'Multi-Currency',
   'Short-Term',
   'Government',
   'Income',
   'Fund',
   '(',
   'Multi-Currency',
   ')',
   ',',
   'Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '(',
   'Multi-Strategy',
   ')',
   'and',
   'Nuveen',
   'Multi-Strategy',
   'Income',
   'and',
   'Growth',
   'Fund',
   '2',
   '(',
   'Multi-Strategy',
   '2',
   ')',
   ',',
   'each',
   'a',
   'Massachusetts',
   'Business',
   'Trust',
   ',',
   'and',
   'Nuveen',
   'New',
   'York',
   'Investment',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Investment',
   'Quality',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Municipal',
   'Value',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Value',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Performance',
   'Plus',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Performance',
   'Plus',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Quality',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Quality',
   ')',
   ',',
   'Nuveen',
   'New',
   'York',
   'Select',
   'Quality',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'New',
   'York',
   'Select',
   ')',
   'and',
   'Nuveen',
   'Insured',
   'New',
   'York',
   'Premium',
   'Income',
   'Municipal',
   'Fund',
   ',',
   'Inc.',
   '(',
   'Insured',
   'New',
   'York',
   'Premium',
   ')',
   ',',
   'each',
   'a',
   'Minnesota',
   'Corporation',
   '(',
   'individually',
   ',',
   'a',
   'Fund',
   'and',
   'collectively',
   ',',
   'the',
   'Funds',
   ')',
   ',',
   'of',
   'proxies',
   'to',
   'be',
   'voted',
   'at',
   'the',
   'Annual',
   'Meeting',
   'of',
   'Shareholders',
   'to',
   'be',
   'held',
   'in',
   'the',
   '31st',
   'Floor',
   'Conference',
   'Room',
   'of',
   'Nuveen',
   'Investments',
   ',',
   '333',
   'West',
   'Wacker',
   'Drive',
   ',',
   'Chicago',
   ',',
   'Illinois',
   ',',
   'on',
   'Tuesday',
   ',',
   'April',
   '6',
   ',',
   '2010',
   ',',
   'at',
   '10:00',
   'a.m.',
   ',',
   'Central',
   'time',
   '(',
   'for',
   'each',
   'Fund',
   ',',
   'an',
   'Annual',
   'Meeting',
   'and',
   'collectively',
   ',',
   'the',
   'Annual',
   'Meetings',
   ')',
   ',',
   'and',
   'at',
   'any',
   'and',
   'all',
   'adjournments',
   'thereof',
   '.'],
  ['On',
   'the',
   'matters',
   'coming',
   'before',
   'each',
   'Annual',
   'Meeting',
   'as',
   'to',
   'which',
   'a',
   'choice',
   'has',
   'been',
   'specified',
   'by',
   'shareholders',
   'on',
   'the',
   'proxy',
   ',',
   'the',
   'shares',
   'will',
   'be',
   'voted',
   'accordingly',
   '.'],
  ['If',
   'a',
   'properly',
   'executed',
   'proxy',
   'is',
   'returned',
   'and',
   'no',
   'choice',
   'is',
   'specified',
   ',',
   'the',
   'shares',
   'will',
   'be',
   'voted',
   'FOR',
   'the',
   'election',
   'of',
   'the',
   'nominees',
   'as',
   'listed',
   'in',
   'this',
   'Joint',
   'Proxy',
   'Statement',
   '.'],
  ['Shareholders',
   'of',
   'a',
   'Fund',
   'who',
   'execute',
   'proxies',
   'may',
   'revoke',
   'them',
   'at',
   'any',
   'time',
   'before',
   'they',
   'are',
   'voted',
   'by',
   'filing',
   'with',
   'that',
   'Fund',
   'a',
   'written',
   'notice',
   'of',
   'revocation',
   ',',
   'by',
   'delivering',
   'a',
   'duly',
   'executed',
   'proxy',
   'bearing',
   'a',
   'later',
   'date',
   ',',
   'or',
   'by',
   'attending',
   'the',
   'Annual',
   'Meeting',
   'and',
   'voting',
   'in',
   'person',
   '.'],
  ['Merely',
   'attending',
   'the',
   'Annual',
   'Meeting',

In [11]:
ener7_ds, ener7_labels, ener7_label2id, ener7_id2label = build_ener_dataset(df, corpus_name="ener7")

In [12]:
ener7_ds

Dataset({
    features: ['tokens', 'ner_tags'],
    num_rows: 11737
})

In [13]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({l for sent in ener7_ds["ner_tags"] for l in sent})
label2id   = {l: i for i, l in enumerate(label_list)}
id2label   = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [14]:
filtered = ener7_ds.filter(
    lambda example: "I-LOC" in example["ner_tags"]
)

print(filtered)
print(filtered[0])

Filter: 100%|██████████| 11737/11737 [00:00<00:00, 16391.63 examples/s]

Dataset({
    features: ['tokens', 'ner_tags'],
    num_rows: 1
})
{'tokens': ['While', 'certain', 'U.S.', 'Government-sponsored', 'agencies', '(', 'such', 'as', 'the', 'Federal', 'Home', 'Loan', 'Mortgage', 'Corporation', 'and', 'the', 'Federal', 'National', 'Mortgage', 'Association', ')', 'may', 'be', 'chartered', 'or', 'sponsored', 'by', 'acts', 'of', 'Congress', ',', 'their', 'securities', 'are', 'neither', 'issued', 'nor', 'guaranteed', 'by', 'the', 'U.S.', 'Risks', 'of', 'Repurchase', 'Agreements', 'and', 'Reverse', 'Repurchase', 'Agreements', '.'], 'ner_tags': ['O', 'O', 'I-LOCATION', 'O', 'O', 'O', 'O', 'O', 'O', 'I-GOVERNMENT', 'I-GOVERNMENT', 'I-GOVERNMENT', 'I-GOVERNMENT', 'I-GOVERNMENT', 'O', 'O', 'I-GOVERNMENT', 'I-GOVERNMENT', 'I-GOVERNMENT', 'I-GOVERNMENT', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'I-GOVERNMENT', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'I-LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}

In [15]:
id2label

{0: 'B-BUSINESS',
 1: 'B-GOVERNMENT',
 2: 'B-LEGISLATION/ACT',
 3: 'B-LOCATION',
 4: 'B-MISCELLANEOUS',
 5: 'B-PERSON',
 6: 'I-BUSINESS',
 7: 'I-COURT',
 8: 'I-GOVERNMENT',
 9: 'I-LEGISLATION/ACT',
 10: 'I-LOC',
 11: 'I-LOCATION',
 12: 'I-MISCELLANEOUS',
 13: 'I-PERSON',
 14: 'O',
 15: 'P'}

In [16]:
NUM_LABELS

16

In [17]:
def replace_labels(example):
    new_tags = []
    for tag in example["ner_tags"]:
        if tag == "P":
            new_tags.append("O")
        elif tag == "I-LOC":
            new_tags.append("I-LOCATION")
        else:
            new_tags.append(tag)
    example["ner_tags"] = new_tags
    return example

ener7_ds = ener7_ds.map(replace_labels)

Map: 100%|██████████| 11737/11737 [00:00<00:00, 15460.74 examples/s]

In [18]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({l for sent in ener7_ds["ner_tags"] for l in sent})
label2id   = {l: i for i, l in enumerate(label_list)}
id2label   = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [19]:
id2label

{0: 'B-BUSINESS',
 1: 'B-GOVERNMENT',
 2: 'B-LEGISLATION/ACT',
 3: 'B-LOCATION',
 4: 'B-MISCELLANEOUS',
 5: 'B-PERSON',
 6: 'I-BUSINESS',
 7: 'I-COURT',
 8: 'I-GOVERNMENT',
 9: 'I-LEGISLATION/ACT',
 10: 'I-LOCATION',
 11: 'I-MISCELLANEOUS',
 12: 'I-PERSON',
 13: 'O'}

# Splits

In [20]:
def split_standard(ds: Dataset) -> DatasetDict:
    """Usa coluna trainingTest do CSV (80/20 original)."""
    if "trainingTest" not in df.columns:
        raise ValueError("CSV não contém a coluna 'trainingTest'")
    train_ids = df.loc[df["trainingTest"] == "training", SENT_COL].unique()
    test_ids = df.loc[df["trainingTest"] == "test", SENT_COL].unique()
    return DatasetDict(
        train=ds.filter(lambda ex: ex["sentence_id"] in train_ids),
        dev=ds.filter(lambda ex: ex["sentence_id"] in test_ids),
    )

In [21]:
def random_splits(
    ds: Dataset, test_size=0.2, seeds: List[int] = range(30)
) -> List[DatasetDict]:
    triples = []
    for s in seeds:
        train, dev = ds.train_test_split(test_size=test_size, seed=s).values()
        triples.append(DatasetDict(train=train, dev=dev))
    return triples

In [22]:
# def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
#     lengths = np.array([len(t) for t in ds["tokens"]])
#     thr = np.percentile(lengths, 100 * (1 - top_pct))
#     mask = lengths >= thr
#     return DatasetDict(train=ds.filter(~mask), dev=ds.filter(mask))


def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
    """20 % das sentenças mais longas viram conjunto de validação (dev)."""
    lengths = np.array([len(t) for t in ds["tokens"]])
    thr = np.percentile(lengths, 100 * (1 - top_pct))  
    mask = lengths >= thr  

    dev_idx = np.where(mask)[0].tolist()  # índices → list[int]
    train_idx = np.where(~mask)[0].tolist()

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Tamanho da sentenças


# def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
#     freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
#     rare = {w for w, c in freq.items() if c <= freq_thr}

#     def has_rare(example):
#         return any(w.lower() in rare for w in example["tokens"])

#     return DatasetDict(
#         train=ds.filter(lambda ex: not has_rare(ex)), dev=ds.filter(has_rare)
#     )


def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
    freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
    rare = {w for w, c in freq.items() if c <= freq_thr}

    keep_dev = []
    for sent in ds["tokens"]:
        print(sent)
        keep_dev.append(any(w.lower() in rare for w in sent))

    dev_idx = [i for i, x in enumerate(keep_dev) if x]
    train_idx = [i for i, x in enumerate(keep_dev) if not x]

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Raridade dos tokens

In [23]:
def split_adversarial(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    embeds = model.encode([" ".join(t) for t in ds["tokens"]], show_progress_bar=False)
    tree = BallTree(embeds, leaf_size=40)

    idx_train, idx_test = set(range(len(ds))), []
    # semente = ponto mais central
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    idx_train.remove(seed_idx)
    idx_test.append(seed_idx)
    print(k)
    while len(idx_test) < k:
        print(len(idx_test))
        dists, _ = tree.query(embeds[list(idx_train)], k=1, return_distance=True)
        nxt = list(idx_train)[int(np.argmax(dists))]
        idx_train.remove(nxt)
        idx_test.append(nxt)

    return DatasetDict(
        train=ds.select(sorted(idx_train)),
        dev=ds.select(sorted(idx_test)),
    )

    # Maximizando Wassertein Distance


def split_adversarial_fast(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    """
    Farthest-Point Sampling aproximando Wasserstein – versão vetorizada.
    Seleciona pct_test (~20 %) das sentenças como conjunto 'dev'.
    """
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    embeds = model.encode(
        [" ".join(t) for t in ds["tokens"]],
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,  # acelera distância euclidiana ≈ cos
    )

    n = embeds.shape[0]
    idx_all = np.arange(n)

    # 1) ponto mais "central" (norma mais distante da média)
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    selected = [seed_idx]

    # 2) vetor de distâncias mínimas a qualquer ponto já escolhido
    min_dists = np.linalg.norm(embeds - embeds[seed_idx], axis=1)

    while len(selected) < k:
        next_idx = np.argmax(min_dists)
        selected.append(next_idx)

        # atualiza min_dists com a distância ao novo ponto — tudo de uma vez
        d_new = np.linalg.norm(embeds - embeds[next_idx], axis=1)
        min_dists = np.minimum(min_dists, d_new)

    train_idx = np.setdiff1d(idx_all, selected, assume_unique=True)

    return DatasetDict(
        train=ds.select(train_idx.tolist()),
        dev=ds.select(selected),
    )

In [24]:
# def loc_split(
#     dataset: Dataset, pct_test: float = 0.20, ngram: int = 4, seed: int = 42
# ) -> DatasetDict:
#     """
#     Split baseado em baixa sobreposição léxica (4-gram Jaccard).
#     Teste = pct_test das sentenças com menor overlap em relação ao pool.
#     """
#     # 1. Texto plano por sentença
#     docs = [" ".join(toks) for toks in dataset["tokens"]]

#     # 2. Vetorizar 4-grams (binário)
#     vect = CountVectorizer(
#         analyzer="word", ngram_range=(ngram, ngram), binary=True
#     ).fit(docs)
#     X = vect.transform(docs)

#     # 3. Similaridade Jaccard aproximada com matriz binária
#     # Jaccard(A,B) = |A∩B|/|A∪B| = 1 - |AΔB|/|A∪B|
#     # Usamos: overlap = (A·Bᵀ) / (|A|+|B|-A·Bᵀ)
#     bin_counts = X.sum(axis=1).A1

#     # Para cada doc i, escolhemos vizinho + próximo (fast):
#     from sklearn.metrics.pairwise import cosine_similarity

#     # (cosine no binário ∝ |A∩B|)
#     sim = cosine_similarity(X, dense_output=False)
#     # Soma dos top-k overlaps (k=5) como score
#     k = 5
#     topk = np.zeros(len(dataset))
#     for i in range(sim.shape[0]):
#         row = sim.getrow(i).toarray()[0]
#         idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
#         # overlap ≈ |∩|
#         inter = row[idx] * bin_counts[i]
#         uni = bin_counts[i] + bin_counts[idx] - inter
#         topk[i] = (inter / uni).mean()

#     # 4. Ordenar por overlap crescente ⇒ mais “novos” vão p/ teste
#     order = np.argsort(topk)
#     n_test = int(len(dataset) * pct_test)
#     test_idx = order[:n_test]
#     train_idx = order[n_test:]

#     return DatasetDict(
#         {"train": dataset.select(train_idx), "test": dataset.select(test_idx)}
#     )

In [25]:
def loc_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    ngram: int = 4,
    seed: int = 42,
) -> DatasetDict:
    """
    Divide por sobreposição léxica (n-gram Jaccard).
    Frações independentes para teste e validação.
    """
    docs = [" ".join(toks) for toks in dataset["tokens"]]

    vect = CountVectorizer(
        analyzer="word", ngram_range=(ngram, ngram), binary=True
    ).fit(docs)
    X = vect.transform(docs)
    bin_counts = X.sum(axis=1).A1

    sim = cosine_similarity(X, dense_output=False)
    k = 5
    topk = np.zeros(len(dataset))
    for i in range(sim.shape[0]):
        row = sim.getrow(i).toarray()[0]
        idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
        inter = row[idx] * bin_counts[i]
        uni = bin_counts[i] + bin_counts[idx] - inter
        topk[i] = (inter / uni).mean()

    order = np.argsort(topk)  # baixo → alto overlap
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[:n_test]
    val_idx = order[n_test : n_test + n_val]
    train_idx = order[n_test + n_val :]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [26]:
def semantic_cluster_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    k: int | None = None,
    seed: int = 42,
) -> DatasetDict:
    """
    Clusters SBERT → reserva clusters distantes para test/val.
    """
    if k is None:
        k = int(np.sqrt(len(dataset)))

    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    embeddings = sbert.encode(
        [" ".join(t) for t in tqdm(dataset["tokens"])],
        batch_size=64,
        show_progress_bar=False,
    )

    km = KMeans(n_clusters=k, random_state=seed, n_init=10).fit(embeddings)
    labels = km.labels_
    centroids = km.cluster_centers_

    global_center = embeddings.mean(0, keepdims=True)
    dists = pairwise_distances(centroids, global_center).flatten()

    clusters_sorted = np.argsort(-dists)  # mais distantes primeiro
    test_clusters, val_clusters = set(), set()
    total_test = total_val = 0
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    for c in clusters_sorted:
        size = np.sum(labels == c)
        if total_test < n_test:  # preenche primeiro o teste
            test_clusters.add(c)
            total_test += size
        elif total_val < n_val:  # depois a validação
            val_clusters.add(c)
            total_val += size
        if total_test >= n_test and total_val >= n_val:
            break

    test_idx = np.where([lbl in test_clusters for lbl in labels])[0]
    val_idx = np.where([lbl in val_clusters for lbl in labels])[0]
    train_idx = np.where(
        [lbl not in test_clusters and lbl not in val_clusters for lbl in labels]
    )[0]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [27]:
def difficulty_scores(dataset: Dataset) -> np.ndarray:
    length = np.array([len(tok) for tok in dataset["tokens"]], dtype=float)
    length = (length - length.mean()) / length.std()

    dens = []
    for labels in dataset["ner_tags"]:
        non_o = sum(1 for l in labels if l != "O")
        dens.append(non_o / len(labels))
    dens = np.array(dens)
    dens = (dens - dens.mean()) / dens.std()

    ent_types, freq = [], Counter()
    for labels in dataset["ner_tags"]:
        types = [l[2:] for l in labels if l != "O"]
        ent_types.append(types[0] if types else "NONE")
    freq.update(ent_types)
    rarity = np.array([1 / freq[t] for t in ent_types])
    rarity = (rarity - rarity.mean()) / rarity.std()

    return length + dens + rarity


def reverse_curriculum_split(
    dataset: Dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
) -> DatasetDict:
    scores = difficulty_scores(dataset)
    order = np.argsort(scores)  # easy→hard
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[-n_test:]  # hardest
    val_idx = order[-(n_test + n_val) : -n_test]
    train_idx = order[: -(n_test + n_val)]

    rng = np.random.RandomState(seed)
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    rng.shuffle(test_idx)

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [28]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42) -> DatasetDict:
    """Testa só sentenças ≥ máx(len_train)."""
    sent_lens = np.array([len(t) for t in dataset["tokens"]])
    # separação inicial train/dev (randômica estratificando por tamanho grosso)
    idx_all   = np.arange(len(dataset))
    train_idx, temp_idx = train_test_split(idx_all,
                                           test_size=pct_test + pct_val,
                                           stratify=(sent_lens//5),  # bin len
                                           random_state=seed)
    # define longo-threshold como tamanho máx. do treino
    max_train_len = sent_lens[train_idx].max()
    # test = sentenças > threshold.  Caso falte/ sobre exemplos, ajusta.
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]
    # completa ou reduz para atingir pct_test
    need = int(pct_test*len(dataset)) - len(test_idx)
    if need > 0:
        test_idx.extend(resto_idx[:need])
        val_idx = resto_idx[need:]
    else:
        val_keep = int(pct_val*len(dataset))
        val_idx  = resto_idx[:val_keep]
        test_idx = test_idx[: int(pct_test*len(dataset))]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 2) Heuristic Rare-Words ----------------------------------
def heur_rare_split(dataset: Dataset,
                    pct_test: float = 0.20,
                    pct_val : float = 0.10,
                    seed: int = 42) -> DatasetDict:
    """Testa frases que contenham palavras do quintil + raro."""
    # contagem de frequência de token
    freqs = Counter(w for toks in dataset["tokens"] for w in toks)
    # define rareza: 20 % mais raras
    thresh = np.quantile(list(freqs.values()), 0.20)
    rare_set = {w for w,c in freqs.items() if c <= thresh}
    is_rare = np.array([any(w in rare_set for w in toks)
                        for toks in dataset["tokens"]])
    rare_idx   = np.where(is_rare)[0]
    common_idx = np.where(~is_rare)[0]
    # garante proporções desejadas
    n_test = int(pct_test*len(dataset))
    n_val  = int(pct_val *len(dataset))
    rng = np.random.default_rng(seed)
    test_idx = rng.choice(rare_idx, size=min(len(rare_idx), n_test),
                          replace=False)
    resto_idx = [i for i in rare_idx if i not in test_idx] + list(common_idx)
    val_idx  = rng.choice(resto_idx, size=n_val, replace=False)
    train_idx = [i for i in resto_idx if i not in val_idx]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 3) Standard (80-10-10) -----------------------------------
def std_split(dataset: Dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42) -> DatasetDict:
    """Split aleatório estratificado por comprimento (PTB-like)."""
    idx = np.arange(len(dataset))
    strat = (np.array([len(t) for t in dataset["tokens"]]) // 5)
    train_idx, temp_idx = train_test_split(idx, test_size=pct_test+pct_val,
                                          stratify=strat, random_state=seed)
    val_rel = pct_val / (pct_test+pct_val)
    val_idx, test_idx = train_test_split(temp_idx, test_size=1-val_rel,
                                         stratify=strat[temp_idx],
                                         random_state=seed)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 4) Adversarial (approx. Wasserstein) ---------------------
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Seleciona k frases 'mais distantes' recursivamente (BallTree + W₂)
    para compor o teste, lembrando Alg.-1 de Søgaard et al.【turn6file4】.
    """
    # SBERT embed (rápido na GPU / aceitável CPU)
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(toks) for toks in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    # BallTree para vizinhança eficiente
    tree = BallTree(emb, leaf_size=40)
    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)
    while len(test_idx) < int(pct_test*len(dataset)):
        # amostra candidata: ponto + longe do centro
        center = emb[list(idx_pool)].mean(0, keepdims=True)
        dists, _ = tree.query(center, k=len(idx_pool))
        farthest = list(idx_pool)[int(dists.argmax())]
        # pega-se farest e seus k-NN mais próximos  ⇒ aumenta diversidade
        nn = tree.query([emb[farthest]], k=k, return_distance=False)[0]
        for j in nn:
            if j in idx_pool and len(test_idx) < int(pct_test*len(dataset)):
                test_idx.append(j)
                idx_pool.remove(j)
    # retira val
    val_size = int(pct_val*len(dataset))
    val_idx  = rng.choice(list(idx_pool), size=val_size, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [29]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42,
                   bin_size: int = 10) -> DatasetDict:
    """
    Teste = sentenças mais longas que max(len(train)).
    Robusto a datasets pequenos: se estratificação falhar, usa split aleatório.
    """
    rng = np.random.default_rng(seed)
    idx_all   = np.arange(len(dataset))
    sent_lens = np.array([len(t) for t in dataset["tokens"]])

    # ------ 1) tenta split estratificado por baldes -------------------------
    strat = (sent_lens // bin_size)
    try:
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            stratify=strat,
            random_state=seed,
        )
    except ValueError:                       # classes com 1 amostra
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # ------ 2) escolhe test = len > max(train) ------------------------------
    max_train_len = sent_lens[train_idx].max()
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]

    # garante tamanhos exatos
    n_test_desired = int(pct_test * len(dataset))
    n_val_desired  = int(pct_val  * len(dataset))

    # completa teste se ficou pequeno
    if len(test_idx) < n_test_desired:
        extra = rng.choice(resto_idx,
                           size=n_test_desired - len(test_idx),
                           replace=False)
        test_idx.extend(extra)
        resto_idx = [i for i in resto_idx if i not in extra]

    # define validação
    val_idx  = rng.choice(resto_idx, size=n_val_desired, replace=False)
    train_idx = [i for i in idx_all if i not in test_idx and i not in val_idx]

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [30]:
def std_split(dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42,
              bin_size: int = 5) -> DatasetDict:
    """
    Split 80-10-10 robusto.
      • Tenta estratificar por comprimento // bin_size.
      • Se houver classes com <2 amostras, recua p/ split aleatório.
    """
    idx  = np.arange(len(dataset))
    bins = (np.array([len(t) for t in dataset["tokens"]]) // bin_size)

    try:
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            stratify=bins,
            random_state=seed,
        )
    except ValueError:                       # classes muito pequenas
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # fraciona temp em val / test mantendo proporção desejada
    val_share = pct_val / (pct_test + pct_val)
    try:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            stratify=bins[temp_idx],
            random_state=seed,
        )
    except ValueError:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [31]:
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Versão robusta: nunca “trava” antes de atingir n_test.
    Seleciona blocos de k sentenças mais distantes do centro iterativamente.
    """
    # -------------------------------- embeds -------------------------------
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(t) for t in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    tree = BallTree(emb, leaf_size=40)

    n_test = int(pct_test * len(dataset))
    n_val  = int(pct_val  * len(dataset))

    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)

    print(f"Selecionando {n_test} sentenças para teste…")
    step = 0
    while len(test_idx) < n_test and idx_pool:
        if step % 5 == 0:
            print(f"  {len(test_idx)} selecionadas…")
        step += 1

        pool_list = list(idx_pool)
        center = emb[pool_list].mean(0, keepdims=True)

        # distância euclidiana ao centro global restante
        dists, _ = tree.query(center, k=len(pool_list))
        farthest_local_idx = int(dists.argmax())
        farthest_global_idx = pool_list[farthest_local_idx]

        # número efetivo de vizinhos
        k_eff = min(k, len(idx_pool))
        nn = set(tree.query([emb[farthest_global_idx]],
                            k=k_eff,
                            return_distance=False)[0])

        # adiciona vizinhos ainda não selecionados
        for j in nn:
            if j in idx_pool and len(test_idx) < n_test:
                test_idx.append(j)
                idx_pool.remove(j)

        # Se nada foi adicionado (pode acontecer quando sobram <k únicos)
        if farthest_global_idx not in test_idx:
            test_idx.append(farthest_global_idx)
            idx_pool.remove(farthest_global_idx)

    # ------------------------ validação e treino ---------------------------
    val_idx = rng.choice(list(idx_pool), size=n_val, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [32]:
heur_len = heur_len_split(ener7_ds)
print("heur_len")
heur_rare = heur_rare_split(ener7_ds)
print("heur_rare")
advers = adversarial_split(ener7_ds)
print("advs")
loc = loc_split(ener7_ds)
print("loc")
semantic = semantic_cluster_split(ener7_ds)
print("semantic")
reverse = reverse_curriculum_split(ener7_ds)
print("reverse")

heur_len
heur_rare
Selecionando 2347 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  48 selecionadas…
  73 selecionadas…
  96 selecionadas…
  119 selecionadas…
  138 selecionadas…
  158 selecionadas…
  177 selecionadas…
  197 selecionadas…
  215 selecionadas…
  232 selecionadas…
  247 selecionadas…
  260 selecionadas…
  285 selecionadas…
  309 selecionadas…
  331 selecionadas…
  354 selecionadas…
  374 selecionadas…
  393 selecionadas…
  413 selecionadas…
  436 selecionadas…
  453 selecionadas…
  469 selecionadas…
  486 selecionadas…
  506 selecionadas…
  524 selecionadas…
  546 selecionadas…
  561 selecionadas…
  571 selecionadas…
  586 selecionadas…
  603 selecionadas…
  613 selecionadas…
  625 selecionadas…
  643 selecionadas…
  666 selecionadas…
  690 selecionadas…
  710 selecionadas…
  733 selecionadas…
  757 selecionadas…
  781 selecionadas…
  799 selecionadas…
  818 selecionadas…
  839 selecionadas…
  856 selecionadas…
  876 selecionadas…
  898 selecionadas…
  913 selecionadas…
  937 selecionadas…
  955 selecionadas…
  972 selecionadas…
  990 selecionadas…
  1009 selecionadas…
  1026 selecionadas…
  1043 selecionadas…
  1063 selecionadas…
  1081 selecionadas…
  1096 selecionadas…
  1119 selecionadas…
  1140 selecionadas…
  1158 selecionadas…
  1176 selecionadas…
  1188 selecionadas…
  1199 selecionadas…
  1214 selecionadas…
  1232 selecionadas…
  1253 selecionadas…
  1275 selecionadas…
  1289 selecionadas…
  1302 selecionadas…
  1315 selecionadas…
  1327 selecionadas…
  1349 selecionadas…
  1365 selecionadas…
  1383 selecionadas…
  1396 selecionadas…
  1407 selecionadas…
  1417 selecionadas…
  1428 selecionadas…
  1438 selecionadas…
  1448 selecionadas…
  1459 selecionadas…
  1469 selecionadas…
  1482 selecionadas…
  1492 selecionadas…
  1507 selecionadas…
  1522 selecionadas…
  1532 selecionadas…
  1538 selecionadas…
  1558 selecionadas…
  1574 selecionadas…
  1590 selecionadas…
  1607 selecionadas…
  1618 selecionadas…
  1628 selecionadas…
  1636 selecionadas…
  1658 selecionadas…
  1671 selecionadas…
  1696 selecionadas…
  1713 selecionadas…
  1729 selecionadas…
  1749 selecionadas…
  1766 selecionadas…
  1781 selecionadas…
  1793 selecionadas…
  1802 selecionadas…
  1818 selecionadas…
  1832 selecionadas…
  1848 selecionadas…
  1861 selecionadas…
  1876 selecionadas…
  1894 selecionadas…
  1908 selecionadas…
  1929 selecionadas…
  1944 selecionadas…
  1967 selecionadas…
  1982 selecionadas…
  1997 selecionadas…
  2011 selecionadas…
  2027 selecionadas…
  2035 selecionadas…
  2050 selecionadas…
  2061 selecionadas…
  2085 selecionadas…
  2101 selecionadas…
  2120 selecionadas…
  2130 selecionadas…
  2151 selecionadas…
  2165 selecionadas…
  2176 selecionadas…
  2189 selecionadas…
  2199 selecionadas…
  2210 selecionadas…
  2229 selecionadas…
  2246 selecionadas…
  2265 selecionadas…
  2278 selecionadas…
  2290 selecionadas…
  2300 selecionadas…
  2311 selecionadas…
  2322 selecionadas…
  2336 selecionadas…
  2346 selecionadas…
advs
loc

100%|██████████| 11737/11737 [00:00<00:00, 559326.31it/s]

semantic
reverse

# Experimentos

In [33]:
from sklearn.metrics import f1_score as skl_f1

In [34]:
def train_ner_with_split(
    dataset: Dataset,
    split: str,  # "loc" | "semantic" | "reverse" | func
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    model_ckpt: str = "Davlan/distilbert-base-multilingual-cased-ner-hrl",
    training_args_kwargs: dict | None = None,
    split_kwargs: dict | None = None,
    seed: int = 42,
):
    """
    Treina um modelo de NER usando a estratégia de split desejada.
    Retorna (trainer, métricas_test).
    """
    # 1. Escolhe função de split ------------------------------------------------
    if callable(split):
        split_fn = split
    else:
        _map = {
            "loc"      : loc_split,
            "reverse"  : reverse_curriculum_split,
            "semantic" : semantic_cluster_split,
            "heur_len" : heur_len_split,
            "heur_rare": heur_rare_split,
            "std"      : std_split,
            "advs"     : adversarial_split,
        }
        if split not in _map:
            raise ValueError(f"split='{split}' não reconhecido.")
        split_fn = _map[split]

    split_kwargs = split_kwargs or {}
    ds = split_fn(
        dataset, pct_test=pct_test, pct_val=pct_val, seed=seed, **split_kwargs
    )  # train/val/test

    # 2. Tokenizer e modelo -----------------------------------------------------
    label_list = sorted({l for labels in dataset["ner_tags"] for l in labels})
    label2id = {l: i for i, l in enumerate(label_list)}
    id2label = {i: l for l, i in label2id.items()}

    num_labels = len(label_list)
    tok = AutoTokenizer.from_pretrained(model_ckpt)
    model = AutoModelForTokenClassification.from_pretrained(
        model_ckpt,
        num_labels=num_labels,  # ← adapta o tamanho
        ignore_mismatched_sizes=True,  # ← descarta pesos velhos da head
    )
    model.config.id2label = id2label
    model.config.label2id = label2id

    # 3. Mapeamento label↔id ----------------------------------------------------
    # label_list = sorted(
    #     {l for labels in dataset["ner_tags"] for l in labels if l != "O"}
    # )

    # 4. Tokenização + alinhamento ---------------------------------------------
    # def tok_function(ex):
    #     return tok(
    #         ex["tokens"], is_split_into_words=True, truncation=True, padding=False
    #     )

    # def align_labels(ex):
    #     word_ids = ex.word_ids()
    #     labels = []
    #     for w in word_ids:
    #         if w is None:
    #             labels.append(-100)
    #         else:
    #             labels.append(label2id.get(ex["ner_tags"][w], 0))
    #     ex["labels"] = labels
    #     return ex

    # ds_tok = ds.map(tok_function, batched=True)
    # ds_tok = ds_tok.map(align_labels)

    def tokenize_and_align_labels(examples, label_all_tokens=False):
        tokenized = tok(examples["tokens"], is_split_into_words=True, truncation=True)

        labels_batch = []
        for i, word_labels in enumerate(examples["ner_tags"]):
            word_ids = tokenized.word_ids(batch_index=i)  # <- aqui sim
            label_ids = []
            previous_word_idx = None
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)  # máscara
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[word_labels[word_idx]])
                else:
                    # marca sub-tokens; mude para `label2id[...]`
                    # se quiser repetir label em todos os sub-tokens
                    label_ids.append(
                        label2id[word_labels[word_idx]] if label_all_tokens else -100
                    )
                previous_word_idx = word_idx
            labels_batch.append(label_ids)

        tokenized["labels"] = labels_batch
        return tokenized

    ds_tok = ds.map(
        tokenize_and_align_labels, batched=True, remove_columns=ds["train"].column_names
    )
    # 5. Métrica (seqeval) ------------------------------------------------------
    seqeval = load_metric("seqeval")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)

        sent_preds, sent_labels = [], []   # p/ seqeval
        flat_preds, flat_labels = [], []   # p/ sklearn

        for p_row, l_row in zip(preds, labels):
            p_sent, l_sent = [], []
            for pi, li in zip(p_row, l_row):
                if li != -100:
                    lbl_true = id2label[li]
                    lbl_pred = id2label[pi]
                    p_sent.append(lbl_pred)
                    l_sent.append(lbl_true)
                    flat_preds.append(lbl_pred)
                    flat_labels.append(lbl_true)
            sent_preds.append(p_sent)
            sent_labels.append(l_sent)

        # métricas seqeval (micro F1 = overall_f1)
        seqeval_metrics = seqeval.compute(
            predictions=sent_preds,
            references=sent_labels,
        )

        # métricas sklearn
        f1_micro    = skl_f1(flat_labels, flat_preds, average="micro",    zero_division=0)
        f1_macro    = skl_f1(flat_labels, flat_preds, average="macro",    zero_division=0)
        f1_weighted = skl_f1(flat_labels, flat_preds, average="weighted", zero_division=0)

        return {
            **seqeval_metrics,            # overall_precision / recall / f1
            "f1_micro":    f1_micro,
            "f1_macro":    f1_macro,
            "f1_weighted": f1_weighted,
        }



    # 6. Args de treinamento ----------------------------------------------------
    args_defaults = dict(
        output_dir=f"ner-{split}",
        # estratégia de avaliação + salvamento
        eval_strategy="epoch",  # novo nome (4.52+)
        save_strategy="no",
        #load_best_model_at_end=True,
        metric_for_best_model="overall_f1",
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=5,
        seed=seed,
        report_to="none"
    )

    if training_args_kwargs:
        args_defaults.update(training_args_kwargs)
    args = TrainingArguments(**args_defaults)

    data_collator = DataCollatorForTokenClassification(tokenizer=tok, padding=True)

    # 7. Trainer ---------------------------------------------------------------
    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=ds_tok["train"],
        eval_dataset=ds_tok["val"],
        tokenizer=tok,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    # 8. Avaliação final --------------------------------------------------------
    test_metrics = trainer.evaluate(eval_dataset=ds_tok["test"])
    return trainer, test_metrics

In [35]:
splits = ["loc", "reverse", "semantic", "heur_len", "heur_rare",  "advs"]

In [36]:
results = {}
trainer_all = {}
s = splits[0]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: loc

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8217/8217 [00:01<00:00, 5761.75 examples/s]
Map: 100%|██████████| 1173/1173 [00:00<00:00, 8781.38 examples/s]
Map: 100%|██████████| 2347/2347 [00:00<00:00, 14769.98 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.5516181902604662
F1 Micro: 0.9849938928633746
F1 Weighted: 0.9843055874075716
{'eval_loss': 0.07563649863004684, 'eval_BUSINESS': {'precision': 0.8432835820895522, 'recall': 0.8625954198473282, 'f1': 0.8528301886792453, 'number': 655}, 'eval_COURT': {'precision': 0.6666666666666666, 'recall': 0.6666666666666666, 'f1': 0.6666666666666666, 'number': 6}, 'eval_GOVERNMENT': {'precision': 0.7142857142857143, 'recall': 0.813953488372093, 'f1': 0.7608695652173914, 'number': 43}, 'eval_LEGISLATION/ACT': {'precision': 0.7916666666666666, 'recall': 0.6551724137931034, 'f1': 0.7169811320754716, 'number': 29}, 'eval_LOCATION': {'precision': 0.738255033557047, 'recall': 0.9166666666666666, 'f1': 0.8178438661710038, 'number': 120}, 'eval_MISCELLANEOUS': {'precision': 0.681592039800995, 'recall': 0.6171171171171171, 'f1': 0.6477541371158393, 'number': 222}, 'eval_PERSON': {'precision': 0.8389261744966443, 'recall': 0.8223684210526315, 'f1': 0.8305647840531561, 'number': 152}, 'eval_overall_precision': 0.7972756410256411, 'eval_overall_recall': 0.810920945395273, 'eval_overall_f1': 0.8040404040404041, 'eval_overall_accuracy': 0.9849938928633746, 'eval_f1_micro': 0.9849938928633746, 'eval_f1_macro': 0.5516181902604662, 'eval_f1_weighted': 0.9843055874075716, 'eval_runtime': 7.217, 'eval_samples_per_second': 325.203, 'eval_steps_per_second': 20.368, 'epoch': 5.0}

20

In [37]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [38]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [39]:
results = {}
trainer_all = {}
s = splits[1]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: reverse

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8217/8217 [00:00<00:00, 10616.63 examples/s]
Map: 100%|██████████| 1173/1173 [00:00<00:00, 7248.61 examples/s]
Map: 100%|██████████| 2347/2347 [00:00<00:00, 5050.47 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.32995920117345445
F1 Micro: 0.9372475320242801
F1 Weighted: 0.9251809212317753
{'eval_loss': 0.49873021245002747, 'eval_BUSINESS': {'precision': 0.538021978021978, 'recall': 0.5373134328358209, 'f1': 0.5376674719964859, 'number': 2278}, 'eval_COURT': {'precision': 0.3333333333333333, 'recall': 0.10714285714285714, 'f1': 0.16216216216216214, 'number': 28}, 'eval_GOVERNMENT': {'precision': 0.9436619718309859, 'recall': 0.31678486997635935, 'f1': 0.4743362831858407, 'number': 423}, 'eval_LEGISLATION/ACT': {'precision': 0.382051282051282, 'recall': 0.40877914951989025, 'f1': 0.3949635520212061, 'number': 729}, 'eval_LOCATION': {'precision': 0.7048951048951049, 'recall': 0.628428927680798, 'f1': 0.6644693473961766, 'number': 802}, 'eval_MISCELLANEOUS': {'precision': 0.596078431372549, 'recall': 0.37163814180929094, 'f1': 0.4578313253012048, 'number': 818}, 'eval_PERSON': {'precision': 0.7931818181818182, 'recall': 0.6763565891472868, 'f1': 0.7301255230125523, 'number': 516}, 'eval_overall_precision': 0.5781153767193594, 'eval_overall_recall': 0.5033964962459778, 'eval_overall_f1': 0.5381748686096511, 'eval_overall_accuracy': 0.9372475320242801, 'eval_f1_micro': 0.9372475320242801, 'eval_f1_macro': 0.32995920117345445, 'eval_f1_weighted': 0.9251809212317753, 'eval_runtime': 30.0828, 'eval_samples_per_second': 78.018, 'eval_steps_per_second': 4.887, 'epoch': 5.0}

20

In [40]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [41]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [42]:
results = {}
trainer_all = {}
s = splits[2]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: semantic

100%|██████████| 11737/11737 [00:00<00:00, 1445857.20it/s]
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8166/8166 [00:01<00:00, 7629.82 examples/s]
Map: 100%|██████████| 1222/1222 [00:00<00:00, 8525.62 examples/s]
Map: 100%|██████████| 2349/2349 [00:00<00:00, 11661.84 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.7334672943155827
F1 Micro: 0.9865994774169466
F1 Weighted: 0.9862825518658914
{'eval_loss': 0.08066357672214508, 'eval_BUSINESS': {'precision': 0.8543388429752066, 'recall': 0.8882921589688507, 'f1': 0.8709847288046341, 'number': 931}, 'eval_COURT': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 6}, 'eval_GOVERNMENT': {'precision': 0.6274509803921569, 'recall': 0.6037735849056604, 'f1': 0.6153846153846154, 'number': 53}, 'eval_LEGISLATION/ACT': {'precision': 0.8222222222222222, 'recall': 0.9673202614379085, 'f1': 0.8888888888888888, 'number': 153}, 'eval_LOCATION': {'precision': 0.7871485943775101, 'recall': 0.9560975609756097, 'f1': 0.8634361233480177, 'number': 205}, 'eval_MISCELLANEOUS': {'precision': 0.7052238805970149, 'recall': 0.7132075471698113, 'f1': 0.7091932457786115, 'number': 265}, 'eval_PERSON': {'precision': 0.8095238095238095, 'recall': 0.7870370370370371, 'f1': 0.7981220657276996, 'number': 108}, 'eval_overall_precision': 0.8117131910235359, 'eval_overall_recall': 0.8617083091226031, 'eval_overall_f1': 0.8359639233370914, 'eval_overall_accuracy': 0.9865994774169466, 'eval_f1_micro': 0.9865994774169466, 'eval_f1_macro': 0.7334672943155827, 'eval_f1_weighted': 0.9862825518658914, 'eval_runtime': 9.0583, 'eval_samples_per_second': 259.32, 'eval_steps_per_second': 16.228, 'epoch': 5.0}

20

In [43]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [44]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [45]:
results = {}
trainer_all = {}
s = splits[3]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_len

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8217/8217 [00:01<00:00, 8118.18 examples/s]
Map: 100%|██████████| 1173/1173 [00:00<00:00, 8489.76 examples/s]
Map: 100%|██████████| 2347/2347 [00:00<00:00, 8298.63 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.7209232782530307
F1 Micro: 0.9953287908419387
F1 Weighted: 0.995285337316602
{'eval_loss': 0.021206628531217575, 'eval_BUSINESS': {'precision': 0.9172056921086675, 'recall': 0.9453333333333334, 'f1': 0.9310571240971767, 'number': 750}, 'eval_COURT': {'precision': 0.6, 'recall': 1.0, 'f1': 0.7499999999999999, 'number': 3}, 'eval_GOVERNMENT': {'precision': 0.8220338983050848, 'recall': 0.9065420560747663, 'f1': 0.8622222222222222, 'number': 107}, 'eval_LEGISLATION/ACT': {'precision': 0.9314516129032258, 'recall': 0.9203187250996016, 'f1': 0.9258517034068137, 'number': 251}, 'eval_LOCATION': {'precision': 0.91, 'recall': 0.9381443298969072, 'f1': 0.9238578680203046, 'number': 194}, 'eval_MISCELLANEOUS': {'precision': 0.8223684210526315, 'recall': 0.8223684210526315, 'f1': 0.8223684210526315, 'number': 304}, 'eval_PERSON': {'precision': 0.9888888888888889, 'recall': 0.956989247311828, 'f1': 0.9726775956284154, 'number': 93}, 'eval_overall_precision': 0.8981588032220944, 'eval_overall_recall': 0.9171562867215041, 'eval_overall_f1': 0.9075581395348837, 'eval_overall_accuracy': 0.9953287908419387, 'eval_f1_micro': 0.9953287908419387, 'eval_f1_macro': 0.7209232782530307, 'eval_f1_weighted': 0.995285337316602, 'eval_runtime': 17.3514, 'eval_samples_per_second': 135.263, 'eval_steps_per_second': 8.472, 'epoch': 5.0}

20

In [46]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [47]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [48]:
results = {}
trainer_all = {}
s = splits[4]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: heur_rare

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8217/8217 [00:00<00:00, 8749.16 examples/s]
Map: 100%|██████████| 1173/1173 [00:00<00:00, 8622.31 examples/s]
Map: 100%|██████████| 2347/2347 [00:00<00:00, 7138.91 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

F1 Macro: 0.5142577194317072
F1 Micro: 0.9868813867636831
F1 Weighted: 0.9864644856189444
{'eval_loss': 0.06744734942913055, 'eval_BUSINESS': {'precision': 0.8041666666666667, 'recall': 0.8717253839205059, 'f1': 0.8365843086259211, 'number': 1107}, 'eval_COURT': {'precision': 0.8888888888888888, 'recall': 0.8888888888888888, 'f1': 0.8888888888888888, 'number': 9}, 'eval_GOVERNMENT': {'precision': 0.8796992481203008, 'recall': 0.8297872340425532, 'f1': 0.854014598540146, 'number': 141}, 'eval_LEGISLATION/ACT': {'precision': 0.8609865470852018, 'recall': 0.8687782805429864, 'f1': 0.8648648648648648, 'number': 221}, 'eval_LOCATION': {'precision': 0.8363095238095238, 'recall': 0.8438438438438438, 'f1': 0.8400597907324365, 'number': 333}, 'eval_MISCELLANEOUS': {'precision': 0.6994106090373281, 'recall': 0.7021696252465484, 'f1': 0.7007874015748032, 'number': 507}, 'eval_PERSON': {'precision': 0.9246231155778895, 'recall': 0.92, 'f1': 0.9223057644110277, 'number': 200}, 'eval_overall_precision': 0.8060559601379839, 'eval_overall_recall': 0.835186656076251, 'eval_overall_f1': 0.8203627852545348, 'eval_overall_accuracy': 0.9868813867636831, 'eval_f1_micro': 0.9868813867636831, 'eval_f1_macro': 0.5142577194317072, 'eval_f1_weighted': 0.9864644856189444, 'eval_runtime': 21.4706, 'eval_samples_per_second': 109.312, 'eval_steps_per_second': 6.847, 'epoch': 5.0}

20

In [49]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [50]:
del results, trainer_all, trainer, metrics

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

In [51]:
results = {}
trainer_all = {}
s = splits[5]
print(f"Treinando com split: {s}")
trainer, metrics = train_ner_with_split(ener7_ds, split=s)
results[s] = metrics
trainer_all[s] = trainer
print("F1 Macro:", metrics["eval_f1_macro"])
print("F1 Micro:", metrics["eval_f1_micro"])
print("F1 Weighted:", metrics["eval_f1_weighted"])
print(metrics)
print("\n")
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# --- limpa GPU e coleta lixo -------------
torch.cuda.empty_cache()  # devolve memória à GPU
gc.collect()

Treinando com split: advs
Selecionando 2347 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  48 selecionadas…
  73 selecionadas…
  96 selecionadas…
  119 selecionadas…
  138 selecionadas…
  158 selecionadas…
  177 selecionadas…
  197 selecionadas…
  215 selecionadas…
  232 selecionadas…
  247 selecionadas…
  260 selecionadas…
  285 selecionadas…
  309 selecionadas…
  331 selecionadas…
  354 selecionadas…
  374 selecionadas…
  393 selecionadas…
  413 selecionadas…
  436 selecionadas…
  453 selecionadas…
  469 selecionadas…
  486 selecionadas…
  506 selecionadas…
  524 selecionadas…
  546 selecionadas…
  561 selecionadas…
  571 selecionadas…
  586 selecionadas…
  603 selecionadas…
  613 selecionadas…
  625 selecionadas…
  643 selecionadas…
  666 selecionadas…
  690 selecionadas…
  710 selecionadas…
  733 selecionadas…
  757 selecionadas…
  781 selecionadas…
  799 selecionadas…
  818 selecionadas…
  839 selecionadas…
  856 selecionadas…
  876 selecionadas…
  898 selecionadas…
  913 selecionadas…
  937 selecionadas…
  955 selecionadas…
  972 selecionadas…
  990 selecionadas…
  1009 selecionadas…
  1026 selecionadas…
  1043 selecionadas…
  1063 selecionadas…
  1081 selecionadas…
  1096 selecionadas…
  1119 selecionadas…
  1140 selecionadas…
  1158 selecionadas…
  1176 selecionadas…
  1188 selecionadas…
  1199 selecionadas…
  1214 selecionadas…
  1232 selecionadas…
  1253 selecionadas…
  1275 selecionadas…
  1289 selecionadas…
  1302 selecionadas…
  1315 selecionadas…
  1327 selecionadas…
  1349 selecionadas…
  1365 selecionadas…
  1383 selecionadas…
  1396 selecionadas…
  1407 selecionadas…
  1417 selecionadas…
  1428 selecionadas…
  1438 selecionadas…
  1448 selecionadas…
  1459 selecionadas…
  1469 selecionadas…
  1482 selecionadas…
  1492 selecionadas…
  1507 selecionadas…
  1522 selecionadas…
  1532 selecionadas…
  1538 selecionadas…
  1558 selecionadas…
  1574 selecionadas…
  1590 selecionadas…
  1607 selecionadas…
  1618 selecionadas…
  1628 selecionadas…
  1636 selecionadas…
  1658 selecionadas…
  1671 selecionadas…
  1696 selecionadas…
  1713 selecionadas…
  1729 selecionadas…
  1749 selecionadas…
  1766 selecionadas…
  1781 selecionadas…
  1793 selecionadas…
  1802 selecionadas…
  1818 selecionadas…
  1832 selecionadas…
  1848 selecionadas…
  1861 selecionadas…
  1876 selecionadas…
  1894 selecionadas…
  1908 selecionadas…
  1929 selecionadas…
  1944 selecionadas…
  1967 selecionadas…
  1982 selecionadas…
  1997 selecionadas…
  2011 selecionadas…
  2027 selecionadas…
  2035 selecionadas…
  2050 selecionadas…
  2061 selecionadas…
  2085 selecionadas…
  2101 selecionadas…
  2120 selecionadas…
  2130 selecionadas…
  2151 selecionadas…
  2165 selecionadas…
  2176 selecionadas…
  2189 selecionadas…
  2199 selecionadas…
  2210 selecionadas…
  2229 selecionadas…
  2246 selecionadas…
  2265 selecionadas…
  2278 selecionadas…
  2290 selecionadas…
  2300 selecionadas…
  2311 selecionadas…
  2322 selecionadas…
  2336 selecionadas…
  2346 selecionadas…

Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at Davlan/distilbert-base-multilingual-cased-ner-hrl and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([9]) in the checkpoint and torch.Size([14]) in the model instantiated
- classifier.weight: found shape torch.Size([9, 768]) in the checkpoint and torch.Size([14, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████| 8216/8216 [00:00<00:00, 8977.16 examples/s]
Map: 100%|██████████| 1173/1173 [00:00<00:00, 8682.00 examples/s]
Map: 100%|██████████| 2348/2348 [00:00<00:00, 6684.10 examples/s]
C:\Users\user\AppData\Local\Temp\ipykernel_10204\17258847.py:170: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

c:\Users\user\miniconda3\envs\lora-gpu\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

F1 Macro: 0.709947166077603
F1 Micro: 0.995116487014965
F1 Weighted: 0.9948871235907478
{'eval_loss': 0.03629439324140549, 'eval_BUSINESS': {'precision': 0.8502304147465438, 'recall': 0.8482758620689655, 'f1': 0.849252013808976, 'number': 435}, 'eval_COURT': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2}, 'eval_GOVERNMENT': {'precision': 0.8932038834951457, 'recall': 0.9292929292929293, 'f1': 0.9108910891089108, 'number': 99}, 'eval_LEGISLATION/ACT': {'precision': 0.9551282051282052, 'recall': 0.952076677316294, 'f1': 0.9536, 'number': 313}, 'eval_LOCATION': {'precision': 0.9020979020979021, 'recall': 0.9148936170212766, 'f1': 0.9084507042253521, 'number': 141}, 'eval_MISCELLANEOUS': {'precision': 0.7871287128712872, 'recall': 0.7429906542056075, 'f1': 0.764423076923077, 'number': 214}, 'eval_PERSON': {'precision': 0.9387755102040817, 'recall': 0.9928057553956835, 'f1': 0.965034965034965, 'number': 139}, 'eval_overall_precision': 0.883668903803132, 'eval_overall_recall': 0.8823529411764706, 'eval_overall_f1': 0.88301043219076, 'eval_overall_accuracy': 0.995116487014965, 'eval_f1_micro': 0.995116487014965, 'eval_f1_macro': 0.709947166077603, 'eval_f1_weighted': 0.9948871235907478, 'eval_runtime': 18.3491, 'eval_samples_per_second': 127.962, 'eval_steps_per_second': 8.011, 'epoch': 5.0}

20

In [52]:
ner_collector.record(split_name=s, metrics=metrics, extras={"gpu":"0"})

In [53]:
df = ner_collector.to_dataframes()

In [54]:
df

(       split  eval_loss  overall_precision  overall_recall  overall_f1  \
 0        loc   0.075636           0.797276        0.810921    0.804040
 1    reverse   0.498730           0.578115        0.503396    0.538175
 2   semantic   0.080664           0.811713        0.861708    0.835964
 3   heur_len   0.021207           0.898159        0.917156    0.907558
 4  heur_rare   0.067447           0.806056        0.835187    0.820363
 5       advs   0.036294           0.883669        0.882353    0.883010

    overall_accuracy  f1_micro  f1_macro  f1_weighted  runtime_s  \
 0          0.984994  0.984994  0.551618     0.984306     7.2170
 1          0.937248  0.937248  0.329959     0.925181    30.0828
 2          0.986599  0.986599  0.733467     0.986283     9.0583
 3          0.995329  0.995329  0.720923     0.995285    17.3514
 4          0.986881  0.986881  0.514258     0.986464    21.4706
 5          0.995116  0.995116  0.709947     0.994887    18.3491

    samples_per_sec  steps_per_sec  epoch
 0          325.203         20.368    5.0
 1           78.018          4.887    5.0
 2          259.320         16.228    5.0
 3          135.263          8.472    5.0
 4          109.312          6.847    5.0
 5          127.962          8.011    5.0  ,
         split            label  precision    recall        f1  support
 0         loc         BUSINESS   0.843284  0.862595  0.852830      655
 1         loc            COURT   0.666667  0.666667  0.666667        6
 2         loc       GOVERNMENT   0.714286  0.813953  0.760870       43
 3         loc  LEGISLATION/ACT   0.791667  0.655172  0.716981       29
 4         loc         LOCATION   0.738255  0.916667  0.817844      120
 5         loc    MISCELLANEOUS   0.681592  0.617117  0.647754      222
 6         loc           PERSON   0.838926  0.822368  0.830565      152
 7     reverse         BUSINESS   0.538022  0.537313  0.537667     2278
 8     reverse            COURT   0.333333  0.107143  0.162162       28
 9     reverse       GOVERNMENT   0.943662  0.316785  0.474336      423
 10    reverse  LEGISLATION/ACT   0.382051  0.408779  0.394964      729
 11    reverse         LOCATION   0.704895  0.628429  0.664469      802
 12    reverse    MISCELLANEOUS   0.596078  0.371638  0.457831      818
 13    reverse           PERSON   0.793182  0.676357  0.730126      516
 14   semantic         BUSINESS   0.854339  0.888292  0.870985      931
 15   semantic            COURT   1.000000  1.000000  1.000000        6
 16   semantic       GOVERNMENT   0.627451  0.603774  0.615385       53
 17   semantic  LEGISLATION/ACT   0.822222  0.967320  0.888889      153
 18   semantic         LOCATION   0.787149  0.956098  0.863436      205
 19   semantic    MISCELLANEOUS   0.705224  0.713208  0.709193      265
 20   semantic           PERSON   0.809524  0.787037  0.798122      108
 21   heur_len         BUSINESS   0.917206  0.945333  0.931057      750
 22   heur_len            COURT   0.600000  1.000000  0.750000        3
 23   heur_len       GOVERNMENT   0.822034  0.906542  0.862222      107
 24   heur_len  LEGISLATION/ACT   0.931452  0.920319  0.925852      251
 25   heur_len         LOCATION   0.910000  0.938144  0.923858      194
 26   heur_len    MISCELLANEOUS   0.822368  0.822368  0.822368      304
 27   heur_len           PERSON   0.988889  0.956989  0.972678       93
 28  heur_rare         BUSINESS   0.804167  0.871725  0.836584     1107
 29  heur_rare            COURT   0.888889  0.888889  0.888889        9
 30  heur_rare       GOVERNMENT   0.879699  0.829787  0.854015      141
 31  heur_rare  LEGISLATION/ACT   0.860987  0.868778  0.864865      221
 32  heur_rare         LOCATION   0.836310  0.843844  0.840060      333
 33  heur_rare    MISCELLANEOUS   0.699411  0.702170  0.700787      507
 34  heur_rare           PERSON   0.924623  0.920000  0.922306      200
 35       advs         BUSINESS   0.850230  0.848276  0.849252      435
 36       advs            COURT   0.000000  0.000000  0.000000        2
 37       advs       GOVERNMENT   0.893204  0.929293  0.910891       99
 38       advs  LEGISLATION/ACT   0.955128  0.952077  0.953600      313
 39       advs         LOCATION   0.902098  0.914894  0.908451      141
 40       advs    MISCELLANEOUS   0.787129  0.742991  0.764423      214
 41       advs           PERSON   0.938776  0.992806  0.965035      139)

In [55]:
nome_modelo = MODEL_NAME.split("/")[1]

In [56]:
ner_collector.to_csv(base_name=nome_modelo)

('albertina-base_overall_metrics.csv', 'albertina-base_label_metrics.csv')