In [315]:

from urllib import request, error
from typing import List, Dict, Any, Iterable, Tuple, Optional

from pathlib import Path
import json, random, itertools, os, gc, statistics as st
import seqeval
import openai
import re
import requests

import numpy as np
import pandas as pd
from datasets import Dataset, DatasetDict
from sklearn.model_selection import KFold, train_test_split
from collections import Counter
from sentence_transformers import SentenceTransformer
from sklearn.neighbors import BallTree
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from sklearn.cluster import KMeans
from dotenv import load_dotenv
from IPython.display import clear_output

import torch
from transformers import (
    AutoTokenizer,
        AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)

from seqeval.metrics import classification_report, f1_score, precision_score, recall_score, accuracy_score
from seqeval.scheme import IOB2
from evaluate import load as load_metric
from tqdm.auto import tqdm

In [2]:
HOST = "http://127.0.0.1:11434"

# >>> Escolha um que REALMENTE está instalado (copie/cole da sua /api/tags):
MODEL_KEY = "deepseek-r1:14b"
# Alternativas que você tem: "qwen2.5:14b-instruct", "deepseek-r1:14b"

# Catálogo só para opções (não interfere no nome/tag do modelo)
OLLAMA_MODELS = {
    "qwen2.5:14b-instruct": {"options": {"num_ctx": 12000, "temperature": 0.2}},
    "llama3.1:8b":          {"options": {"num_ctx": 8000,  "temperature": 0.2}},
    "deepseek-r1:14b":      {"options": {"num_ctx": 8000,  "temperature": 0.2}},
}

In [3]:
OLLAMA_MODELS[MODEL_KEY]["options"].update({
    "temperature": 0.0,
    "repeat_penalty": 1.1,
})

In [4]:
JSON_PATH = "../data/geocorpus-v2.json"        # ajuste se estiver noutra pasta
SEED_GLOBAL = 42
FEW_SHOT_K = 20

random.seed(SEED_GLOBAL)
np.random.seed(SEED_GLOBAL)

# ---------- ler o arquivo ----------
with open(JSON_PATH, encoding="utf-8") as f:
    raw = json.load(f)

In [5]:
records_geo = [
    {
        "sentence_id": i,
        "tokens"     : item["tokens"],
        "ner_tags"   : item["ner_tokens"],
    }
    for i, item in enumerate(raw)
]

geocorpus_full = Dataset.from_list(records_geo)

In [6]:
# lista de rótulos (ordem alfabética garante consistência entre runs)
label_list = sorted({l for sent in geocorpus_full["ner_tags"] for l in sent})
label2id   = {l: i for i, l in enumerate(label_list)}
id2label   = {i: l for l, i in label2id.items()}
NUM_LABELS = len(label_list)

In [7]:
iob_labels = (
    "O "
    "B-baciaSedimentar I-baciaSedimentar "
    "B-epoca I-epoca "
    "B-idade I-idade "
    "B-periodo I-periodo "
    "B-eon I-eon "
    "B-era I-era "
    "B-magmaticas I-magmaticas "
    "B-metamorficas I-metamorficas "
    "B-sedimentaresSiliciclasticas I-sedimentaresSiliciclasticas "
    "B-sedimentaresCarbonaticas I-sedimentaresCarbonaticas "
    "B-unidadeEstratigrafica I-unidadeEstratigrafica "
    "B-contextoGeologicoDeBacia I-contextoGeologicoDeBacia "
    "B-ambienteSedimentacao I-ambienteSedimentacao "
    "B-constituinteRochaSedimentar I-constituinteRochaSedimentar "
    "B-fosseis I-fosseis "
    "B-planctonico I-planctonico "
    "B-bentonico I-bentonico "
    "B-mineral I-mineral "
    "B-procedimentoMetodologico I-procedimentoMetodologico"
)

# Splits

In [8]:
def random_splits(
    ds: Dataset, test_size=0.2, seeds: List[int] = range(30)
) -> List[DatasetDict]:
    triples = []
    for s in seeds:
        train, dev = ds.train_test_split(test_size=test_size, seed=s).values()
        triples.append(DatasetDict(train=train, dev=dev))
    return triples

In [9]:
# def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
#     lengths = np.array([len(t) for t in ds["tokens"]])
#     thr = np.percentile(lengths, 100 * (1 - top_pct))
#     mask = lengths >= thr
#     return DatasetDict(train=ds.filter(~mask), dev=ds.filter(mask))


def split_heur_length(ds: Dataset, top_pct: float = 0.20) -> DatasetDict:
    """20 % das sentenças mais longas viram conjunto de validação (dev)."""
    lengths = np.array([len(t) for t in ds["tokens"]])
    thr = np.percentile(lengths, 100 * (1 - top_pct))  
    mask = lengths >= thr  

    dev_idx = np.where(mask)[0].tolist()  # índices → list[int]
    train_idx = np.where(~mask)[0].tolist()

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Tamanho da sentenças


# def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
#     freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
#     rare = {w for w, c in freq.items() if c <= freq_thr}

#     def has_rare(example):
#         return any(w.lower() in rare for w in example["tokens"])

#     return DatasetDict(
#         train=ds.filter(lambda ex: not has_rare(ex)), dev=ds.filter(has_rare)
#     )


def split_heur_rare(ds: Dataset, freq_thr: int = 5) -> DatasetDict:
    freq = Counter(w.lower() for sent in ds["tokens"] for w in sent)
    rare = {w for w, c in freq.items() if c <= freq_thr}

    keep_dev = []
    for sent in ds["tokens"]:
        print(sent)
        keep_dev.append(any(w.lower() in rare for w in sent))

    dev_idx = [i for i, x in enumerate(keep_dev) if x]
    train_idx = [i for i, x in enumerate(keep_dev) if not x]

    return DatasetDict(
        train=ds.select(train_idx),
        dev=ds.select(dev_idx),
    )

    # Raridade dos tokens

In [10]:
def split_adversarial(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    embeds = model.encode([" ".join(t) for t in ds["tokens"]], show_progress_bar=False)
    tree = BallTree(embeds, leaf_size=40)

    idx_train, idx_test = set(range(len(ds))), []
    # semente = ponto mais central
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    idx_train.remove(seed_idx)
    idx_test.append(seed_idx)
    print(k)
    while len(idx_test) < k:
        print(len(idx_test))
        dists, _ = tree.query(embeds[list(idx_train)], k=1, return_distance=True)
        nxt = list(idx_train)[int(np.argmax(dists))]
        idx_train.remove(nxt)
        idx_test.append(nxt)

    return DatasetDict(
        train=ds.select(sorted(idx_train)),
        dev=ds.select(sorted(idx_test)),
    )

    # Maximizando Wassertein Distance


def split_adversarial_fast(ds: Dataset, pct_test: float = 0.20) -> DatasetDict:
    """
    Farthest-Point Sampling aproximando Wasserstein – versão vetorizada.
    Seleciona pct_test (~20 %) das sentenças como conjunto 'dev'.
    """
    k = int(len(ds) * pct_test)
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    embeds = model.encode(
        [" ".join(t) for t in ds["tokens"]],
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,  # acelera distância euclidiana ≈ cos
    )

    n = embeds.shape[0]
    idx_all = np.arange(n)

    # 1) ponto mais "central" (norma mais distante da média)
    seed_idx = np.argmax(np.linalg.norm(embeds - embeds.mean(0), axis=1))
    selected = [seed_idx]

    # 2) vetor de distâncias mínimas a qualquer ponto já escolhido
    min_dists = np.linalg.norm(embeds - embeds[seed_idx], axis=1)

    while len(selected) < k:
        next_idx = np.argmax(min_dists)
        selected.append(next_idx)

        # atualiza min_dists com a distância ao novo ponto — tudo de uma vez
        d_new = np.linalg.norm(embeds - embeds[next_idx], axis=1)
        min_dists = np.minimum(min_dists, d_new)

    train_idx = np.setdiff1d(idx_all, selected, assume_unique=True)

    return DatasetDict(
        train=ds.select(train_idx.tolist()),
        dev=ds.select(selected),
    )

In [11]:
# def loc_split(
#     dataset: Dataset, pct_test: float = 0.20, ngram: int = 4, seed: int = 42
# ) -> DatasetDict:
#     """
#     Split baseado em baixa sobreposição léxica (4-gram Jaccard).
#     Teste = pct_test das sentenças com menor overlap em relação ao pool.
#     """
#     # 1. Texto plano por sentença
#     docs = [" ".join(toks) for toks in dataset["tokens"]]

#     # 2. Vetorizar 4-grams (binário)
#     vect = CountVectorizer(
#         analyzer="word", ngram_range=(ngram, ngram), binary=True
#     ).fit(docs)
#     X = vect.transform(docs)

#     # 3. Similaridade Jaccard aproximada com matriz binária
#     # Jaccard(A,B) = |A∩B|/|A∪B| = 1 - |AΔB|/|A∪B|
#     # Usamos: overlap = (A·Bᵀ) / (|A|+|B|-A·Bᵀ)
#     bin_counts = X.sum(axis=1).A1

#     # Para cada doc i, escolhemos vizinho + próximo (fast):
#     from sklearn.metrics.pairwise import cosine_similarity

#     # (cosine no binário ∝ |A∩B|)
#     sim = cosine_similarity(X, dense_output=False)
#     # Soma dos top-k overlaps (k=5) como score
#     k = 5
#     topk = np.zeros(len(dataset))
#     for i in range(sim.shape[0]):
#         row = sim.getrow(i).toarray()[0]
#         idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
#         # overlap ≈ |∩|
#         inter = row[idx] * bin_counts[i]
#         uni = bin_counts[i] + bin_counts[idx] - inter
#         topk[i] = (inter / uni).mean()

#     # 4. Ordenar por overlap crescente ⇒ mais “novos” vão p/ teste
#     order = np.argsort(topk)
#     n_test = int(len(dataset) * pct_test)
#     test_idx = order[:n_test]
#     train_idx = order[n_test:]

#     return DatasetDict(
#         {"train": dataset.select(train_idx), "test": dataset.select(test_idx)}
#     )

In [12]:
def loc_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    ngram: int = 4,
    seed: int = 42,
) -> DatasetDict:
    """
    Divide por sobreposição léxica (n-gram Jaccard).
    Frações independentes para teste e validação.
    """
    docs = [" ".join(toks) for toks in dataset["tokens"]]

    vect = CountVectorizer(
        analyzer="word", ngram_range=(ngram, ngram), binary=True
    ).fit(docs)
    X = vect.transform(docs)
    bin_counts = X.sum(axis=1).A1

    sim = cosine_similarity(X, dense_output=False)
    k = 5
    topk = np.zeros(len(dataset))
    for i in range(sim.shape[0]):
        row = sim.getrow(i).toarray()[0]
        idx = np.argpartition(-row, range(1, k + 1))[1 : k + 1]
        inter = row[idx] * bin_counts[i]
        uni = bin_counts[i] + bin_counts[idx] - inter
        topk[i] = (inter / uni).mean()

    order = np.argsort(topk)  # baixo → alto overlap
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[:n_test]
    val_idx = order[n_test : n_test + n_val]
    train_idx = order[n_test + n_val :]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [13]:
def semantic_cluster_split(
    dataset: Dataset,
    pct_test: float = 0.20,
    pct_val: float = 0.10,
    k: int | None = None,
    seed: int = 42,
) -> DatasetDict:
    """
    Clusters SBERT → reserva clusters distantes para test/val.
    """
    if k is None:
        k = int(np.sqrt(len(dataset)))

    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    embeddings = sbert.encode(
        [" ".join(t) for t in tqdm(dataset["tokens"])],
        batch_size=64,
        show_progress_bar=False,
    )

    km = KMeans(n_clusters=k, random_state=seed, n_init=10).fit(embeddings)
    labels = km.labels_
    centroids = km.cluster_centers_

    global_center = embeddings.mean(0, keepdims=True)
    dists = pairwise_distances(centroids, global_center).flatten()

    clusters_sorted = np.argsort(-dists)  # mais distantes primeiro
    test_clusters, val_clusters = set(), set()
    total_test = total_val = 0
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    for c in clusters_sorted:
        size = np.sum(labels == c)
        if total_test < n_test:  # preenche primeiro o teste
            test_clusters.add(c)
            total_test += size
        elif total_val < n_val:  # depois a validação
            val_clusters.add(c)
            total_val += size
        if total_test >= n_test and total_val >= n_val:
            break

    test_idx = np.where([lbl in test_clusters for lbl in labels])[0]
    val_idx = np.where([lbl in val_clusters for lbl in labels])[0]
    train_idx = np.where(
        [lbl not in test_clusters and lbl not in val_clusters for lbl in labels]
    )[0]

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [14]:
def difficulty_scores(dataset: Dataset) -> np.ndarray:
    length = np.array([len(tok) for tok in dataset["tokens"]], dtype=float)
    length = (length - length.mean()) / length.std()

    dens = []
    for labels in dataset["ner_tags"]:
        non_o = sum(1 for l in labels if l != "O")
        dens.append(non_o / len(labels))
    dens = np.array(dens)
    dens = (dens - dens.mean()) / dens.std()

    ent_types, freq = [], Counter()
    for labels in dataset["ner_tags"]:
        types = [l[2:] for l in labels if l != "O"]
        ent_types.append(types[0] if types else "NONE")
    freq.update(ent_types)
    rarity = np.array([1 / freq[t] for t in ent_types])
    rarity = (rarity - rarity.mean()) / rarity.std()

    return length + dens + rarity


def reverse_curriculum_split(
    dataset: Dataset, pct_test: float = 0.20, pct_val: float = 0.10, seed: int = 42
) -> DatasetDict:
    scores = difficulty_scores(dataset)
    order = np.argsort(scores)  # easy→hard
    n_test = int(len(dataset) * pct_test)
    n_val = int(len(dataset) * pct_val)

    test_idx = order[-n_test:]  # hardest
    val_idx = order[-(n_test + n_val) : -n_test]
    train_idx = order[: -(n_test + n_val)]

    rng = np.random.RandomState(seed)
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    rng.shuffle(test_idx)

    return DatasetDict(
        {
            "train": dataset.select(train_idx),
            "val": dataset.select(val_idx),
            "test": dataset.select(test_idx),
        }
    )

In [15]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42) -> DatasetDict:
    """Testa só sentenças ≥ máx(len_train)."""
    sent_lens = np.array([len(t) for t in dataset["tokens"]])
    # separação inicial train/dev (randômica estratificando por tamanho grosso)
    idx_all   = np.arange(len(dataset))
    train_idx, temp_idx = train_test_split(idx_all,
                                           test_size=pct_test + pct_val,
                                           stratify=(sent_lens//5),  # bin len
                                           random_state=seed)
    # define longo-threshold como tamanho máx. do treino
    max_train_len = sent_lens[train_idx].max()
    # test = sentenças > threshold.  Caso falte/ sobre exemplos, ajusta.
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]
    # completa ou reduz para atingir pct_test
    need = int(pct_test*len(dataset)) - len(test_idx)
    if need > 0:
        test_idx.extend(resto_idx[:need])
        val_idx = resto_idx[need:]
    else:
        val_keep = int(pct_val*len(dataset))
        val_idx  = resto_idx[:val_keep]
        test_idx = test_idx[: int(pct_test*len(dataset))]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 2) Heuristic Rare-Words ----------------------------------
def heur_rare_split(dataset: Dataset,
                    pct_test: float = 0.20,
                    pct_val : float = 0.10,
                    seed: int = 42) -> DatasetDict:
    """Testa frases que contenham palavras do quintil + raro."""
    # contagem de frequência de token
    freqs = Counter(w for toks in dataset["tokens"] for w in toks)
    # define rareza: 20 % mais raras
    thresh = np.quantile(list(freqs.values()), 0.20)
    rare_set = {w for w,c in freqs.items() if c <= thresh}
    is_rare = np.array([any(w in rare_set for w in toks)
                        for toks in dataset["tokens"]])
    rare_idx   = np.where(is_rare)[0]
    common_idx = np.where(~is_rare)[0]
    # garante proporções desejadas
    n_test = int(pct_test*len(dataset))
    n_val  = int(pct_val *len(dataset))
    rng = np.random.default_rng(seed)
    test_idx = rng.choice(rare_idx, size=min(len(rare_idx), n_test),
                          replace=False)
    resto_idx = [i for i in rare_idx if i not in test_idx] + list(common_idx)
    val_idx  = rng.choice(resto_idx, size=n_val, replace=False)
    train_idx = [i for i in resto_idx if i not in val_idx]
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 3) Standard (80-10-10) -----------------------------------
def std_split(dataset: Dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42) -> DatasetDict:
    """Split aleatório estratificado por comprimento (PTB-like)."""
    idx = np.arange(len(dataset))
    strat = (np.array([len(t) for t in dataset["tokens"]]) // 5)
    train_idx, temp_idx = train_test_split(idx, test_size=pct_test+pct_val,
                                          stratify=strat, random_state=seed)
    val_rel = pct_val / (pct_test+pct_val)
    val_idx, test_idx = train_test_split(temp_idx, test_size=1-val_rel,
                                         stratify=strat[temp_idx],
                                         random_state=seed)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

# ---------- 4) Adversarial (approx. Wasserstein) ---------------------
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Seleciona k frases 'mais distantes' recursivamente (BallTree + W₂)
    para compor o teste, lembrando Alg.-1 de Søgaard et al.【turn6file4】.
    """
    # SBERT embed (rápido na GPU / aceitável CPU)
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(toks) for toks in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    # BallTree para vizinhança eficiente
    tree = BallTree(emb, leaf_size=40)
    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)
    while len(test_idx) < int(pct_test*len(dataset)):
        # amostra candidata: ponto + longe do centro
        center = emb[list(idx_pool)].mean(0, keepdims=True)
        dists, _ = tree.query(center, k=len(idx_pool))
        farthest = list(idx_pool)[int(dists.argmax())]
        # pega-se farest e seus k-NN mais próximos  ⇒ aumenta diversidade
        nn = tree.query([emb[farthest]], k=k, return_distance=False)[0]
        for j in nn:
            if j in idx_pool and len(test_idx) < int(pct_test*len(dataset)):
                test_idx.append(j)
                idx_pool.remove(j)
    # retira val
    val_size = int(pct_val*len(dataset))
    val_idx  = rng.choice(list(idx_pool), size=val_size, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)
    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [16]:
def heur_len_split(dataset: Dataset,
                   pct_test: float = 0.20,
                   pct_val : float = 0.10,
                   seed: int = 42,
                   bin_size: int = 10) -> DatasetDict:
    """
    Teste = sentenças mais longas que max(len(train)).
    Robusto a datasets pequenos: se estratificação falhar, usa split aleatório.
    """
    rng = np.random.default_rng(seed)
    idx_all   = np.arange(len(dataset))
    sent_lens = np.array([len(t) for t in dataset["tokens"]])

    # ------ 1) tenta split estratificado por baldes -------------------------
    strat = (sent_lens // bin_size)
    try:
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            stratify=strat,
            random_state=seed,
        )
    except ValueError:                       # classes com 1 amostra
        train_idx, temp_idx = train_test_split(
            idx_all,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # ------ 2) escolhe test = len > max(train) ------------------------------
    max_train_len = sent_lens[train_idx].max()
    test_idx  = [i for i in temp_idx if sent_lens[i] > max_train_len]
    resto_idx = [i for i in temp_idx if i not in test_idx]

    # garante tamanhos exatos
    n_test_desired = int(pct_test * len(dataset))
    n_val_desired  = int(pct_val  * len(dataset))

    # completa teste se ficou pequeno
    if len(test_idx) < n_test_desired:
        extra = rng.choice(resto_idx,
                           size=n_test_desired - len(test_idx),
                           replace=False)
        test_idx.extend(extra)
        resto_idx = [i for i in resto_idx if i not in extra]

    # define validação
    val_idx  = rng.choice(resto_idx, size=n_val_desired, replace=False)
    train_idx = [i for i in idx_all if i not in test_idx and i not in val_idx]

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [17]:
def std_split(dataset,
              pct_test: float = 0.10,
              pct_val : float = 0.10,
              seed: int = 42,
              bin_size: int = 5) -> DatasetDict:
    """
    Split 80-10-10 robusto.
      • Tenta estratificar por comprimento // bin_size.
      • Se houver classes com <2 amostras, recua p/ split aleatório.
    """
    idx  = np.arange(len(dataset))
    bins = (np.array([len(t) for t in dataset["tokens"]]) // bin_size)

    try:
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            stratify=bins,
            random_state=seed,
        )
    except ValueError:                       # classes muito pequenas
        train_idx, temp_idx = train_test_split(
            idx,
            test_size=pct_test + pct_val,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    # fraciona temp em val / test mantendo proporção desejada
    val_share = pct_val / (pct_test + pct_val)
    try:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            stratify=bins[temp_idx],
            random_state=seed,
        )
    except ValueError:
        val_idx, test_idx = train_test_split(
            temp_idx,
            test_size=1 - val_share,
            shuffle=True,
            random_state=seed,
            stratify=None,
        )

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [18]:
def adversarial_split(dataset: Dataset,
                      pct_test: float = 0.20,
                      pct_val : float = 0.10,
                      k: int = 5,
                      seed: int = 42) -> DatasetDict:
    """
    Versão robusta: nunca “trava” antes de atingir n_test.
    Seleciona blocos de k sentenças mais distantes do centro iterativamente.
    """
    # -------------------------------- embeds -------------------------------
    sbert = SentenceTransformer(
        "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    )
    emb = sbert.encode([" ".join(t) for t in dataset["tokens"]],
                       batch_size=64, show_progress_bar=False)
    tree = BallTree(emb, leaf_size=40)

    n_test = int(pct_test * len(dataset))
    n_val  = int(pct_val  * len(dataset))

    idx_pool = set(range(len(dataset)))
    test_idx = []
    rng = np.random.default_rng(seed)

    print(f"Selecionando {n_test} sentenças para teste…")
    step = 0
    while len(test_idx) < n_test and idx_pool:
        if step % 5 == 0:
            print(f"  {len(test_idx)} selecionadas…")
        step += 1

        pool_list = list(idx_pool)
        center = emb[pool_list].mean(0, keepdims=True)

        # distância euclidiana ao centro global restante
        dists, _ = tree.query(center, k=len(pool_list))
        farthest_local_idx = int(dists.argmax())
        farthest_global_idx = pool_list[farthest_local_idx]

        # número efetivo de vizinhos
        k_eff = min(k, len(idx_pool))
        nn = set(tree.query([emb[farthest_global_idx]],
                            k=k_eff,
                            return_distance=False)[0])

        # adiciona vizinhos ainda não selecionados
        for j in nn:
            if j in idx_pool and len(test_idx) < n_test:
                test_idx.append(j)
                idx_pool.remove(j)

        # Se nada foi adicionado (pode acontecer quando sobram <k únicos)
        if farthest_global_idx not in test_idx:
            test_idx.append(farthest_global_idx)
            idx_pool.remove(farthest_global_idx)

    # ------------------------ validação e treino ---------------------------
    val_idx = rng.choice(list(idx_pool), size=n_val, replace=False)
    idx_pool -= set(val_idx)
    train_idx = list(idx_pool)

    return DatasetDict({
        "train": dataset.select(train_idx),
        "val"  : dataset.select(val_idx),
        "test" : dataset.select(test_idx),
    })

In [19]:
standard_split = std_split(geocorpus_full)
print('std')
# random_splt = random_splits(geocorpus_full)
# print('random')
heur_len = heur_len_split(geocorpus_full)
print("heur_len")
heur_rare = heur_rare_split(geocorpus_full)
print("heur_rare")
advers = adversarial_split(geocorpus_full)
print("advs")
loc = loc_split(geocorpus_full)
print("loc")
semantic = semantic_cluster_split(geocorpus_full)
print("semantic")
reverse = reverse_curriculum_split(geocorpus_full)
print("reverse")

std
heur_len
heur_rare
Selecionando 1054 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  47 selecionadas…
  71 selecionadas…
  96 selecionadas…
  121 selecionadas…
  144 selecionadas…
  165 selecionadas…
  187 selecionadas…
  211 selecionadas…
  232 selecionadas…
  251 selecionadas…
  271 selecionadas…
  288 selecionadas…
  305 selecionadas…
  329 selecionadas…
  349 selecionadas…
  364 selecionadas…
  383 selecionadas…
  399 selecionadas…
  417 selecionadas…
  433 selecionadas…
  452 selecionadas…
  470 selecionadas…
  488 selecionadas…
  501 selecionadas…
  515 selecionadas…
  529 selecionadas…
  542 selecionadas…
  554 selecionadas…
  565 selecionadas…
  577 selecionadas…
  590 selecionadas…
  597 selecionadas…
  610 selecionadas…
  628 selecionadas…
  642 selecionadas…
  658 selecionadas…
  671 selecionadas…
  685 selecionadas…
  698 selecionadas…
  713 selecionadas…
  724 selecionadas…
  738 selecionadas…
  754 selecionadas…
  771 selecionadas…
  785 selecionadas…
  798 selecionadas…
  817 selecionadas…
  830 selecionadas…
  844 selecionadas…
  856 selecionadas…
  868 selecionadas…
  884 selecionadas…
  894 selecionadas…
  901 selecionadas…
  916 selecionadas…
  936 selecionadas…
  951 selecionadas…
  963 selecionadas…
  976 selecionadas…
  986 selecionadas…
  998 selecionadas…
  1015 selecionadas…
  1032 selecionadas…
  1047 selecionadas…
advs
loc

100%|██████████| 5272/5272 [00:00<00:00, 1199672.89it/s]

semantic
reverse

# Pipeline Ollama

In [20]:
def tokens_to_text(tokens: List[str]) -> str:
    # Junta preservando espaços simples.
    return " ".join(tokens)


def fmt_example(ex: dict) -> str:
    toks = ex["tokens"]
    tags = ex.get("tags") or ex.get("ner_tags")  # compatível com seus dsets
    pairs_line = " ".join(f"{i+1}-{t}" for i, t in enumerate(tags))
    return f"Tokens: {' '.join(toks)}\nSaída: {pairs_line}"

def build_prompt(few_shot: List[Dict[str, Any]], query_tokens: List[str]) -> str:
    N = len(query_tokens)
    header = f"""
        Você é um anotador especialista em NER. Rotule **cada token** usando o esquema **IOB2**.

        Regras (case-sensitive):
        1) Use apenas os rótulos:\n{iob_labels}

        2) IOB2 (cheque silenciosamente):
        • Uma entidade inicia em B-<TIPO>.
        • I-<TIPO> só após B-<TIPO> ou I-<TIPO> do mesmo TIPO.
        • Nunca iniciar com I-.

        3) Formato ÚNICO de saída (sem texto extra):
        • Uma única linha com N pares índice-rótulo (1-based), separados por espaço.
        • Cada par: <índice>-<RÓTULO>.
        • Ex.: 1-O 2-B-magmaticas 3-I-magmaticas ... N-O

        4) Se houver N tokens, produza exatamente N rótulos.
        """.strip()

    examples = "\n\n### Exemplos\n" + "\n\n".join(fmt_example(ex) for ex in few_shot)

    task = f"""
        ### Tarefa
        Tokens: {tokens_to_text(query_tokens)}

        ### Saída esperada
        Retorne **apenas**: {{"tags": ["O", "B-...", "..."]}} com {N} itens.
        """.strip()

    return f"{header}\n\n{examples}\n\n{task}"

In [21]:
def select_few_shot(exemplars: Dataset, k=FEW_SHOT_K) -> list[dict]:
    # amostra k exemplos aleatórios (pode trocar por stratified sampling)
    return random.sample(list(exemplars), k)

In [22]:
def ollama_generate(
    model: str,
    prompt: str,
    options: Optional[Dict[str, Any]] = None,
    host: str = "http://localhost:11434",
    timeout: int = 120,
    stream: bool = False,
) -> str:
    """
    Wrapper do endpoint /api/generate.
    """
    url = f"{host}/api/generate"
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": stream,
        "options": options or {},
        # "stop": ["\n\n"],  # ajuste opcional se algum modelo insistir em linhas extras
    }
    # Timeout levemente alto pois alguns modelos podem demorar.
    resp = requests.post(url, json=payload, timeout=timeout)
    resp.raise_for_status()

    if stream:
        # Se usar stream=True, agregamos as linhas 'data: {...}'
        text = ""
        for line in resp.iter_lines():
            if not line:
                continue
            try:
                obj = json.loads(line.decode("utf-8"))
            except Exception:
                continue
            text += obj.get("response", "")
        return text
    else:
        data = resp.json()
        return data.get("response", "")

In [23]:
def predict_labels_ollama(few_shot, query_tokens, model_key=MODEL_KEY, host=HOST):
    cfg = OLLAMA_MODELS[model_key]
    prompt = build_prompt(few_shot, query_tokens)
    print(prompt)
    raw = ollama_generate(model=model_key, prompt=prompt, options=cfg.get("options"), host=host, stream=False)
    return raw

In [24]:
SESSION = requests.Session()

In [25]:
def ollama_generate_json(model: str, prompt: str, host="http://127.0.0.1:11434",
                         num_predict:int=64, num_ctx:int=2048, timeout=(10, 600)):
    payload = {
        "model": model,
        "prompt": prompt,
        "format": "json",     # resposta vem como string JSON em data['response']
        "stream": False,      # evita travar se o cliente não consumir stream
        "keep_alive": "30m",
        "options": {
            "temperature": 0,
            "seed": 42,
            "num_ctx": num_ctx*30,
            "num_predict": max(64, 5 * num_predict)
        }
    }
    return SESSION.post(f"{host}/api/generate", json=payload, timeout=timeout)

In [26]:
import time

In [27]:
def predict_labels_ollama(tokens: List[str],
                          few_shot_text: str = "",
                          model: str = "llama3.1:8b") -> List[str]:
    # prompt curto e objetivo; evite few-shots gigantes (cole 1–2 exemplos no few_shot_text)
    
    N = len(tokens)
    prompt = build_prompt(few_shot_text, tokens)
    # retry leve para 5xx/timeout
    for attempt in range(3):
        try:
            r = ollama_generate_json(
                model=model,
                prompt=prompt,
                # use o número de tokens como base para calcular num_predict interno
                num_predict=min(64, 3 * len(tokens)),
                num_ctx=N
            )
            r.raise_for_status()
            data = r.json()
            attempt = 3
            return data['response']
        except Exception:
            if attempt == 2:
                raise
            time.sleep(1.5 * (attempt + 1))

# Prompts

In [28]:
# few_shot = [
#     {"tokens": ["o", "maj", "é", "composto"], "tags": ["O","O","O","O"]},
#     {"tokens": ["dioritos", "e", "monzodioritos"], "tags": ["B-magmaticas","O","I-magmaticas"]},
# ]
# query_tokens = ["o","maj","é","composto","por","monzodioritos","."]
# preds = predict_labels_ollama(few_shot, query_tokens)  # usa MODEL_KEY
# preds

In [29]:
standard_split = std_split(geocorpus_full)
print('std')
# random_splt = random_splits(geocorpus_full)
# print('random')
heur_len = heur_len_split(geocorpus_full)
print("heur_len")
heur_rare = heur_rare_split(geocorpus_full)
print("heur_rare")
advers = adversarial_split(geocorpus_full)
print("advs")
loc = loc_split(geocorpus_full)
print("loc")
semantic = semantic_cluster_split(geocorpus_full)
print("semantic")
reverse = reverse_curriculum_split(geocorpus_full)
print("reverse")

std
heur_len
heur_rare
Selecionando 1054 sentenças para teste…
  0 selecionadas…
  24 selecionadas…
  47 selecionadas…
  71 selecionadas…
  96 selecionadas…
  121 selecionadas…
  144 selecionadas…
  165 selecionadas…
  187 selecionadas…
  211 selecionadas…
  232 selecionadas…
  251 selecionadas…
  271 selecionadas…
  288 selecionadas…
  305 selecionadas…
  329 selecionadas…
  349 selecionadas…
  364 selecionadas…
  383 selecionadas…
  399 selecionadas…
  417 selecionadas…
  433 selecionadas…
  452 selecionadas…
  470 selecionadas…
  488 selecionadas…
  501 selecionadas…
  515 selecionadas…
  529 selecionadas…
  542 selecionadas…
  554 selecionadas…
  565 selecionadas…
  577 selecionadas…
  590 selecionadas…
  597 selecionadas…
  610 selecionadas…
  628 selecionadas…
  642 selecionadas…
  658 selecionadas…
  671 selecionadas…
  685 selecionadas…
  698 selecionadas…
  713 selecionadas…
  724 selecionadas…
  738 selecionadas…
  754 selecionadas…
  771 selecionadas…
  785 selecionadas…
  798 selecionadas…
  817 selecionadas…
  830 selecionadas…
  844 selecionadas…
  856 selecionadas…
  868 selecionadas…
  884 selecionadas…
  894 selecionadas…
  901 selecionadas…
  916 selecionadas…
  936 selecionadas…
  951 selecionadas…
  963 selecionadas…
  976 selecionadas…
  986 selecionadas…
  998 selecionadas…
  1015 selecionadas…
  1032 selecionadas…
  1047 selecionadas…
advs
loc

100%|██████████| 5272/5272 [00:00<00:00, 1252754.56it/s]

semantic
reverse

In [284]:
splits = [standard_split, heur_len, heur_rare, advers]

In [285]:
splits_names = ['standard', 'heur_len', 'heur_rare', 'adversarial']

In [309]:
model_escolhido = 'llama3.1:8b'  # ou 'vicuna-13b-v1.5:8b', etc.

In [ ]:
golds, predictions = {}, {}
for split, nome in zip(splits, splits_names):
    split_base = split
    
    #max_len_split = len(split_base["test"])
    max_len_split = 500
    random.seed(SEED_GLOBAL)
    realizado = 0
    few_shot = select_few_shot(split_base["train"], FEW_SHOT_K)
    total = 500 #len(split_base['test'])
    golds[nome] = []
    predictions[nome] = []
    for ex in split_base['test'].select(range(500)):

        print('---', nome, '---')
        pred_tags = predict_labels_ollama(ex["tokens"], few_shot_text=few_shot, model=model_escolhido)
        golds[nome].append([ex["ner_tags"]])
        predictions[nome].append([pred_tags])


        realizado += 1
        clear_output(wait=True)
        print(f'Total de exemplos processados: {realizado/total*100:.2f}%')

Total de exemplos processados: 100.00%

In [316]:
report = {}
f1_macro = {}
precision = {}
recall = {}
metrics_all = {}

bads_sets = {}

for name, predidction in predictions.items():
    preds = []
    print(predidction)
    for tags_prediction in predidction:
        try:
            preds.append(json.loads(tags_prediction)['tags']) 
        except:
            try:
                preds.append(json.loads(tags_prediction[0])['tags']) 
            except:
                try:
                    preds.append(json.loads(tags_prediction[0][0])['tags']) 
                except:
                    preds.append(['O'])
          
    new_preds = []
    for pred_token in preds:
        if type(pred_token) == str:
            new_preds.append(pred_token)
        else:
            tokens_ajustados = []  
            for token in pred_token:
                try:
                    if int(_).is_integer():
                        tokens_ajustados.extend([token_ajustado])
                    else:
                        tokens_ajustados.extend([token])
                except:
                    try:
                        token_ajustado = token['tag']
                        tokens_ajustados.extend([token_ajustado])
                    except:
                        token_ajustado = token
                        tokens_ajustados.extend([token_ajustado])
            new_preds.append(tokens_ajustados)

        
    if type(golds[name][0][0]) == list:
        actual_golds = [gold[0] for gold in golds[name]]
        print('ok')
    else:
        actual_golds = golds[name]
    actual_preds = new_preds
    print(new_preds)
    # clean_golds, cleaned, clean_preds = [], [], []

    # for i, (g, p) in enumerate(zip(actual_golds, actual_preds)):
    #     if type(g[0][0]) == list:
    #         g_ = g[0]
    #         print(len(g_), len(p))
    #         if len(p) < len(g_):
    #             print('limpou preds'); print(i)
    #             cleaned.append(i)
    #             continue  # pula a adição
    #         elif len(p) > len(g_):
    #             print('limpou golds'); print(i)
    #             cleaned.append(i)
    #             continue  # pula a adição
    #     else:
    #         print(len(g), len(p))
    #         if len(p) < len(g):
    #             print('limpou preds'); print(i)
    #             cleaned.append(i)
    #             continue  # pula a adição
    #         elif len(p) > len(g):
    #             print('limpou golds'); print(i)
    #             cleaned.append(i)
    #             continue  # pula a adição

    clean_golds, clean_preds = [], []
    for g, p in zip(actual_golds, actual_preds):
        # se o modelo gerar menos/more tags que tokens, ajustamos:
        if type(g[0][0]) == list:
            g_ = g[0]
            if len(p) < len(g_):
                print('limpou preds')
                p = p + ["O"] * (len(g_) - len(p))          # completa com O
            elif len(p) > len(g_):
                print('limpou golds')
                p = p[:len(g_)]                             # descarta excedente
            clean_golds.append(g_)
            clean_preds.append(p)
        else:
            if len(p) < len(g):
                print('limpou preds')
                p = p + ["O"] * (len(g) - len(p))          # completa com O
            elif len(p) > len(g):
                print('limpou golds')
                p = p[:len(g)]                             # descarta excedente
            clean_golds.append(g)
            clean_preds.append(p)

    # bad = set(cleaned)

    # bads_sets[name] = bad

    # clean_golds[:] = [g for i, g in enumerate(actual_golds) if i not in bad]
    # clean_preds[:] = [p for i, p in enumerate(actual_preds) if i not in bad]

    print(f"{name}: {len(clean_golds)} exemplos válidos ({len(bad)} removidos)")
    print(clean_golds, len(clean_golds))
    print(clean_preds, len(clean_preds))
    if len(clean_golds) != 0 and len(clean_preds) != 0:
        report[name] = classification_report(clean_golds, clean_preds, output_dict=True)
        f1_macro[name] = f1_score(clean_golds, clean_preds, average="macro")
        precision[name] = precision_score(clean_golds, clean_preds, average="macro")
        recall[name] = recall_score(clean_golds, clean_preds, average="macro")
        rep = classification_report(clean_golds, clean_preds, scheme=IOB2, zero_division=0, output_dict=True)

        metrics = {
            "precision_micro":   rep["micro avg"]["precision"],
            "recall_micro":      rep["micro avg"]["recall"],
            "f1_micro":          rep["micro avg"]["f1-score"],
            "precision_macro":   rep["macro avg"]["precision"],
            "recall_macro":      rep["macro avg"]["recall"],
            "f1_macro":          rep["macro avg"]["f1-score"],
            "precision_weighted":rep["weighted avg"]["precision"],
            "recall_weighted":   rep["weighted avg"]["recall"],
            "f1_weighted":       rep["weighted avg"]["f1-score"],
            "accuracy":          accuracy_score(clean_golds, clean_preds),
        }

        metrics_all[name] = metrics

[['{"tags": ["O", "B-ambienteSedimentacao", "sedimentos", "quartzosos", "em", "bacias", "tafrogênicas", "depositados", "em", "ambientes", "continentais", "ambientes", "fluvial", "e", "eólico", "passaram", "a", "ter", "grande", "importância", "na", "história", "da", "terra", "durante", "o", "paleomesoproterozoico"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSilicic'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-estratigia", "I-estratigia", "O", "B-aspecto bacteriologico", "O", "B-analises bacteriológicas", "O", "B-coliformes fecais", "O", "B-poços tubulares", "O", "B-porcentagem de coliformes fecais"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-eon", "proterozoico", "fanerozoico", "evidente", "relativamente", "curto", "proliferaram", "desenvolveram", "animais", "plantas", "pluricelulares"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-bacteriológico", "O"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O'], ['{\n    "tags": [\n        "O",\n        "B-estratigrafia",\n        "I-estratigrafia",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O"\n    ]\n}'], ['{"tags": ["O", "B-NOUN", "I-NOUN", "O", "B-VERB"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-..."]}'], ['{"tags": ["O", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigraf'], ['{"tags": ["O", "B-fácies", "de", "calcários", "argilosos", "lc", "a", "fácies", "lc", "constitui-se", "de", "camadas", "de", "calcários", "argilosos", "calcíticos", "normalmente", "maciços", "formando", "crostas", "duros", "calcretes", "abundentemente", "fossilíferos"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia"]}'], ['{"tags": ["O", "B-estratigrafia", "B-periodo", "B-sedimentaresSiliciclasticas", "B-ambienteSedimentacao", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "O", "O", "O", "B-estratigrafia", "I-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-TAG", "I-TAG", "O", "B-TAG"]}'], ['{\n    "tags": [\n        "1-O",\n        "2-O",\n        "3-O",\n        "4-O",\n        "5-O",\n        "6-O",\n        "7-O",\n        "8-O",\n        "9-O"\n    ]\n}'], ['{\n    "tags": [\n        "O",\n        "B-estratigrafia",\n        "I-estratigrafia",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "B-estratigrafia"\n    ]\n}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-tectonoEstratigráfica", "O", "B-evoluçãoTectonoEstratigráfica", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-principaisDaEvoluçãoTectonoEstratigráfica", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-causasPrincipaisDaEvoluçãoTectonoEstratigráfica", "O", "B-evoluçãoTectonoEstratigráficaDaSeçãoEstudada", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-evoluçãoTectonoEstratigráficaDaSeçãoEstudada", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-evoluçãoTectonoEstratigráfica'], ['{"tags": ["O", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas",'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-métodos", "O", "B-detectores", "O", "B-de-bordas", "O", "B-de-corpos", "O", "B-pouco", "O", "B-influenciado", "O", "B-pela", "O", "B-profundidade", "O", "B-das", "O", "B-fontes"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-aspecto", "O", "B-análises", "O", "B-bacteriológicas", "O", "B-em", "O", "B-águas", "O", "B-de", "O", "B-poços", "O", "B-tubulares", "O", "B-revelaram", "O", "B-que", "O", "B-em", "O", "B-nenhum", "O"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSil'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-clima", "B-ameno", "O", "B-presentando", "O", "B-mediana", "O", "B-elevada", "O", "B-umidade", "O", "B-provavelmente", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia"]}'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentares'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia"]}'], ['{"tags": ["O", "B-idade", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-estratigrafia", "B-metamorficas", "B-sedimentaresSiliciclasticas", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratig'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-metamorficas", "B-idade", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-periodo", "O", "B-idade", "B-idade", "B-idade", "B-estratigrafia", "B-estratigrafia", "B-estratigrafia", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "I-estratigrafia", "O", "B-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-periodo", "O", "B-idade", "O"

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sedimentos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: quartzosos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: bacias seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: tafrogênicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: depositados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ambientes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: continentais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fluvial seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: e seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: eólico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: passaram seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: a seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ter seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: grande seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: importância seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: na seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: história seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: da seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: terra seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: durante seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: o seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleomesoproterozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: proterozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fanerozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: evidente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: relativamente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: curto seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: proliferaram seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: desenvolveram seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: animais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: plantas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pluricelulares seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: calcários seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: argilosos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: lc seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fácies seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: constitui-se seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: camadas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: calcíticos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: normalmente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: maciços seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: formando seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: crostas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: duros seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: calcretes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: abundentemente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fossilíferos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: arenitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: subordinadamente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: caracterizadas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pela seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intercalação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: finos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: siltitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: conglomerados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Puntuação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: é seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: semelhante seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: à seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: monchiquitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ígnea seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: equivalente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: extrusiva seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: monzonito seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: rica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: plagioclases seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: feldespatos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: potássicos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: que seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ocorre seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: formações seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vulcânicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: contendo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: materiais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pobres seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sílica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sedimentaresSiliciclasticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: de arenitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: com estruturas trativas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: indicam que durante o recuo glacial ocorria instalação de sistemas deltaicos mergulho acima seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: as análises bacteriológicas em águas de poços tubulares revelaram que em nenhum poço foi detectada a presença de coliformes fecais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: terrigênicos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: grossos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ruditos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: progradando seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: estrato seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleocênico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cobrindo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: bacia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

[['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon"]}'], ['{"tags": ["1-O", "2-O", "3-O", "4-O", "5-O", "6-O", "7-O", "8-O", "9-O", "10-O", "11-O", "12-O", "13-B-epoca", "14-O"]}'], ['{"tags": ["O", "B-idade", "epoca", "periodo", "era", "eon", "idade", "periodo", "era", "eon", "idade", "periodo", "era", "eon", "idade", "periodo", "era", "eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O",'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "periodo", "era", "eon"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-epoca"]}'], ['{"tags": ["O", "B-camada", "carbonática", "B-periodo", "mais", "seco", "B-idade", "provavelmente", "não", "B-epoca", "exposição", "subaérea", "pois", "indícios", "carstificação", "dissolução"]}'], ['{"tags": ["O", "B-propriedades", "O", "B-modelos", "O", "B-rochas", "O", "B-selantes", "O", "B-feito", "O", "B-trabalhos", "O", "B-Schlömer", "O", "B-Krooss", "O", "B-Schmitt"]}'], ['{"tags": ["O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-epoca"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "idade", "periodo", "era", "eon", "epoca", "O", "B-estrada", "prj", "g", "r", "O", "B-fósseis", "feoopteris", "dolianitii"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-estratigrafia", "O", "B-idade", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-sedimentaresSiliciclasticas", "O", "'], ['{"tags": ["O", "B-idade", "B-epoca", "B-era", "B-eon", "B-região geográfica", "B-topônimo", "B-língua", "B-nome de região geográfica grega", "B-transliteração", "B-correspondente", "B-existente", "B-na", "B-lusa", "O", "B-idade", "B-hirnantiana", "B-rhuddaniana"]}'], ['{"tags": ["O", "B-idade", "um último evento transgressivo pós<ec>", "glacial teve início no final do pleistoceno.", "O", "B-epoca", "a idade rhuddaniana sucede a idade hirnantiana.", "O", "B-periodo", "O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-idade", "O", "B-idade", "O", "B-idade"]}'], ['{"tags": ["O", "B-fácies", "B-fluxo", "B-corrente", "B-leito", "B-médio", "B-porte", "B-unidirecional", "B-producto", "B-formas", "B-arenosas", "B-sob", "B-corrente", "O", "B-fácies", "B-fluxo", "B-trativo", "B-associado", "B-migração", "B-leito", "B-arenosas", "B-de", "B-médio", "B-porte", "B-sob", "B-corrente", "O"]}'], ['{"tags": ["O", "B-idade", "B-periodo", "B-era", "B-eon", "B-estratigrafia", "B-epoca", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade",'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-acumulações", "eólicas", "registradas", "nos", "últimos", "120", "milhões", "de", "anos", "possuem", "gênese", "relacionada", "aos", "ciclos", "climáticos", "de", "diferentes", "ordens", "do", "pleistoceno", "ao", "holoceno", "e", "cuja", "evolução", "do", "espaço", "de", "acumulação", "foi", "ditada", "pelos", "flutuações", "do", "nível", "freático"]}'], ['{"tags": ["O", "B-era", "B-eon", "B-idade", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "B-epoca", "B-periodo", "B-tiempo", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B'], ['{"tags": ["O", "B-epoca", "idade", "rhuddaniana", "sucede", "a", "idade", "hirnantiana"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-era", "O'], ['{\n    "tags": [\n        "1-O",\n        "2-O",\n        "3-O",\n        "4-O",\n        "5-O",\n        "6-O",\n        "7-O",\n        "8-O",\n        "9-O",\n        "10-O",\n        "11-O",\n        "12-O",\n        "13-B-epoca",\n        "14-O",\n        "B-..."\n    ]\n}'], ['{"tags": ["O", "B-superfícies", "aplainadas", "entrecortadas", "por", "vales", "fluviais", "aproximadamente", "perpendiculares", "à", "linha", "de", "costa", "predominam", "tabuleiros", "com", "grandes", "e", "bem", "definidas"] }'], ['{"tags": ["O", "um último evento transgressivo pós<ec> - glacial teve início no final do pleistoceno.", "a idade rhuddaniana sucede a idade hirnantiana.", "esta é a primeira e mais antiga das quatro subdivisões da era da cisuralien."]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-pseudomatriz", "O", "B-material", "argiloso", "silicificado", "O", "B-resultante", "alteração", "compactação", "fragmentos", "vulcânicos", "intra clastos", "pelíticos", "O", "B-ocupado", "material", "abundante", "intergranular", "O", "B-aparentemente", "silicificado", "O", "B-material", "argiloso", "silicificado", "O", "B-resultante", "alteração", "compactação", "fragmentos", "vulcânicos", "intra clastos", "pelíticos"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "periodo", "era", "eon", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era", "O", "B-ec", "O", "B-glacial", "O", "B-evento", "O", "B-transgressivo", "O", "B-pós", "O", "B-final", "O", "B-do"]}'], ['{"tags": ["O", "B-aulacógeno", "do", "paramirim", "correspondem", "à", "expressão", "intracratônica", "das", "sucessivas", "orogenias", "que", "afetaram", "as", "margens", "do", "cráton", "do", "são", "francisco", "ao", "fim", "do", "pré-cambriano"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O"]}'], ['{\n    "tokens": [\n        "a",\n        "parte",\n        "central",\n        "e",\n        "quantitativamente",\n        "mais",\n        "importante",\n        "da",\n        "nebulosa",\n        "deu",\n        "origem",\n        "ao",\n        "sol",\n        "."\n    ],\n    "tags": ["O", "B-...", "..."]\n}'], ['{"tags": ["O", "B-sedimentacao continental", "B-registro de formas exclusivamente não marinhas", "B-conchostráceos e ostracodes", "B-sistemas lacustres favoráveis à formação de camadas de red-beds"]}'], ['{"tags": ["1-O", "2-O", "3-O", "4-O", "5-O", "6-O", "7-O", "8-O", "9-O", "10-O", "11-O", "12-O", "13-B-epoca", "14-O", "15-O"]}'], ['{"tags": ["O", "B-era", "eon", "fanerozoico", "B-eon", "B-idade", "periodo", "B-periodo", "B-epoca", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade",'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade"]}'], ['{\n    "tokens": [\n        "kimberlito",\n        "é",\n        "vulgarmente",\n        "conhecido",\n        "como",\n        "a",\n        "rocha",\n        "que",\n        "contêm",\n        "diamantes"\n    ],\n    "saida_esperada": {\n        "tags": ["O", "B-...", "..."]\n    }\n}'], ['{"tags": ["O", "B-evento", "B-epoca", "B-periodo", "B-eon", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-evento", "O", "B-idade", "B-periodo", "B-eon", "B-idade", "B-periodo", "B-eon", "B-idade", "B-periodo", "B-eon", "B-idade", "B-periodo", "B-eon", "B-evento", "O", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca"]}'], ['{"tags": ["O", "B-epoca", "um último evento transgressivo pós<ec>", "glacial teve início no final do pleistoceno.", "a idade rhuddaniana sucede a idade hirnantiana.", "na escala de tempo geológico, o bajociano é uma idade ou estágio no jurássico médio."]}'], ['{"tags": ["O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "apenas", "2", "-", "3", "ºc", "superior", "à", "<pp>", "actual", "sendo", "que", "o", "clima", "era", "já", "bastante", "semelhante", "ao", "actual"]}'], ['{"tags": ["O", "B-formação", "B-met arenitos", "B-acamamento sedimentar", "B-dobrado em anticlinais e sinclinais", "B-foliação plano-axial", "B-metachert ferrífero", "B-bandado", "B-estratificação plano-paralela", "B-leitos ricos em quartzo com hematita e magnetita", "B-visão geral da parede da pedreira na encosta do morro do agostinho", "B-estruturas em almofadas nos basaltos", "B-detalhe das estruturas em almofada", "B-zonas interalmofadas vítreas de cor verde", "B-foliação incipiente", "B-basalto hipovítreo maciço com esferulitos e pequena venulação de calcita e epídoto"]}'], ['{"tags": ["O", "B-epoca", "O", "B-idade", "O", "B-ec", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-ec", "O", "B-eon", "O"]}'], ['{\n    "tags": [\n        "O",\n        "B-rocha",\n        "ultramáfica",\n        "e",\n        "compacta"\n    ]\n}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "unidade", "litoestratigráfica", "siltitos", "arenitos", "topo", "direção", "aumenta", "intercalações", "métricas", "decimétricas", "finos", "presença", "composto", "por", "laminares"]}'], ['{"tags": ["O", "B-eo", "O", "B-ordoviciano", "O", "B-tal", "como", "hoje", "fazem", "os", "\\"tatuzinhos-de-jardim\\""]}'], ['{"tags": ["O", "B-epoca", "idade", "pleistoceno", "glacial", "teve", "início", "final", "O", "idade", "rhuddaniana", "sucede", "idade", "hirnantiana", "O"]}'], ['{"tags": ["O", "um", "último", "evento", "transgressivo", "pós-", "glacial", "teve", "início", "no", "final", "do", "pleistoceno", "a", "idade", "rhuddaniana", "sucede"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon"]}'], ['{"tags": ["O", "B-rochas", "petrofísicas", "propriedades", "petrofísica", "rocha", "selante", "sistema", "poroso", "geometria", "caracterizar", "trabalho", "desenvolvido", "informação", "relativa", "pouca", "B-epoca", "B-eon", "B-periodo", "B-era", "B-idade"]}'], ['{"tags": ["O", "B-região", "da", "toca", "da", "moura", "é", "comparada", "à", "região", "de", "cabrela,", "onde", "se", "verifica,", "igualmente,", "predomínio", "da", "sedimentação", "terrígena", "fina,", "datada", "do", "viseano", "superior", "baixo,", "associada", "a", "escorregamentos", "gravitacionais", "e", "vulcanismo.", "O", "B-idade", "rhuddaniana", "sucede", "à", "idade", "hirnantiana.", "Um", "último", "evento", "transgressivo", "pós<ec>", "-glacial", "teve", "início", "no", "final", "do", "pleistoceno.", "A", "idade", "rhuddaniana", "sucede", "à", "idade", "hirnantiana.", "Um", "último", "evento", "transgressivo", "pós<ec>", "-glacial", "teve", "início", "no", "final", "do", "pleistoceno.", "A", "idade", "rhuddaniana", "sucede", "à", "idade", "hirnantiana.", "'], ['{"tags": ["O", "B-acritarcos", "O", "B-palinoforaminíferos", "O", "B-ovos de copépodes", "O", "B-miósporos", "O", "B-acritarcos", "O", "B-palinoforaminíferos", "O", "B-ovos de copépodes", "O", "B-miósporos", "O", "B-acritarcos", "O", "B-palinoforaminíferos", "O", "B-ovos de copépodes", "O", "B-miósporos"]}'], ['{"tags": ["O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-idade", "B-epoca", "B-periodo", "B-eon", "B-era", "B-evento", "B-transgressivo", "B-glacial", "B-pós", "B-suítes", "B-graníticas", "B-batólito", "B-pelotas", "B-septos", "B-embasamento"]}'], ['{"tags": ["O", "B-sedimentos", "continentais", "B-fase", "de", "subsidência", "mecânica", "B-no", "topo", "depositados", "em", "fase", "de", "subsidência", "flexural", "B-epoca", "pleistoceno", "B-idade", "rhuddaniana", "sucede", "a", "idade", "hirnantiana", "B-periodo", "pleistoceno", "B-eon", "cambriano", "B-sedimentos", "continentais", "B-fase", "de", "subsidência", "mecânica", "B-no", "topo", "depositados", "em", "fase", "de", "subsidência", "flexural"]}'], ['{"tags": ["O", "B-ramo", "O", "B-autóctone", "O", "B-zona", "O", "B-orogenia", "O", "B-fase", "O", "B-intensidade"]}'], ['{"tags": ["O", "B-idade", "periodo", "era", "eon", "O", "B-periodo", "era", "eon", "O", "B-idade", "periodo", "era", "eon", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era", "O", "B-ec", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-..."]}'], ['{"tags": ["O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era", "O", "B-eon", "O", "B-periodo", "O", "B-idade", "O", "B-epoca", "O", "B-idade", "O", "B-epoca", "O", "B-idade", "O", "B-epoca", "O", "B-eon", "O", "B-periodo", "O", "B-era"]}'], ['{"tags": ["O", "B-evolução", "tectono-estratigráfica", "seção", "estudada", "associação", "curva", "variação", "nível", "mar", "devoniano"]}'], ['{"tags": ["O", "B-idade", "um", "último", "evento", "transgressivo", "pós-glacial", "teve", "início", "no", "final", "do", "pleistoceno", "a", "idade", "rhuddaniana", "sucede", "à", "idade", "hirnantiana"]}'], ['{\n    "tags": [\n        {\n            "tag": "B-LOC",\n            "word": "Paris"\n        },\n        {\n            "tag": "I-ORG",\n            "word": "France"\n        }\n    ]\n}'], ['{"tags": ["O", "B-fácies", "B-modelo", "B-padrão", "B-lógico", "B-empilhamento", "B-sedimentar", "B-associações", "B-fácies", "B-seleção", "B-eon", "B-idade", "B-periodo", "B-era", "B-eon", "B-idade", "B-periodo", "B-era", "B-epoca", "O", "B-idade", "B-periodo", "B-idade", "B-periodo", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-i

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: periodo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: era seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: eon seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 13-B-epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: carbonática seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: seco seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: provavelmente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: não seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: exposição seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: subaérea seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pois seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: indícios seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: carstificação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: dissolução seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: prj seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: r seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: feoopteris seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: dolianitii seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: um último evento transgressivo pós<ec> seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: glacial teve início no final do pleistoceno. seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: a idade rhuddaniana sucede a idade hirnantiana. seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: eólicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: registradas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: últimos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 120 seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: milhões seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: anos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: possuem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: gênese seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: relacionada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ciclos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: climáticos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: diferentes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ordens seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pleistoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ao seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: holoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cuja seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: evolução seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: espaço seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: acumulação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ditada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pelos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: flutuações seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: nível seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: freático seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: rhuddaniana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sucede seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: hirnantiana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aplainadas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: entrecortadas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vales seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fluviais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aproximadamente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: perpendiculares seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: linha seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: costa seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: predominam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: tabuleiros seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: grandes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: bem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: definidas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: um último evento transgressivo pós<ec> - glacial teve início no final do pleistoceno. seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: esta é a primeira e mais antiga das quatro subdivisões da era da cisuralien. seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: argiloso seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: silicificado seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: alteração seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: compactação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fragmentos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vulcânicos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intra clastos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: material seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: abundante seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intergranular seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paramirim seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: correspondem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: expressão seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intracratônica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: das seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sucessivas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: orogenias seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: afetaram seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: margens seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: são seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: francisco seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fim seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pré-cambriano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

[['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-conformidade", "O", "B-orogenia", "O", "B-clivagem", "O", "B-dobras", "O", "B-deformação", "O", "B-associadas", "O", "B-corresponde", "O", "B-existente", "O", "B-discordância", "O", "B-datada", "O", "B-givetiano", "O", "B-pedreira", "O", "B-engenharia", "O", "B-cabrela"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["O", "B-idade", "B-episódio", "B-conformidade", "B-região", "B-sistema", "B-sequência", "B-unidades", "B-tipo", "B-rift", "B-sag", "B-pedreira", "B-deformação", "B-orogenia", "B-varisca", "B-clivagem", "B-dobras", "B-associadas", "B-corresponde", "B-existente", "B-discordância", "B-formações", "B-pedreira", "B-engenharia", "B-cabrela", "B-givetiano", "B-datada", "B-episódio", "B-primeiro"]}'], ['{"tags": ["O", "B-fácies", "fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-fácies", "B-f'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade"]}'], ['{\n    "tokens": [\n        "inferior",\n        "/",\n        "temprano",\n        "b232"\n    ],\n    "tags": [\n        "O",\n        "B-tempo/relacionado",\n        "I-tempo/relacionado",\n        "O"\n    ]\n}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-unidade", "B-idade", "B-concentração", "B-episódio", "B-orogenia", "B-formação", "B-pedreira", "B-engenharia", "B-cabrela", "B-clivagem", "B-dobras", "B-deformação", "B-existente", "O", "B-episódio", "B-orogenia", "B-formação", "B-pedreira", "B-engenharia", "B-cabrela", "B-clivagem", "B-dobras"]}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade"]}'], ['{"tags": ["O", "B-idade", "O", "B-unidade de tempo", "O", "B-episódio", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-orogenia", "O", "B-associadas", "O", "B-existente", "O", "B-corresponde", "O", "B-do", "O", "B-clivagem", "O", "B-datas", "O", "B-givetiano", "O", "B-orogenia", "O", "B-episódio", "O", "B-deformação", "O", "B-da", "O", "B-orogenia", "O", "B-varisca"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["1-O", "2-O", "3-O", "4-O", "5-O", "6-O", "7-O", "8-O", "9-O", "10-O", "11-O", "12-O", "13-O", "14-O", "15-O", "16-O", "17-O"]}'], ['{"tags": ["O", "B-idade", "O", "B-unidade de idade", "O", "B-formação geológica", "O", "B-episódio de deformação", "O", "B-orogenia varisca", "O", "B-dobras e clivagem associadas", "O", "B-givetiano", "O", "B-pedreira de engenharia", "O", "B-cabrela", "O", "B-cretáceo", "O", "B-neocomiana", "O", "B-sucessão ininterrupta", "O", "B-formações de pedreira de engenharia e cabrela"]}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade", "O", "B-idade"]}'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-unidadeEstratigrafica", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["O", "B-idade", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio", "B-episódio"]}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-..."]}'], ['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-conformidade", "O", "B-associadas", "O", "B-orogenia", "O", "B-varisca", "O", "B-clivagem", "O", "B-dobras", "O", "B-deformação", "O", "B-primeiro", "O", "B-corresponde", "O", "B-existente", "O", "B-discordância"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade"]}'], ['{"tags": ["O", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-idade"]}'], ['{"tags": ["O", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-contextoGeologicoDeBacia", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade"]}'], ['{"tags": ["O", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-..."]}'], ['{"tags": ["O", "B-idade", "B-episódio", "B-conformidade", "B-associadas", "B-subordinada", "B-dominante", "B-sienítica", "B-granodiorítica", "B-monzogranítica", "B-a sienogranítica", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "'], ['{"tags": ["B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-contextoGeologicoDeBacia", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "O", "B-contextoGeologicoDeBacia", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "B-idade", "B-epoca", "O", "B-contextoGeologicoDeBacia", "B-idade", "B-epoca", "B-idade", "B-epoca"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["O", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-tectonoestratigraficos", "B-falhas", "B-cisalhamento", "B-transpressivas", "B-terrenos", "B-sintetizam", "O", "B-quadro", "O", "B-geral", "O", "B-conjunto", "O", "B-diversos", "O", "B-terrenos", "O", "B-tectonoestratigraficos", "O", "B-limitados", "O", "B-por", "O", "B-falhas", "O", "B-de", "O", "B-cavalgamento", "O", "B-ou", "O", "B-por", "O", "B-zonas", "O", "B-de", "O", "B-cisalhamento", "O", "B-transpressivas"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-fácies", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade",'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-formação", "O", "B-orogenia", "O", "B-clivagem", "O", "B-dobras", "O", "B-deformação", "O", "B-corresponde", "O", "B-datada", "O", "B-associadas", "O", "B-existe", "O", "B-discordância", "O", "B-cabrela", "O", "B-pedreira", "O", "B-engenharia", "O", "B-givetiano"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade"]}'], ['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-orogenia", "O", "B-clivagem", "O", "B-dobras", "O", "B-deformação", "O", "B-formações", "O", "B-pedreira", "O", "B-engenharia", "O", "B-cabrela", "O", "B-givetiano", "O", "B-episódio", "O", "B-orogenia", "O", "B-varisca"]}'], ['{\n    "tags": [\n        "O",\n        "B-PER",\n        "I-PER"\n    ]\n}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-..."]}'], ['{"tags": ["O", "B-idade", "B-episódio", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade"]}'], ['{"tags": ["O", "B-idade", "O", "B-episódio", "O", "B-orogenia", "O", "B-deformação", "O", "B-clivagem", "O", "B-dobras", "O", "B-associadas", "O", "B-corresponde", "O", "B-primeiro", "O", "B-episódio", "O", "B-orogenia", "O", "B-varisca", "O", "B-datada", "O", "B-givetiano"]}'], ['{"tags": ["O", "B-idade", "O", "B-..."]}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-idade", "O", "B-impactos", "O", "B-problemas", "O", "B-infraestrutura", "O", "B-esgotamento", "O", "B-sanitário", "O", "B-rede", "O", "B-pluvial", "O", "B-ambientais", "O", "B-somam-se", "O", "B-problemas", "O", "B-infraestrutura", "O", "B-esgotamento", "O", "B-sanitário", "O", "B-rede", "O", "B-pluvial"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-epoca", "B-idade", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade",'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca"]}'], ['{"tags": ["O", "B-paleógeno", "O", "B-gastrópodes", "O", "B-bivalves", "O", "B-lulas", "O", "B-ouriços-do-mar", "O", "B-tubarões", "O", "B-peixes ósseos"]}'], ['{"tags": ["O", "B-idade", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-epoca", "O", "B-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "B-idade"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "B-epoca", "B-idade", "B-contextoGeologicoDeBacia", "B-epoca", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", 

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Grego seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: phneros seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: visível seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: zoikos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vida seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: éon geológico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: abrange seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 542 milhões de anos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: tem início seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: era paleozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: surgimento seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vários animais de concha seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: é o éon ao longo do qual a abundância de vida é maior seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: conformidade seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: discordância seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: corresponde seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: primeiro seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: orógeno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: etapa seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sin-colisional seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: caracteriza-se seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: metamorfismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: acompagnada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intensa seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: granitogênese seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: microclásticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: oligocênico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Brasil seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Formação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Tremembé seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Bacia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Taubaté seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: orogenia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: varisca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: dobra seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: clivagem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: associada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: existente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pedreira seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: engenharia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cabrela seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: datada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: givetiano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-formações seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-pedreira seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-engenharia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-cabrela seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-givetiano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-orogenia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-varisca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-deformação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-dobras seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-clivagem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-corresponde seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-existe seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-discordância seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-datada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-episódio seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-primeiro seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: O-eoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: conodontes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: animal seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: bucal seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: este seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: século seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aparato seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: elementos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: conhece seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: chamaram-se seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 22-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 24-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 27-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 28-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 29-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 30-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 31-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 32-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 33-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 34-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 35-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: filito seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sobre seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: granulometria seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fina seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: magmáticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: efusivas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: hipoabissais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ics seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sps seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: enfatizam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

[['{"tags": ["O", "B-idade", "época", "era", "período", "siluriano", "sucede", "precede", "idade", "hirauntiana", "rhuddaniana", "llandovery", "sucedem-se", "epocas", "eram", "periodos", "silurianos", "era", "período", "siluriano", "sucessão", "precedência", "idade", "hirauntiana", "rhuddaniana", "llandovery", "sucedem-se", "epocas", "eram", "periodos", "silurianos"]}'], ['{"tags": ["O", "B-idade", "epoca", "periodo", "era", "eono", "sede", "sedimento", "sedimentares", "carbonatos", "abertura", "oceano", "atlantico", "terciario", "oligoceno", "presenca", "argilas", "quantidade", "continua", "atlantico", "tipos", "litologicos", "rochas", "vulcanicas", "intrusivas", "vulcano-clasticas", "autoclasicas", "piroclasticas", "ultrabasicas", "idades", "radiometricas", "ar-ar", "paleogeno", "paleoceno", "meso-eoceno", "significa", "perigo", "apedeutismo", "população", "mundo", "civilizada", "educada"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-idade", "época", "período", "idade", "época", "período", "idade", "época", "período", "idade", "época", "período", "idade", "época", "período", "idade", "época", "período", "B-idade", "época", "período"]}'], ['{"tags": ["O", "B-epoca", "idade", "triássica", "inferior", "período", "idade", "ladiniana", "época", "idade", "anisiana", "sucede", "idade", "olenekiana", "época", "triássica", "idade", "ladiniana", "época", "idade", "anisiana", "precede", "idade", "olenekiana", "época", "triássica"]}'], ['{"tags": ["O", "B-idade", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-epoca", "B-sistemaPetrolifero", "B-contextoGeologicoDeBacia", "B-sedimentaresSiliciclasticas", "B-idade", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-epoca", "B-sistemaPetrolifero", "B-contextoGeologicoDeBacia", "B-sedimentaresSiliciclasticas", "O", "B-idade", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-epoca", "B-sistemaPetrolifero", "B-contextoGeologicoDeBacia", "B-sedimentaresSiliciclasticas", "O", "B-idade", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-epoca", "B-sistemaPetrolifero", "B-contextoGeologicoDeBacia", "B-sedimentaresSiliciclasticas", "O", "B-idade", "B-periodo'], ['{"tags": ["O", "B-periodo", "O", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresCarbonaticas", "O", "B-sedimentaresCarbonaticas", "O", "B-contextoGeologicoDeBacia", "O", "B-idade", "O", "B-periodo", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-metamorficas", "O", "B-epoca", "O", "B-epoca", "O", "B-idade", "O", "B-periodo", "O", "B-epoca", "O", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresCarbonaticas", "O", "B-contextoGeologicoDeBacia", "O", "B-idade", "O", "B-periodo", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-metamorficas", "O", "B-epoca", "O", "B-epoca", "O", "B-idade'], ['{"tags": ["O", "B-periodo", "O", "B-epoca", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-era", "B-idade", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeologicoDeBacia", "B-metamorficas", "B-epoca", "B-periodo", "B-idade", "B-epoca", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeologicoDeBacia", "B-metamorficas", "B-epoca", "O", "B-era", "B-idade", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeologicoDeBacia", "B-metamorficas", "B-epoca", "O", "B-periodo", "B-idade", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeologicoDeBacia", "B-metamorficas", "B-epoca", "O", "B-era", "B-idade", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeologicoDeBacia", "B-metamorficas", "B-epoca", "O", "B-periodo", "B-idade", "B-granulometria", "B-sedimentaresCarbonaticas", "B-contextoGeolog'], ['{"tags": ["O", "B-periodo", "idade", "epoca", "grande percentagem", "carbonatos", "abertura contínua do oceano atlântico", "rochas vulcânicas", "intrusivas e vulcanoclásticas", "ultrabásicas", "paleogeno", "paleoceno ao meso eoceno", "perigo de apedeutismo", "civilizada", "educada", "datações pelo método k - ar em ilitas diagenéticas dos arenitos da formação juruá", "preenchimento dos reservatórios por petróleo ocorreu no n eotriássico", "remobilização pelo evento do mega cisalhamento do solimões"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-", "O", "B-epoca", "O", "B-", "O", "B-epoca", "O", "B-", "O", "B-epoca", "O", "B-"] }'], ['{"tags": ["O", "B-baciaSedimentar", "I-contextoGeologicoDeBacia", "O", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresCarbonaticas", "O", "B-sedimentaresCarbonaticas", "O", "B-sedimentaresCarbonaticas", "O", "B-contextoGeologicoDeBacia", "I-contextoGeologicoDeBacia", "O", "B-periodo", "O", "B-epoca", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-idade", "O", "B-epoca", "O", "B-epoca", "O", "B-periodo", "O", "B-baciaSedimentar", "I-contextoGeologicoDeBacia", "O", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresCarbonaticas", "O", "B-sedimentaresCarbonaticas", "O", "B-contextoGeologicoDeBacia", "I-contextoGeologicoDeBacia", "O", "B-periodo", "'], ['{"tags": ["O", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-epoca", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-'], ['{"tags": ["O", "B-era", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-..."]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-unidade", "estabeleceria", "o", "desenvolvimento", "do", "primeiro", "sistema", "lacustre", "completo", "da", "bacia", "do", "araripe", "resultando", "na", "deposição", "de", "até", "1", ".", "300", "m", "de", "sedimentos", "pelíticos", "lacustres", "devido", "à", "compactação", "de", "minerais", "de", "argila", "constituintes", "dos", "pelitos"]}'], ['{"tags": ["O", "B-periodo", "epoca", "idade", "metamorficas", "grande", "menor", "abertura", "continua", "oceano", "atlântico", "terciário", "início", "oligoceno", "predominantemente", "presença", "percentagens", "argilas", "carbonatos", "refletindo", "Terciário", "início", "Oligoceno", "caracterizado", "pela", "presença", "grandes", "percentagens", "argilas", "menor", "quantidade", "carbonatos", "refletindo", "abertura", "contínua", "oceano", "atlântico", "B-epoca", "idade", "metamorficas"]}'], ['{"tags": ["O", "Bacia do Araripe", "Conglomerado basal", "Calcários de Santana", "Arenito superior", "Paleogeno", "Eoceno", "Mesozoico", "Cretáceo", "Jurássico", "Triássico", "Período", "Era", "Sistema", "Epoca", "Idade radiométrica", "Araripe", "Pacote sedimentar", "Rochas vulcânicas", "Intrusivas", "Vulcanoclásticas", "Ultrabásicas", "Paleoceno", "Mesozoico", "Cretáceo", "Jurássico", "Triássico"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "I-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "I-contextoGeologicoDeBacia", "B-baciaSedimentar", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "B-sedimentaresSiliciclasticas", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-periodo", "B-granulometria", "B-epoca", "B-unidadeEstratigrafica", "I-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "I-contextoGeologicoDeBacia", "B-baciaSedimentar", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "B-sedimentaresSiliciclasticas", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade"]}'], ['{"tags": ["O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-ep'], ['{"tags": ["O", "B-periodo", "epoca", "idade", "metamorficas", "grande", "percentagens", "carbonatos", "abertura", "oceano", "atlântico", "terciário", "início", "oligoceno", "predominantemente", "presença", "argilas", "menor", "quantidade", "refletindo", "contínua", "oceanico", "atlântico", "B-epoca", "grande", "percentagens", "carbonatos", "abertura", "oceano", "atlântico", "terciário", "início", "oligoceno", "predominantemente", "presença", "argilas", "menor", "quantidade", "refletindo", "contínua", "oceanico", "atlântico", "B-epoca", "grande", "percentagens", "carbonatos", "abertura", "oceano", "atlântico", "terciário", "início", "oligoceno", "predominantemente", "presença", "argilas", "menor", "quantidade", "refletindo", "contínua", "oceanico", "atlântico", "B-epoca", "grande", "percentagens", "carbonatos", "abertura", "oceano", "atlâ'], ['{"tags": ["O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca"]}'], ['{"tags": ["O", "B-amonites", "B-bacia", "B-lusitânica", "B-registo", "B-sinemuriano", "B-sucessão", "B-tipo", "B-vulcânico"]}'], ['{"tags": ["O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B'], ['{"tags": ["O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B'], ['{"tags": ["1-O", "2-O", "3-O", "4-O", "5-B-eon", "6-O", "7-O", "8-O", "9-O", "10-O", "11-O", "12-O", "13-O", "14-O", "15-O", "16-O", "17-O", "18-O", "19-O", "20-O", "21-O", "22-O", "23-O", "24-O", "25-O", "26-O", "27-O", "28-O", "29-O", "30-O", "31-O", "32-O", "33-B-idade", "34-O", "35-O", "36-O", "37-O", "38-B-periodo", "39-O", "40-O", "41-O", "42-O", "43-O", "44-O", "45-O", "46-O", "47-O", "48-O", "49-O", "50-O", "51-O", "52-O", "53-O", "54-B-idade", "55-O", "56-B-periodo", "57-O", "58-O", "59-O", "60-O", "61-O", "62-O", "63-O", "64-O", "65-O", "66-O", "67-O", "68-O", "69-O", "70-O", "71-O", "72-B-idade", "73-O", "74-B-periodo", "75-O", "76-O'], ['{"tags": ["O", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-granulometria", "B-sedimentaresCarbonaticas", "O", "B-epoca", "O", "B-granulometria", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-sedimentaresCarbonaticas", "O", "B-epoca"]}'], ['{"tags": ["O", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-sedimentaresCarbonaticas", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-periodo", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-granulometria", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-sedimentaresCarbonaticas", "O", "B-granulometria"]}'], ['{"tags": ["O", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-tectonica", "B-conjunto", "B-regiao", "B-partes", "B-dominio", "B-domino", "B-parte", "B-grupo", "B-dominio", "B-relativa", "B-estabilidade", "B-region", "B-parte", "B-tectonica", "B-conjunto", "B-regiao", "B-partes", "B-dominio", "B-domino", "B-parte", "B-grupo", "B-dominio", "B-relativa", "B-estabilidade", "B-region"]}'], ['{"tags": ["O", "B-unidadeEstratigrafica", "I-unidadeEstratigrafica", "B-contextoGeologicoDeBacia", "I-contextoGeologicoDeBacia", "B-baciaSedimentar", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "B-sedimentaresSiliciclasticas", "B-sedimentaresCarbonaticas", "B-idade", "B-granulometria", "B-epoca", "O"]}'], ['{"tags": ["O", "B-contextoGeologicoDeBacia", "B-sistemaPetrolifero", "I-sistemaPetrolifero", "B-sedimentaresSiliciclasticas", "B-sedimentaresCarbonaticas", "B-idade", "B-granulometria", "B-periodo", "B-epoca", "O"]}'], ['{"tags": ["O", "B-granulometria", "B-sedimentaresCarbonaticas", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B'], ['{"tags": ["O", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O"]}'], ['{"tags": ["O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-periodo", "B-granulometria", "B-sedimentaresCarbonaticas", "B-metamorficas", "B-idade", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca"]}'], ['{"tags": ["O", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-", "O", "B-", "O", "B-", "O", "B-", "O", "B-", "O", "B-", "O", "B-"]}'], ['{\n    "tags": [\n        "1-O",\n        "2-O",\n        "3-O",\n        "4-O",\n        "5-O",\n        "6-O",\n        "7-O",\n        "8-O",\n        "9-O"\n    ]\n}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-periodo", "O", "B-granulometria", "O", "B-sedimentaresCarbonaticas", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O"]}'], ['{"tags": ["O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca", "O", "B-epoca"]}'], ['{"tags": ["O", "B-rochas plutónicas", "rochas plutónicas", "complexo gabrodiorítico de cuba - alvito", "dioritos da casa branca e monte novo", "gabros de beja", "do maciço de beja", "que se terão instalado entre o devoniano médio superior e o carbónico inferior", "a folha 43 - a abrange os pórfiros dos baleizão", "carbónico", "o complexo vulcânico de odivelas", "cvO", "atribuído ao carbónico", "e ainda outras formações sedimentare

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: época seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: siluriano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: hirauntiana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sucedem-se seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: epocas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: periodos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: silurianos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: precedência seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: eono seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sede seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: carbonatos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: abertura seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: oceano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: atlantico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: terciario seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: oligoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: presenca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: argilas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: continua seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: tipos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: litologicos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vulcanicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vulcano-clasticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: autoclasicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: piroclasticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ultrabasicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: idades seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: radiometricas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ar-ar seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleogeno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: meso-eoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: significa seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: perigo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: apedeutismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: população seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: mundo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: civilizada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: educada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: triássica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ladiniana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: anisiana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: olenekiana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: grande percentagem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: abertura contínua do oceano atlântico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: rochas vulcânicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: intrusivas e vulcanoclásticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ultrabásicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleoceno ao meso eoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: perigo de apedeutismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: datações pelo método k - ar em ilitas diagenéticas dos arenitos da formação juruá seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: preenchimento dos reservatórios por petróleo ocorreu no n eotriássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: remobilização pelo evento do mega cisalhamento do solimões seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: estabeleceria seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: completo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: araripe seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: deposição seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 1 seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 300 seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: devido seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: argila seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: constituintes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pelitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: metamorficas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: menor seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: atlântico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: terciário seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: predominantemente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: percentagens seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: refletindo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Terciário seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Oligoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: caracterizado seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: contínua seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Bacia do Araripe seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Conglomerado basal seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Calcários de Santana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Arenito superior seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Paleogeno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Eoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Mesozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Cretáceo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Jurássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Triássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Período seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Era seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Sistema seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Idade radiométrica seems not to be NE tag.

In [317]:
report

{'standard': {'...': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '0': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '004': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '010': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '12': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '50': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '996': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-estratigrafia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-subsurface': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-sul-americanos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'Clastos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'Contexto': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'I-estratigrafia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'LOC': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'NOUN': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'O': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ORG': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'TAG': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'VERB': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '_': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'a': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'abo': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'abrange todo o quaternário': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acias': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acional': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acito': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aciço': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aciços': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'acteriológico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'adeano': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'afloramentos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'afra': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'afrogênicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'agner': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ais & Roche': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'alamuni': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'alcretes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'alcários': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'alcíticos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aleocênico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aleomesoproterozoico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aleontologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'algas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'altitude': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'altura média de precipitação': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'amadas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'amazônico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ambienteMarinhoAnóxico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ambienteSedimentacao': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(20)},
  'ameno': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'americana': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'amniotas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'amonites': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'amíferos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'analises bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'analisesBacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'andesito': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'anerozoico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'anortosito': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análise cristalográfico-estrutural da fração magnética da rocha itabirito mostra a existência de duas fases mineralógicas: magnetita e hematita.': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análise de dados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas em águas de poços tubulares': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas em águas de poços tubulares revelaram que em nenhum poço foi detectada a presença de coliformes fecais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas em águas de poços tubulares revelaram que em nenhum poço foi detectada a presença de coliformes fecais.': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apenas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apitaniano': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apresenta': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apresentam': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apresentação': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apresentes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aqüífero fraturado profundidade das entradas de água em apenas 29 poços cadastrados haviam informações confiáveis quanto às profundidades das entradas de água (ea) nos poços.': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ara': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aracterizadas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aranoá': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'arbonífero': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ardia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'areia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'argila': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ariaram': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'artarugas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'arte': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'as': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'as famílias de fraturas com direção n54w e n53e, embora dominadas por ângulos altos de mergulhos , apresentam valores relativamente inferiores às outras 2 famílias .': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto bacteriologico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto bacteriológico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspectoBacteriologico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'assa': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'assaram': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ateriais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aumento gradual da frequência de fetos oportunistas no final do moscoviano–extinção abrupta das lycopsida dominantes e substituição por fetos arbóreos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ação': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'b': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacia hidrográfica': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'baciaSedimentar': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(57)},
  'bacteriologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacteriologico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacteriológico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'balanco': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'balanco hídrico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'balancoHidrico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bentonico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(3)},
  'biologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'biotita': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'biozona ospz6': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'blocos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'blocos ressedimentados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'braquiópodes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'brasil': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'brigam': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bundentemente': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'butterworth visando castro l': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'c': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'camadas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'capitaniano': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'cavalgantes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'caídos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'centimétricas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'central': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'cinturão': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'cinturãoEpidérmico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'clima': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'climatologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'coliformes fecais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'cologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'com': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'começaram a se nuclear as estruturas com componente direcional nas bordas do sinclinal': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'complexo': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'composição': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'conchas recristalizadas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'conclusão': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'conglomerado': {'precision': np.float64(0.0),

In [318]:
f1_macro

{'standard': np.float64(8.886333858486097e-05),
 'heur_len': np.float64(2.8265317305228006e-05),
 'heur_rare': np.float64(6.668953242691234e-05),
 'adversarial': np.float64(5.6403577802502874e-05)}

In [319]:
precision

{'standard': np.float64(7.707353096642911e-05),
 'heur_len': np.float64(1.602717638395342e-05),
 'heur_rare': np.float64(3.704846731806967e-05),
 'adversarial': np.float64(3.873963659561645e-05)}

In [320]:
recall

{'standard': np.float64(0.00021936631390695918),
 'heur_len': np.float64(0.00012397304711497865),
 'heur_rare': np.float64(0.0003468655246598865),
 'adversarial': np.float64(0.000191664391110745)}

In [321]:
precision_micro = []
recall_micro = []
f1_micro = []
f1_macro = []
precision_macro = []
recall_macro = []
f1_weighted = []
precision_weighted = []
recall_weighted = []
accuracy = []
name = []

for keys,value in metrics_all.items():
    name.append(keys)
    precision_micro.append(value['precision_micro'])
    recall_micro.append(value['recall_micro'])
    f1_micro.append(value['f1_micro'])
    precision_macro.append(value['precision_macro'])
    recall_macro.append(value['recall_macro'])
    f1_macro.append(value['f1_macro'])
    precision_weighted.append(value['precision_weighted'])
    recall_weighted.append(value['recall_weighted'])
    f1_weighted.append(value['f1_weighted'])
    accuracy.append(value['accuracy'])

df_results = pd.DataFrame({'name':name,
                           'precision_micro':precision_micro,
                           'recall_micro':recall_micro,
                           'f1_micro':f1_micro,
                           'precision_macro':precision_macro,
                           'recall_macro':recall_macro,
                           'f1_macro':f1_macro,
                           'precision_weighted':precision_weighted,
                           'recall_weighted':recall_weighted,
                           'f1_weighted':f1_weighted,
                           'accuracy':accuracy})

In [322]:
df_results

,name,precision_micro,recall_micro,f1_micro,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,accuracy
0,standard,0.002979,0.011494,0.004731,0.000077,0.000219,0.000089,0.004425,0.011494,0.005216,0.699315
1,heur_len,0.001642,0.012528,0.002904,0.000016,0.000124,0.000028,0.001605,0.012528,0.002833,0.529615
2,heur_rare,0.002808,0.016298,0.004790,0.000037,0.000347,0.000067,0.001753,0.016298,0.003154,0.656876
3,adversarial,0.001474,0.005476,0.002322,0.000039,0.000192,0.000056,0.001068,0.005476,0.001577,0.658037

In [323]:
df_results.to_csv(f'metricas_{model_escolhido}_exclusao.csv', index=False)

In [363]:
report = {}
f1_macro = {}
precision = {}
recall = {}
metrics_all2 = {}

bads_sets = {}

for name, predidction in predictions.items():
    preds = []
    print(predidction)
    for tags_prediction in predidction:
        try:
            preds.append(json.loads(tags_prediction)['tags']) 
        except:
            try:
                preds.append(json.loads(tags_prediction[0])['tags']) 
            except:
                try:
                    preds.append(json.loads(tags_prediction[0][0])['tags']) 
                except:
                    preds.append(['O'])
          
    new_preds = []
    for pred_token in preds:
        if type(pred_token) == str:
            new_preds.append(pred_token)
        else:
            tokens_ajustados = []  
            for token in pred_token:
                try:
                    if int(_).is_integer():
                        tokens_ajustados.extend([token_ajustado])
                    else:
                        tokens_ajustados.extend([token])
                except:
                    try:
                        token_ajustado = token['tag']
                        tokens_ajustados.extend([token_ajustado])
                    except:
                        token_ajustado = token
                        tokens_ajustados.extend([token_ajustado])
            new_preds.append(tokens_ajustados)

        
    if type(golds[name][0][0]) == list:
        actual_golds = [gold[0] for gold in golds[name]]
        print('ok')
    else:
        actual_golds = golds[name]
    actual_preds = new_preds
    print(new_preds)
    clean_golds, cleaned, clean_preds = [], [], []

    for i, (g, p) in enumerate(zip(actual_golds, actual_preds)):
        if type(g[0][0]) == list:
            g_ = g[0]
            print(len(g_), len(p))
            if len(p) < len(g_):
                print('limpou preds'); print(i)
                cleaned.append(i)
                continue  # pula a adição
            elif len(p) > len(g_):
                print('limpou golds'); print(i)
                cleaned.append(i)
                continue  # pula a adição
        else:
            print(len(g), len(p))
            if len(p) < len(g):
                print('limpou preds'); print(i)
                cleaned.append(i)
                continue  # pula a adição
            elif len(p) > len(g):
                print('limpou golds'); print(i)
                cleaned.append(i)
                continue  # pula a adição

    bad = set(cleaned)

    bads_sets[name] = bad

    clean_golds[:] = [g for i, g in enumerate(actual_golds) if i not in bad]
    clean_preds[:] = [p for i, p in enumerate(actual_preds) if i not in bad]


    if len(clean_golds) != 0 and len(clean_preds) != 0:
        report[name] = classification_report(clean_golds, clean_preds, output_dict=True)
        f1_macro[name] = f1_score(clean_golds, clean_preds, average="macro")
        precision[name] = precision_score(clean_golds, clean_preds, average="macro")
        recall[name] = recall_score(clean_golds, clean_preds, average="macro")

        rep = classification_report(clean_golds, clean_preds, scheme=IOB2, zero_division=0, output_dict=True)
        
        metrics2 = {
            "precision_micro":   rep["micro avg"]["precision"],
            "recall_micro":      rep["micro avg"]["recall"],
            "f1_micro":          rep["micro avg"]["f1-score"],
            "precision_macro":   rep["macro avg"]["precision"],
            "recall_macro":      rep["macro avg"]["recall"],
            "f1_macro":          rep["macro avg"]["f1-score"],
            "precision_weighted":rep["weighted avg"]["precision"],
            "recall_weighted":   rep["weighted avg"]["recall"],
            "f1_weighted":       rep["weighted avg"]["f1-score"],
            "accuracy":          accuracy_score(clean_golds, clean_preds),
        }

        metrics_all2[name] = metrics2

[['{"tags": ["O", "B-ambienteSedimentacao", "sedimentos", "quartzosos", "em", "bacias", "tafrogênicas", "depositados", "em", "ambientes", "continentais", "ambientes", "fluvial", "e", "eólico", "passaram", "a", "ter", "grande", "importância", "na", "história", "da", "terra", "durante", "o", "paleomesoproterozoico"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-periodo", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSilicic'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-estratigia", "I-estratigia", "O", "B-aspecto bacteriologico", "O", "B-analises bacteriológicas", "O", "B-coliformes fecais", "O", "B-poços tubulares", "O", "B-porcentagem de coliformes fecais"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-eon", "proterozoico", "fanerozoico", "evidente", "relativamente", "curto", "proliferaram", "desenvolveram", "animais", "plantas", "pluricelulares"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-bacteriológico", "O"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O'], ['{\n    "tags": [\n        "O",\n        "B-estratigrafia",\n        "I-estratigrafia",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "B-sedimentaresSiliciclasticas",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O"\n    ]\n}'], ['{"tags": ["O", "B-NOUN", "I-NOUN", "O", "B-VERB"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-..."]}'], ['{"tags": ["O", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigraf'], ['{"tags": ["O", "B-fácies", "de", "calcários", "argilosos", "lc", "a", "fácies", "lc", "constitui-se", "de", "camadas", "de", "calcários", "argilosos", "calcíticos", "normalmente", "maciços", "formando", "crostas", "duros", "calcretes", "abundentemente", "fossilíferos"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia", "O", "B-estratigrafia"]}'], ['{"tags": ["O", "B-estratigrafia", "B-periodo", "B-sedimentaresSiliciclasticas", "B-ambienteSedimentacao", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "O", "O", "O", "B-estratigrafia", "I-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-TAG", "I-TAG", "O", "B-TAG"]}'], ['{\n    "tags": [\n        "1-O",\n        "2-O",\n        "3-O",\n        "4-O",\n        "5-O",\n        "6-O",\n        "7-O",\n        "8-O",\n        "9-O"\n    ]\n}'], ['{\n    "tags": [\n        "O",\n        "B-estratigrafia",\n        "I-estratigrafia",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "O",\n        "B-estratigrafia"\n    ]\n}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-tectonoEstratigráfica", "O", "B-evoluçãoTectonoEstratigráfica", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-principaisDaEvoluçãoTectonoEstratigráfica", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-causasPrincipaisDaEvoluçãoTectonoEstratigráfica", "O", "B-evoluçãoTectonoEstratigráficaDaSeçãoEstudada", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-evoluçãoTectonoEstratigráficaDaSeçãoEstudada", "O", "B-associadaComAcurvaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-curaDeVariaçãoDoNívelDoMarDevoniano", "O", "B-evoluçãoTectonoEstratigráfica'], ['{"tags": ["O", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "B-sedimentaresSiliciclasticas",'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-métodos", "O", "B-detectores", "O", "B-de-bordas", "O", "B-de-corpos", "O", "B-pouco", "O", "B-influenciado", "O", "B-pela", "O", "B-profundidade", "O", "B-das", "O", "B-fontes"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-estratigrafia", "B-'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-aspecto", "O", "B-análises", "O", "B-bacteriológicas", "O", "B-em", "O", "B-águas", "O", "B-de", "O", "B-poços", "O", "B-tubulares", "O", "B-revelaram", "O", "B-que", "O", "B-em", "O", "B-nenhum", "O"]}'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-...", "..."]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "I-estratigrafia", "O", "B-periodo", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSil'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-clima", "B-ameno", "O", "B-presentando", "O", "B-mediana", "O", "B-elevada", "O", "B-umidade", "O", "B-provavelmente", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia"]}'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-periodo", "B-estratigrafia", "I-estratigrafia", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-sedimentares'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-estratigrafia", "I-estratigrafia", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "O", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratig'], ['{"tags": ["O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-estratigrafia"]}'], ['{"tags": ["O", "B-idade", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-estratigrafia", "B-metamorficas", "B-sedimentaresSiliciclasticas", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "I-unidadeEstratigrafica", "O", "B-idade", "B-estratig'], ['{"tags": ["O", "B-periodo", "B-sedimentaresSiliciclasticas", "B-metamorficas", "B-idade", "B-estratigrafia", "B-ambienteSedimentacao", "B-sedimentaresSiliciclasticas", "B-sedimentaresSiliciclasticas", "B-periodo", "O", "B-idade", "B-idade", "B-idade", "B-estratigrafia", "B-estratigrafia", "B-estratigrafia", "B-estratigrafia", "B-sedimentaresSiliciclasticas", "O", "B-periodo", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B-idade", "B'], ['{"tags": ["O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "I-estratigrafia", "O", "B-estratigrafia", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}'], ['{"tags": ["O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O", "B-estratigrafia", "I-estratigrafia", "O", "B-ambienteSedimentacao", "O", "B-sedimentaresSiliciclasticas", "O", "B-sedimentaresSiliciclasticas", "O"]}'], ['{"tags": ["O", "B-periodo", "O", "B-idade", "O"

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 1-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 2-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 3-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 4-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 5-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 6-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 7-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 8-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 9-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 10-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 11-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: idade seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 9-B-subsurface seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: freqüentemente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: estas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: litologias seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: apresentam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aspecto seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: maciço seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: graptolites seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: braquiópodes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cordados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: moluscos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: espongiários seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: algas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 28-B-estratigrafia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 29-I-estratigrafia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 12-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 13-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: as seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: análises seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: em seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: águas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: de seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ... seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: morro seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: do seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: chapéu seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: mesoproterozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 3-B- seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 9-B- seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 11-B- seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 14-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 15-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 16-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 17-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 18-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 19-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 20-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 21-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 22-B- seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 23-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 24-B- seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 25-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 26-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: apenas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 2-B-sul-americanos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: (pinheiro Machado) seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: /tardío seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: (furongiano) seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: b12 seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: paleontologia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: estratigrafia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: geologia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ecologia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: biologia seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 13-B-epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: rhuddaniana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sucede seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: a seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: hirnantiana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: periodo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: era seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: eon seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ultramáfica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: e seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: compacta seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pleistoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: glacial seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: teve seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: início seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: final seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: climas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: bloco seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

22 23
limpou golds
479
28 15
limpou preds
480
14 14
25 26
limpou golds
482
20 20
47 9
limpou preds
484
22 15
limpou preds
485
52 20
limpou preds
486
43 1
limpou preds
487
55 1
limpou preds
488
32 30
limpou preds
489
21 21
21 8
limpou preds
491
11 11
45 22
limpou preds
493
13 1
limpou preds
494
63 14
limpou preds
495
28 30
limpou golds
496
43 17
limpou preds
497
25 26
limpou golds
498
34 12
limpou preds
499

c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: época seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: período seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Bacia do Araripe seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Conglomerado basal seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Calcários de Santana seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Arenito superior seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Paleogeno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Eoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Mesozoico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Cretáceo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Jurássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Triássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Período seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Era seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Sistema seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Idade radiométrica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Araripe seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Pacote sedimentar seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Rochas vulcânicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Intrusivas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Vulcanoclásticas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Ultrabásicas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Paleoceno seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: perigo de apedeutismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: civilizada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: educada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: moluscos bivalves seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: coquinas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fósseis seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: maioria da população mundial seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sequer foi civilizada seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: apendeutismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: usualmente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: esses seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: arenitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: calcíferos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fossilíferos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: folhelhos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: alterados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: pastilhas seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: predominam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aparecem seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sequer seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: maioria seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: mundo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: que seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: dirá seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: vezes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: observa-se seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: presença seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: perigo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: conodontes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cambriano seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: triássico seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: apedeutismo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fóssil seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: registro seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 37-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 38-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 39-B-epoca seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 40-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: 41-O seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: siltitos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: derivam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: processos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: decantação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: gravitacionais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: mtds seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: identificados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: estratificados seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: blocos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: hemipelágica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: sedimentação seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fácies seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: provavelmente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: representa seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: Hemipelagic seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: típica seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: envolvendo seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: representam seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: plagioclásio seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: ripiformes seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: fino seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: aciculares seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: dispostos randomicamente seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: cristais seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
c:\Users\user\Documents\mestrado\ner_splits\ner_splits\Lib\site-packages\seqeval\metrics\sequence_labeling.py:171: UserWarning: finos seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

In [364]:
accuracy_score

In [365]:
report

{'standard': {'...': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '12': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-estratigrafia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-subsurface': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'B-sul-americanos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'Clastos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'I-estratigrafia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'LOC': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'NOUN': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'O': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ORG': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'TAG': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'VERB': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  '_': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'abrange todo o quaternário': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aciço': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aleontologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'algas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ambienteSedimentacao': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'ameno': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'analises bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'anortosito': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análise de dados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'análises bacteriológicas em águas de poços tubulares revelaram que em nenhum poço foi detectada a presença de coliformes fecais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'apresentam': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto bacteriologico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'aspecto bacteriológico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'baciaSedimentar': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'bacteriologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacteriológicas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'bacteriológico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'biologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'biotita': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'biozona ospz6': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'braquiópodes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'capitaniano': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'caídos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'clima': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'climatologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'coliformes fecais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'cologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'constituinteRochaSedimentar': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(5)},
  'contextoGeologicoDeBacia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(7)},
  'cordados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'dade': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'desmembramento': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'diorito': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'e': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'e elevada': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'e elevadas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'e valido para as bacias marginais do sudeste brasileiro': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ecologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'elementoQuimico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'elevada': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'em geral': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'eologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'eon': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'epoca': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(11)},
  'era': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'esoproterozoico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'espongiários': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'estatística': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'estes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'estratigia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'estratigrafia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'foram': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'formação': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'fosseis': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'furongiano)': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'gabro': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'geografia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'geologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'geomorfologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'geoquímica': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'granulometria': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'graptolites': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'guas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'hapéu': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'hidrologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'idade': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(7)},
  'iologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'itologias': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'lgas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'm': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'magmaticas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(11)},
  'mediana': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'metamorficas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'metodologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'microbiologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'mineral': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'moluscos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'monzodiorito / monzogabro com feldspatóide ; 14 .': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'máfico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'máficos são pirobólio e / ou biotita.': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'nálises': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'não': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'o': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'observados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'oluscos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ordados': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'orro': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'ou': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'paisagem': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'paleontologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'palinologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'parcelamento': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'penas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'periodo': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(14)},
  'permeabilidade': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'petrologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'pinheiro Machado)': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'pirobólico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'placa árabica': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'planctonico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'porcentagem de coliformes fecais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'porosidade': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'poços': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'poços tubulares': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'presentam': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'presentando': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'presente trabalho': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'principais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'procedimentoMetodologico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(1)},
  'provavelmente': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'pyrobiótico': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'póços tubulares': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'raptolites': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'raquiópodes': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'região': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'reqüentemente': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'rocha magmática': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'rurais': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  's': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'sedimentaresCarbonaticas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(6)},
  'sedimentaresSiliciclasticas': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(18)},
  'sedimentologia': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'sedimentos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'sistemaPetrolifero': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(2)},
  'solos': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},
  'specto': {'precision': np.float64(0.0),
   'recall': np.float64(0.0),
   'f1-score': np.float64(0.0),
   'support': np.int64(0)},

In [366]:
f1_macro

{'standard': np.float64(0.0),
 'heur_len': np.float64(0.0),
 'heur_rare': np.float64(0.0),
 'adversarial': np.float64(0.000779028765088539)}

In [367]:
precision

{'standard': np.float64(0.0),
 'heur_len': np.float64(0.0),
 'heur_rare': np.float64(0.0),
 'adversarial': np.float64(0.0007715057220007716)}

In [368]:
recall

{'standard': np.float64(0.0),
 'heur_len': np.float64(0.0),
 'heur_rare': np.float64(0.0),
 'adversarial': np.float64(0.0035650623885918)}

In [369]:
metrics_all2

{'standard': {'precision_micro': np.float64(0.0),
  'recall_micro': np.float64(0.0),
  'f1_micro': np.float64(0.0),
  'precision_macro': np.float64(0.0),
  'recall_macro': np.float64(0.0),
  'f1_macro': np.float64(0.0),
  'precision_weighted': np.float64(0.0),
  'recall_weighted': np.float64(0.0),
  'f1_weighted': np.float64(0.0),
  'accuracy': 0.5384177575412635},
 'heur_len': {'precision_micro': np.float64(0.0),
  'recall_micro': np.float64(0.0),
  'f1_micro': np.float64(0.0),
  'precision_macro': np.float64(0.0),
  'recall_macro': np.float64(0.0),
  'f1_macro': np.float64(0.0),
  'precision_weighted': np.float64(0.0),
  'recall_weighted': np.float64(0.0),
  'f1_weighted': np.float64(0.0),
  'accuracy': 0.3188010899182561},
 'heur_rare': {'precision_micro': np.float64(0.0),
  'recall_micro': np.float64(0.0),
  'f1_micro': np.float64(0.0),
  'precision_macro': np.float64(0.0),
  'recall_macro': np.float64(0.0),
  'f1_macro': np.float64(0.0),
  'precision_weighted': np.float64(0.0),
  'recall_weighted': np.float64(0.0),
  'f1_weighted': np.float64(0.0),
  'accuracy': 0.5430555555555555},
 'adversarial': {'precision_micro': np.float64(0.001401541695865452),
  'recall_micro': np.float64(0.009478672985781991),
  'f1_micro': np.float64(0.002442002442002442),
  'precision_macro': np.float64(0.0007715057220007716),
  'recall_macro': np.float64(0.0035650623885918),
  'f1_macro': np.float64(0.000779028765088539),
  'precision_weighted': np.float64(0.004752133981170629),
  'recall_weighted': np.float64(0.009478672985781991),
  'f1_weighted': np.float64(0.00476486254222434),
  'accuracy': 0.33690527218174027}}

In [370]:
precision_micro2 = []
recall_micro2 = []
f1_micro2 = []
f1_macro2 = []
precision_macro2 = []
recall_macro2 = []
f1_weighted2 = []
precision_weighted2 = []
recall_weighted2 = []
accuracy2 = []
name2 = []

for keys,value in metrics_all2.items():
    name2.append(keys)
    precision_micro2.append(value['precision_micro'])
    recall_micro2.append(value['recall_micro'])
    f1_micro2.append(value['f1_micro'])
    precision_macro2.append(value['precision_macro'])
    recall_macro2.append(value['recall_macro'])
    f1_macro2.append(value['f1_macro'])
    precision_weighted2.append(value['precision_weighted'])
    recall_weighted2.append(value['recall_weighted'])
    f1_weighted2.append(value['f1_weighted'])
    accuracy2.append(value['accuracy'])

df_results2 = pd.DataFrame({'name':name2,
                           'precision_micro':precision_micro2,
                           'recall_micro':recall_micro2,
                           'f1_micro':f1_micro2,
                           'precision_macro':precision_macro2,
                           'recall_macro':recall_macro2,
                           'f1_macro':f1_macro2,
                           'precision_weighted':precision_weighted2,
                           'recall_weighted':recall_weighted2,
                           'f1_weighted':f1_weighted2,
                           'accuracy_score':accuracy2})

In [371]:
df_results2.to_csv(f'metricas_{model_escolhido}_complemento.csv', index=False)

In [372]:
df_results2

,name,precision_micro,recall_micro,f1_micro,precision_macro,recall_macro,f1_macro,precision_weighted,recall_weighted,f1_weighted,accuracy_score
0,standard,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.538418
1,heur_len,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318801
2,heur_rare,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.543056
3,adversarial,0.001402,0.009479,0.002442,0.000772,0.003565,0.000779,0.004752,0.009479,0.004765,0.336905